// Generated file. Do not edit.
// Autogenerated from Pigeon (v27.3.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.xuehua.xue_hua_media_compression

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object MessagesPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/**
 * 输入位置：0 = 内存字节，1 = 路径 / URI。
 *
 * Source kind: 0 = in-memory bytes, 1 = filesystem path / URI.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class SourceMsg (
  val kind: Long,
  val bytes: ByteArray? = null,
  val path: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SourceMsg {
      val kind = pigeonVar_list[0] as Long
      val bytes = pigeonVar_list[1] as ByteArray?
      val path = pigeonVar_list[2] as String?
      return SourceMsg(kind, bytes, path)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      kind,
      bytes,
      path,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as SourceMsg
    return MessagesPigeonUtils.deepEquals(this.kind, other.kind) && MessagesPigeonUtils.deepEquals(this.bytes, other.bytes) && MessagesPigeonUtils.deepEquals(this.path, other.path)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.kind)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.bytes)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.path)
    return result
  }
  override fun toString(): String {
    return "SourceMsg(kind=$kind, bytes=${bytes?.contentToString()}, path=$path)"
  }
}

/**
 * 输出位置：0 = 内存字节，1 = 文件路径。
 *
 * Destination kind: 0 = in-memory bytes, 1 = filesystem path.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class DestinationMsg (
  val kind: Long,
  val path: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DestinationMsg {
      val kind = pigeonVar_list[0] as Long
      val path = pigeonVar_list[1] as String?
      return DestinationMsg(kind, path)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      kind,
      path,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as DestinationMsg
    return MessagesPigeonUtils.deepEquals(this.kind, other.kind) && MessagesPigeonUtils.deepEquals(this.path, other.path)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.kind)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.path)
    return result
  }
  override fun toString(): String {
    return "DestinationMsg(kind=$kind, path=$path)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ImageOptionsMsg (
  val format: String,
  val quality: Long,
  val maxDimension: Long? = null,
  val keepMetadata: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ImageOptionsMsg {
      val format = pigeonVar_list[0] as String
      val quality = pigeonVar_list[1] as Long
      val maxDimension = pigeonVar_list[2] as Long?
      val keepMetadata = pigeonVar_list[3] as Boolean
      return ImageOptionsMsg(format, quality, maxDimension, keepMetadata)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      format,
      quality,
      maxDimension,
      keepMetadata,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ImageOptionsMsg
    return MessagesPigeonUtils.deepEquals(this.format, other.format) && MessagesPigeonUtils.deepEquals(this.quality, other.quality) && MessagesPigeonUtils.deepEquals(this.maxDimension, other.maxDimension) && MessagesPigeonUtils.deepEquals(this.keepMetadata, other.keepMetadata)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.format)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.quality)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.maxDimension)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.keepMetadata)
    return result
  }
  override fun toString(): String {
    return "ImageOptionsMsg(format=$format, quality=$quality, maxDimension=$maxDimension, keepMetadata=$keepMetadata)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class VideoOptionsMsg (
  val codec: String,
  val bitrate: Long,
  val fps: Long? = null,
  val maxDimension: Long? = null,
  val keyframeInterval: Long? = null,
  val keepAudio: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): VideoOptionsMsg {
      val codec = pigeonVar_list[0] as String
      val bitrate = pigeonVar_list[1] as Long
      val fps = pigeonVar_list[2] as Long?
      val maxDimension = pigeonVar_list[3] as Long?
      val keyframeInterval = pigeonVar_list[4] as Long?
      val keepAudio = pigeonVar_list[5] as Boolean
      return VideoOptionsMsg(codec, bitrate, fps, maxDimension, keyframeInterval, keepAudio)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      codec,
      bitrate,
      fps,
      maxDimension,
      keyframeInterval,
      keepAudio,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as VideoOptionsMsg
    return MessagesPigeonUtils.deepEquals(this.codec, other.codec) && MessagesPigeonUtils.deepEquals(this.bitrate, other.bitrate) && MessagesPigeonUtils.deepEquals(this.fps, other.fps) && MessagesPigeonUtils.deepEquals(this.maxDimension, other.maxDimension) && MessagesPigeonUtils.deepEquals(this.keyframeInterval, other.keyframeInterval) && MessagesPigeonUtils.deepEquals(this.keepAudio, other.keepAudio)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.codec)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.bitrate)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.fps)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.maxDimension)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.keyframeInterval)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.keepAudio)
    return result
  }
  override fun toString(): String {
    return "VideoOptionsMsg(codec=$codec, bitrate=$bitrate, fps=$fps, maxDimension=$maxDimension, keyframeInterval=$keyframeInterval, keepAudio=$keepAudio)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ImageCapabilitiesMsg (
  val inputFormats: List<String>,
  val outputFormats: List<String>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ImageCapabilitiesMsg {
      val inputFormats = pigeonVar_list[0] as List<String>
      val outputFormats = pigeonVar_list[1] as List<String>
      return ImageCapabilitiesMsg(inputFormats, outputFormats)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      inputFormats,
      outputFormats,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ImageCapabilitiesMsg
    return MessagesPigeonUtils.deepEquals(this.inputFormats, other.inputFormats) && MessagesPigeonUtils.deepEquals(this.outputFormats, other.outputFormats)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.inputFormats)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.outputFormats)
    return result
  }
  override fun toString(): String {
    return "ImageCapabilitiesMsg(inputFormats=$inputFormats, outputFormats=$outputFormats)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class VideoCapabilitiesMsg (
  val encoderName: String? = null,
  val codecs: List<String>,
  val acceptsContentUri: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): VideoCapabilitiesMsg {
      val encoderName = pigeonVar_list[0] as String?
      val codecs = pigeonVar_list[1] as List<String>
      val acceptsContentUri = pigeonVar_list[2] as Boolean
      return VideoCapabilitiesMsg(encoderName, codecs, acceptsContentUri)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      encoderName,
      codecs,
      acceptsContentUri,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as VideoCapabilitiesMsg
    return MessagesPigeonUtils.deepEquals(this.encoderName, other.encoderName) && MessagesPigeonUtils.deepEquals(this.codecs, other.codecs) && MessagesPigeonUtils.deepEquals(this.acceptsContentUri, other.acceptsContentUri)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.encoderName)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.codecs)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.acceptsContentUri)
    return result
  }
  override fun toString(): String {
    return "VideoCapabilitiesMsg(encoderName=$encoderName, codecs=$codecs, acceptsContentUri=$acceptsContentUri)"
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SourceMsg.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DestinationMsg.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ImageOptionsMsg.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          VideoOptionsMsg.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ImageCapabilitiesMsg.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          VideoCapabilitiesMsg.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is SourceMsg -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is DestinationMsg -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is ImageOptionsMsg -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is VideoOptionsMsg -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is ImageCapabilitiesMsg -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is VideoCapabilitiesMsg -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface MediaCompressionHostApi {
  fun createJob(): Long
  fun queryImageCapabilities(): ImageCapabilitiesMsg
  fun startImageCompress(id: Long, source: SourceMsg, destination: DestinationMsg, options: ImageOptionsMsg, callback: (Result<Unit>) -> Unit)
  fun queryVideoCapabilities(): VideoCapabilitiesMsg
  fun startVideoCompress(id: Long, inputPath: String, outputPath: String, options: VideoOptionsMsg, callback: (Result<Unit>) -> Unit)
  fun cancelJob(id: Long)
  fun disposeJob(id: Long)

  companion object {
    /** The codec used by MediaCompressionHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `MediaCompressionHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: MediaCompressionHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.xue_hua_media_compression_platform_interface.MediaCompressionHostApi.createJob$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.createJob())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.xue_hua_media_compression_platform_interface.MediaCompressionHostApi.queryImageCapabilities$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.queryImageCapabilities())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.xue_hua_media_compression_platform_interface.MediaCompressionHostApi.startImageCompress$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idArg = args[0] as Long
            val sourceArg = args[1] as SourceMsg
            val destinationArg = args[2] as DestinationMsg
            val optionsArg = args[3] as ImageOptionsMsg
            api.startImageCompress(idArg, sourceArg, destinationArg, optionsArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.xue_hua_media_compression_platform_interface.MediaCompressionHostApi.queryVideoCapabilities$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.queryVideoCapabilities())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.xue_hua_media_compression_platform_interface.MediaCompressionHostApi.startVideoCompress$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idArg = args[0] as Long
            val inputPathArg = args[1] as String
            val outputPathArg = args[2] as String
            val optionsArg = args[3] as VideoOptionsMsg
            api.startVideoCompress(idArg, inputPathArg, outputPathArg, optionsArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.xue_hua_media_compression_platform_interface.MediaCompressionHostApi.cancelJob$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.cancelJob(idArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.xue_hua_media_compression_platform_interface.MediaCompressionHostApi.disposeJob$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.disposeJob(idArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
