include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  exclude:
    - '**/*.g.dart'
    - '**/*.g.kt'
    - '**/*.g.swift'
    - '**/*.g.h'
    - '**/*.g.cpp'
    - '**/*.g.cc'
    - 'example/build/**'
    - 'test_driver/**'
