// Generated file. Do not edit.
// Autogenerated from Pigeon (v27.3.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_MESSAGES_G_H_
#define PIGEON_MESSAGES_G_H_
#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <ostream>
#include <string>

namespace xue_hua_media_compression {


// Generated class from Pigeon.

class FlutterError {
 public:
  explicit FlutterError(const std::string& code)
    : code_(code) {}
  explicit FlutterError(const std::string& code, const std::string& message)
    : code_(code), message_(message) {}
  explicit FlutterError(const std::string& code, const std::string& message, const ::flutter::EncodableValue& details)
    : code_(code), message_(message), details_(details) {}

  const std::string& code() const { return code_; }
  const std::string& message() const { return message_; }
  const ::flutter::EncodableValue& details() const { return details_; }

 private:
  std::string code_;
  std::string message_;
  ::flutter::EncodableValue details_;
};

template<class T> class ErrorOr {
 public:
  ErrorOr(const T& rhs) : v_(rhs) {}
  ErrorOr(const T&& rhs) : v_(std::move(rhs)) {}
  ErrorOr(const FlutterError& rhs) : v_(rhs) {}
  ErrorOr(const FlutterError&& rhs) : v_(std::move(rhs)) {}

  bool has_error() const { return std::holds_alternative<FlutterError>(v_); }
  const T& value() const { return std::get<T>(v_); };
  const FlutterError& error() const { return std::get<FlutterError>(v_); };

 private:
  friend class MediaCompressionHostApi;
  ErrorOr() = default;
  T TakeValue() && { return std::get<T>(std::move(v_)); }

  std::variant<T, FlutterError> v_;
};



// 输入位置：0 = 内存字节，1 = 路径 / URI。
//
// Source kind: 0 = in-memory bytes, 1 = filesystem path / URI.
//
// Generated class from Pigeon that represents data sent in messages.
class SourceMsg {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit SourceMsg(int64_t kind);

  // Constructs an object setting all fields.
  explicit SourceMsg(
    int64_t kind,
    const std::vector<uint8_t>* bytes,
    const std::string* path);

  int64_t kind() const;
  void set_kind(int64_t value_arg);

  const std::vector<uint8_t>* bytes() const;
  void set_bytes(const std::vector<uint8_t>* value_arg);
  void set_bytes(const std::vector<uint8_t>& value_arg);

  const std::string* path() const;
  void set_path(const std::string_view* value_arg);
  void set_path(std::string_view value_arg);

  bool operator==(const SourceMsg& other) const;
  bool operator!=(const SourceMsg& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
  /// Stream output operator for formatted string representation.
  friend std::ostream& operator<<(std::ostream& os, const SourceMsg& obj);
 private:
  static SourceMsg FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class MediaCompressionHostApi;
  friend class PigeonInternalCodecSerializer;
  int64_t kind_;
  std::optional<std::vector<uint8_t>> bytes_;
  std::optional<std::string> path_;
};


// 输出位置：0 = 内存字节，1 = 文件路径。
//
// Destination kind: 0 = in-memory bytes, 1 = filesystem path.
//
// Generated class from Pigeon that represents data sent in messages.
class DestinationMsg {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit DestinationMsg(int64_t kind);

  // Constructs an object setting all fields.
  explicit DestinationMsg(
    int64_t kind,
    const std::string* path);

  int64_t kind() const;
  void set_kind(int64_t value_arg);

  const std::string* path() const;
  void set_path(const std::string_view* value_arg);
  void set_path(std::string_view value_arg);

  bool operator==(const DestinationMsg& other) const;
  bool operator!=(const DestinationMsg& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
  /// Stream output operator for formatted string representation.
  friend std::ostream& operator<<(std::ostream& os, const DestinationMsg& obj);
 private:
  static DestinationMsg FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class MediaCompressionHostApi;
  friend class PigeonInternalCodecSerializer;
  int64_t kind_;
  std::optional<std::string> path_;
};


// Generated class from Pigeon that represents data sent in messages.
class ImageOptionsMsg {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit ImageOptionsMsg(
    const std::string& format,
    int64_t quality,
    bool keep_metadata);

  // Constructs an object setting all fields.
  explicit ImageOptionsMsg(
    const std::string& format,
    int64_t quality,
    const int64_t* max_dimension,
    bool keep_metadata);

  const std::string& format() const;
  void set_format(std::string_view value_arg);

  int64_t quality() const;
  void set_quality(int64_t value_arg);

  const int64_t* max_dimension() const;
  void set_max_dimension(const int64_t* value_arg);
  void set_max_dimension(int64_t value_arg);

  bool keep_metadata() const;
  void set_keep_metadata(bool value_arg);

  bool operator==(const ImageOptionsMsg& other) const;
  bool operator!=(const ImageOptionsMsg& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
  /// Stream output operator for formatted string representation.
  friend std::ostream& operator<<(std::ostream& os, const ImageOptionsMsg& obj);
 private:
  static ImageOptionsMsg FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class MediaCompressionHostApi;
  friend class PigeonInternalCodecSerializer;
  std::string format_;
  int64_t quality_;
  std::optional<int64_t> max_dimension_;
  bool keep_metadata_;
};


// Generated class from Pigeon that represents data sent in messages.
class VideoOptionsMsg {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit VideoOptionsMsg(
    const std::string& codec,
    int64_t bitrate,
    bool keep_audio);

  // Constructs an object setting all fields.
  explicit VideoOptionsMsg(
    const std::string& codec,
    int64_t bitrate,
    const int64_t* fps,
    const int64_t* max_dimension,
    const int64_t* keyframe_interval,
    bool keep_audio);

  const std::string& codec() const;
  void set_codec(std::string_view value_arg);

  int64_t bitrate() const;
  void set_bitrate(int64_t value_arg);

  const int64_t* fps() const;
  void set_fps(const int64_t* value_arg);
  void set_fps(int64_t value_arg);

  const int64_t* max_dimension() const;
  void set_max_dimension(const int64_t* value_arg);
  void set_max_dimension(int64_t value_arg);

  const int64_t* keyframe_interval() const;
  void set_keyframe_interval(const int64_t* value_arg);
  void set_keyframe_interval(int64_t value_arg);

  bool keep_audio() const;
  void set_keep_audio(bool value_arg);

  bool operator==(const VideoOptionsMsg& other) const;
  bool operator!=(const VideoOptionsMsg& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
  /// Stream output operator for formatted string representation.
  friend std::ostream& operator<<(std::ostream& os, const VideoOptionsMsg& obj);
 private:
  static VideoOptionsMsg FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class MediaCompressionHostApi;
  friend class PigeonInternalCodecSerializer;
  std::string codec_;
  int64_t bitrate_;
  std::optional<int64_t> fps_;
  std::optional<int64_t> max_dimension_;
  std::optional<int64_t> keyframe_interval_;
  bool keep_audio_;
};


// Generated class from Pigeon that represents data sent in messages.
class ImageCapabilitiesMsg {
 public:
  // Constructs an object setting all fields.
  explicit ImageCapabilitiesMsg(
    const ::flutter::EncodableList& input_formats,
    const ::flutter::EncodableList& output_formats);

  const ::flutter::EncodableList& input_formats() const;
  void set_input_formats(const ::flutter::EncodableList& value_arg);

  const ::flutter::EncodableList& output_formats() const;
  void set_output_formats(const ::flutter::EncodableList& value_arg);

  bool operator==(const ImageCapabilitiesMsg& other) const;
  bool operator!=(const ImageCapabilitiesMsg& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
  /// Stream output operator for formatted string representation.
  friend std::ostream& operator<<(std::ostream& os, const ImageCapabilitiesMsg& obj);
 private:
  static ImageCapabilitiesMsg FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class MediaCompressionHostApi;
  friend class PigeonInternalCodecSerializer;
  ::flutter::EncodableList input_formats_;
  ::flutter::EncodableList output_formats_;
};


// Generated class from Pigeon that represents data sent in messages.
class VideoCapabilitiesMsg {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit VideoCapabilitiesMsg(
    const ::flutter::EncodableList& codecs,
    bool accepts_content_uri);

  // Constructs an object setting all fields.
  explicit VideoCapabilitiesMsg(
    const std::string* encoder_name,
    const ::flutter::EncodableList& codecs,
    bool accepts_content_uri);

  const std::string* encoder_name() const;
  void set_encoder_name(const std::string_view* value_arg);
  void set_encoder_name(std::string_view value_arg);

  const ::flutter::EncodableList& codecs() const;
  void set_codecs(const ::flutter::EncodableList& value_arg);

  bool accepts_content_uri() const;
  void set_accepts_content_uri(bool value_arg);

  bool operator==(const VideoCapabilitiesMsg& other) const;
  bool operator!=(const VideoCapabilitiesMsg& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
  /// Stream output operator for formatted string representation.
  friend std::ostream& operator<<(std::ostream& os, const VideoCapabilitiesMsg& obj);
 private:
  static VideoCapabilitiesMsg FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class MediaCompressionHostApi;
  friend class PigeonInternalCodecSerializer;
  std::optional<std::string> encoder_name_;
  ::flutter::EncodableList codecs_;
  bool accepts_content_uri_;
};


class PigeonInternalCodecSerializer : public ::flutter::StandardCodecSerializer {
 public:
  PigeonInternalCodecSerializer();
  inline static PigeonInternalCodecSerializer& GetInstance() {
    static PigeonInternalCodecSerializer sInstance;
    return sInstance;
  }

  void WriteValue(
    const ::flutter::EncodableValue& value,
    ::flutter::ByteStreamWriter* stream) const override;
 protected:
  ::flutter::EncodableValue ReadValueOfType(
    uint8_t type,
    ::flutter::ByteStreamReader* stream) const override;
};

// Generated interface from Pigeon that represents a handler of messages from Flutter.
class MediaCompressionHostApi {
 public:
  MediaCompressionHostApi(const MediaCompressionHostApi&) = delete;
  MediaCompressionHostApi& operator=(const MediaCompressionHostApi&) = delete;
  virtual ~MediaCompressionHostApi() {}
  virtual ErrorOr<int64_t> CreateJob() = 0;
  virtual ErrorOr<ImageCapabilitiesMsg> QueryImageCapabilities() = 0;
  virtual void StartImageCompress(
    int64_t id,
    const SourceMsg& source,
    const DestinationMsg& destination,
    const ImageOptionsMsg& options,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual ErrorOr<VideoCapabilitiesMsg> QueryVideoCapabilities() = 0;
  virtual void StartVideoCompress(
    int64_t id,
    const std::string& input_path,
    const std::string& output_path,
    const VideoOptionsMsg& options,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual std::optional<FlutterError> CancelJob(int64_t id) = 0;
  virtual std::optional<FlutterError> DisposeJob(int64_t id) = 0;

  // The codec used by MediaCompressionHostApi.
  static const ::flutter::StandardMessageCodec& GetCodec();
  // Sets up an instance of `MediaCompressionHostApi` to handle messages through the `binary_messenger`.
  static void SetUp(
    ::flutter::BinaryMessenger* binary_messenger,
    MediaCompressionHostApi* api);
  static void SetUp(
    ::flutter::BinaryMessenger* binary_messenger,
    MediaCompressionHostApi* api,
    const std::string& message_channel_suffix);
  static ::flutter::EncodableValue WrapError(std::string_view error_message);
  static ::flutter::EncodableValue WrapError(const FlutterError& error);
 protected:
  MediaCompressionHostApi() = default;
};
}  // namespace xue_hua_media_compression
#endif  // PIGEON_MESSAGES_G_H_
