// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/image.dart';
import 'api/media.dart';
import 'api/platform/apple.dart';
import 'api/simple.dart';
import 'api/traits.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiMediaRustInit();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -2013770217;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'xue_hua_media_compression',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<VideoResult> crateApiPlatformAppleAppleVideoCompressorCompress({
    required String inputPath,
    required String outputPath,
    required VideoOptions opts,
  });

  Future<Uint8List> crateApiImageGenericImageCompressorCompress({
    required List<int> input,
    required ImageOptions opts,
  });

  String crateApiSimpleGreet({required String name});

  Future<ImageOptions> crateApiTraitsImageOptionsDefault();

  Future<void> crateApiSimpleInitApp();

  Future<Uint8List> crateApiMediaRustCompressImage({
    required List<int> input,
    required ImageOptions opts,
  });

  Future<BigInt> crateApiMediaRustCompressImageFile({
    required String inputPath,
    required String outputPath,
    required ImageOptions opts,
  });

  Future<VideoResult> crateApiMediaRustCompressVideo({
    required String inputPath,
    required String outputPath,
    required VideoOptions opts,
  });

  Future<ImageOptions> crateApiMediaRustDefaultImageOptions();

  Future<VideoOptions> crateApiMediaRustDefaultVideoOptions();

  Future<void> crateApiMediaRustInit();

  Future<String> crateApiMediaRustVideoBackendName();

  Future<VideoOptions> crateApiTraitsVideoOptionsDefault();

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_AppleVideoCompressor;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_AppleVideoCompressor;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_AppleVideoCompressorPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_GenericImageCompressor;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_GenericImageCompressor;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_GenericImageCompressorPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<VideoResult> crateApiPlatformAppleAppleVideoCompressorCompress({
    required String inputPath,
    required String outputPath,
    required VideoOptions opts,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(inputPath, serializer);
          sse_encode_String(outputPath, serializer);
          sse_encode_box_autoadd_video_options(opts, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_video_result,
          decodeErrorData: sse_decode_media_error,
        ),
        constMeta: kCrateApiPlatformAppleAppleVideoCompressorCompressConstMeta,
        argValues: [inputPath, outputPath, opts],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiPlatformAppleAppleVideoCompressorCompressConstMeta =>
      const TaskConstMeta(
        debugName: "AppleVideoCompressor_compress",
        argNames: ["inputPath", "outputPath", "opts"],
      );

  @override
  Future<Uint8List> crateApiImageGenericImageCompressorCompress({
    required List<int> input,
    required ImageOptions opts,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(input, serializer);
          sse_encode_box_autoadd_image_options(opts, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_media_error,
        ),
        constMeta: kCrateApiImageGenericImageCompressorCompressConstMeta,
        argValues: [input, opts],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageGenericImageCompressorCompressConstMeta =>
      const TaskConstMeta(
        debugName: "GenericImageCompressor_compress",
        argNames: ["input", "opts"],
      );

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<ImageOptions> crateApiTraitsImageOptionsDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_image_options,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTraitsImageOptionsDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTraitsImageOptionsDefaultConstMeta =>
      const TaskConstMeta(debugName: "image_options_default", argNames: []);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<Uint8List> crateApiMediaRustCompressImage({
    required List<int> input,
    required ImageOptions opts,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(input, serializer);
          sse_encode_box_autoadd_image_options(opts, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_media_error,
        ),
        constMeta: kCrateApiMediaRustCompressImageConstMeta,
        argValues: [input, opts],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMediaRustCompressImageConstMeta =>
      const TaskConstMeta(
        debugName: "rust_compress_image",
        argNames: ["input", "opts"],
      );

  @override
  Future<BigInt> crateApiMediaRustCompressImageFile({
    required String inputPath,
    required String outputPath,
    required ImageOptions opts,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(inputPath, serializer);
          sse_encode_String(outputPath, serializer);
          sse_encode_box_autoadd_image_options(opts, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: sse_decode_media_error,
        ),
        constMeta: kCrateApiMediaRustCompressImageFileConstMeta,
        argValues: [inputPath, outputPath, opts],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMediaRustCompressImageFileConstMeta =>
      const TaskConstMeta(
        debugName: "rust_compress_image_file",
        argNames: ["inputPath", "outputPath", "opts"],
      );

  @override
  Future<VideoResult> crateApiMediaRustCompressVideo({
    required String inputPath,
    required String outputPath,
    required VideoOptions opts,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(inputPath, serializer);
          sse_encode_String(outputPath, serializer);
          sse_encode_box_autoadd_video_options(opts, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_video_result,
          decodeErrorData: sse_decode_media_error,
        ),
        constMeta: kCrateApiMediaRustCompressVideoConstMeta,
        argValues: [inputPath, outputPath, opts],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMediaRustCompressVideoConstMeta =>
      const TaskConstMeta(
        debugName: "rust_compress_video",
        argNames: ["inputPath", "outputPath", "opts"],
      );

  @override
  Future<ImageOptions> crateApiMediaRustDefaultImageOptions() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_image_options,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMediaRustDefaultImageOptionsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMediaRustDefaultImageOptionsConstMeta =>
      const TaskConstMeta(
        debugName: "rust_default_image_options",
        argNames: [],
      );

  @override
  Future<VideoOptions> crateApiMediaRustDefaultVideoOptions() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_video_options,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMediaRustDefaultVideoOptionsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMediaRustDefaultVideoOptionsConstMeta =>
      const TaskConstMeta(
        debugName: "rust_default_video_options",
        argNames: [],
      );

  @override
  Future<void> crateApiMediaRustInit() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMediaRustInitConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMediaRustInitConstMeta =>
      const TaskConstMeta(debugName: "rust_init", argNames: []);

  @override
  Future<String> crateApiMediaRustVideoBackendName() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMediaRustVideoBackendNameConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMediaRustVideoBackendNameConstMeta =>
      const TaskConstMeta(debugName: "rust_video_backend_name", argNames: []);

  @override
  Future<VideoOptions> crateApiTraitsVideoOptionsDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_video_options,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTraitsVideoOptionsDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTraitsVideoOptionsDefaultConstMeta =>
      const TaskConstMeta(debugName: "video_options_default", argNames: []);

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_AppleVideoCompressor => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppleVideoCompressor;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_AppleVideoCompressor => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppleVideoCompressor;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_GenericImageCompressor => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGenericImageCompressor;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_GenericImageCompressor => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGenericImageCompressor;

  @protected
  AppleVideoCompressor
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppleVideoCompressor(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AppleVideoCompressorImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  GenericImageCompressor
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGenericImageCompressor(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return GenericImageCompressorImpl.frbInternalDcoDecode(
      raw as List<dynamic>,
    );
  }

  @protected
  AppleVideoCompressor
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppleVideoCompressor(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AppleVideoCompressorImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  GenericImageCompressor
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGenericImageCompressor(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return GenericImageCompressorImpl.frbInternalDcoDecode(
      raw as List<dynamic>,
    );
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  ImageCompressor dco_decode_TraitDef_ImageCompressor(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  VideoCompressor dco_decode_TraitDef_VideoCompressor(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  ImageOptions dco_decode_box_autoadd_image_options(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_image_options(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_box_autoadd_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  VideoOptions dco_decode_box_autoadd_video_options(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_video_options(raw);
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  ImageFormat dco_decode_image_format(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ImageFormat.values[raw as int];
  }

  @protected
  ImageOptions dco_decode_image_options(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ImageOptions(
      format: dco_decode_image_format(arr[0]),
      quality: dco_decode_u_8(arr[1]),
      maxDimension: dco_decode_opt_box_autoadd_u_32(arr[2]),
      speed: dco_decode_opt_box_autoadd_u_8(arr[3]),
    );
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  MediaError dco_decode_media_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return MediaError_UnsupportedFormat(dco_decode_String(raw[1]));
      case 1:
        return MediaError_Decode(dco_decode_String(raw[1]));
      case 2:
        return MediaError_Encode(dco_decode_String(raw[1]));
      case 3:
        return MediaError_HardwareUnavailable(dco_decode_String(raw[1]));
      case 4:
        return MediaError_Mux(dco_decode_String(raw[1]));
      case 5:
        return MediaError_Io(dco_decode_String(raw[1]));
      case 6:
        return MediaError_Native(
          code: dco_decode_i_64(raw[1]),
          msg: dco_decode_String(raw[2]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_8(raw);
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  VideoCodec dco_decode_video_codec(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return VideoCodec.values[raw as int];
  }

  @protected
  VideoOptions dco_decode_video_options(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return VideoOptions(
      codec: dco_decode_video_codec(arr[0]),
      bitrate: dco_decode_u_32(arr[1]),
      fps: dco_decode_opt_box_autoadd_u_32(arr[2]),
      maxDimension: dco_decode_opt_box_autoadd_u_32(arr[3]),
      keyframeInterval: dco_decode_opt_box_autoadd_u_32(arr[4]),
    );
  }

  @protected
  VideoResult dco_decode_video_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return VideoResult(
      outputPath: dco_decode_String(arr[0]),
      sizeBytes: dco_decode_u_64(arr[1]),
      backend: dco_decode_String(arr[2]),
      width: dco_decode_u_32(arr[3]),
      height: dco_decode_u_32(arr[4]),
    );
  }

  @protected
  AppleVideoCompressor
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppleVideoCompressor(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return AppleVideoCompressorImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  GenericImageCompressor
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGenericImageCompressor(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return GenericImageCompressorImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  AppleVideoCompressor
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppleVideoCompressor(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return AppleVideoCompressorImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  GenericImageCompressor
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGenericImageCompressor(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return GenericImageCompressorImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  ImageOptions sse_decode_box_autoadd_image_options(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_image_options(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_8(deserializer));
  }

  @protected
  VideoOptions sse_decode_box_autoadd_video_options(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_video_options(deserializer));
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  ImageFormat sse_decode_image_format(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ImageFormat.values[inner];
  }

  @protected
  ImageOptions sse_decode_image_options(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_format = sse_decode_image_format(deserializer);
    var var_quality = sse_decode_u_8(deserializer);
    var var_maxDimension = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_speed = sse_decode_opt_box_autoadd_u_8(deserializer);
    return ImageOptions(
      format: var_format,
      quality: var_quality,
      maxDimension: var_maxDimension,
      speed: var_speed,
    );
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  MediaError sse_decode_media_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_field0 = sse_decode_String(deserializer);
        return MediaError_UnsupportedFormat(var_field0);
      case 1:
        var var_field0 = sse_decode_String(deserializer);
        return MediaError_Decode(var_field0);
      case 2:
        var var_field0 = sse_decode_String(deserializer);
        return MediaError_Encode(var_field0);
      case 3:
        var var_field0 = sse_decode_String(deserializer);
        return MediaError_HardwareUnavailable(var_field0);
      case 4:
        var var_field0 = sse_decode_String(deserializer);
        return MediaError_Mux(var_field0);
      case 5:
        var var_field0 = sse_decode_String(deserializer);
        return MediaError_Io(var_field0);
      case 6:
        var var_code = sse_decode_i_64(deserializer);
        var var_msg = sse_decode_String(deserializer);
        return MediaError_Native(code: var_code, msg: var_msg);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_8(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  VideoCodec sse_decode_video_codec(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return VideoCodec.values[inner];
  }

  @protected
  VideoOptions sse_decode_video_options(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_codec = sse_decode_video_codec(deserializer);
    var var_bitrate = sse_decode_u_32(deserializer);
    var var_fps = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_maxDimension = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_keyframeInterval = sse_decode_opt_box_autoadd_u_32(deserializer);
    return VideoOptions(
      codec: var_codec,
      bitrate: var_bitrate,
      fps: var_fps,
      maxDimension: var_maxDimension,
      keyframeInterval: var_keyframeInterval,
    );
  }

  @protected
  VideoResult sse_decode_video_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_outputPath = sse_decode_String(deserializer);
    var var_sizeBytes = sse_decode_u_64(deserializer);
    var var_backend = sse_decode_String(deserializer);
    var var_width = sse_decode_u_32(deserializer);
    var var_height = sse_decode_u_32(deserializer);
    return VideoResult(
      outputPath: var_outputPath,
      sizeBytes: var_sizeBytes,
      backend: var_backend,
      width: var_width,
      height: var_height,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppleVideoCompressor(
    AppleVideoCompressor self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as AppleVideoCompressorImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGenericImageCompressor(
    GenericImageCompressor self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as GenericImageCompressorImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppleVideoCompressor(
    AppleVideoCompressor self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as AppleVideoCompressorImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGenericImageCompressor(
    GenericImageCompressor self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as GenericImageCompressorImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_box_autoadd_image_options(
    ImageOptions self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_image_options(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_8(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_video_options(
    VideoOptions self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_video_options(self, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_image_format(ImageFormat self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_image_options(ImageOptions self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_image_format(self.format, serializer);
    sse_encode_u_8(self.quality, serializer);
    sse_encode_opt_box_autoadd_u_32(self.maxDimension, serializer);
    sse_encode_opt_box_autoadd_u_8(self.speed, serializer);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_media_error(MediaError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case MediaError_UnsupportedFormat(field0: final field0):
        sse_encode_i_32(0, serializer);
        sse_encode_String(field0, serializer);
      case MediaError_Decode(field0: final field0):
        sse_encode_i_32(1, serializer);
        sse_encode_String(field0, serializer);
      case MediaError_Encode(field0: final field0):
        sse_encode_i_32(2, serializer);
        sse_encode_String(field0, serializer);
      case MediaError_HardwareUnavailable(field0: final field0):
        sse_encode_i_32(3, serializer);
        sse_encode_String(field0, serializer);
      case MediaError_Mux(field0: final field0):
        sse_encode_i_32(4, serializer);
        sse_encode_String(field0, serializer);
      case MediaError_Io(field0: final field0):
        sse_encode_i_32(5, serializer);
        sse_encode_String(field0, serializer);
      case MediaError_Native(code: final code, msg: final msg):
        sse_encode_i_32(6, serializer);
        sse_encode_i_64(code, serializer);
        sse_encode_String(msg, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_8(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_8(self, serializer);
    }
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_video_codec(VideoCodec self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_video_options(VideoOptions self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_video_codec(self.codec, serializer);
    sse_encode_u_32(self.bitrate, serializer);
    sse_encode_opt_box_autoadd_u_32(self.fps, serializer);
    sse_encode_opt_box_autoadd_u_32(self.maxDimension, serializer);
    sse_encode_opt_box_autoadd_u_32(self.keyframeInterval, serializer);
  }

  @protected
  void sse_encode_video_result(VideoResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.outputPath, serializer);
    sse_encode_u_64(self.sizeBytes, serializer);
    sse_encode_String(self.backend, serializer);
    sse_encode_u_32(self.width, serializer);
    sse_encode_u_32(self.height, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}

@sealed
class AppleVideoCompressorImpl extends RustOpaque
    implements AppleVideoCompressor {
  // Not to be used by end users
  AppleVideoCompressorImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  AppleVideoCompressorImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount: RustLib
        .instance
        .api
        .rust_arc_increment_strong_count_AppleVideoCompressor,
    rustArcDecrementStrongCount: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_AppleVideoCompressor,
    rustArcDecrementStrongCountPtr: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_AppleVideoCompressorPtr,
  );
}

@sealed
class GenericImageCompressorImpl extends RustOpaque
    implements GenericImageCompressor {
  // Not to be used by end users
  GenericImageCompressorImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  GenericImageCompressorImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount: RustLib
        .instance
        .api
        .rust_arc_increment_strong_count_GenericImageCompressor,
    rustArcDecrementStrongCount: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_GenericImageCompressor,
    rustArcDecrementStrongCountPtr: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_GenericImageCompressorPtr,
  );
}
