// Generated file. Do not edit.
// Autogenerated from Pigeon (v27.3.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


/// 输入位置：0 = 内存字节，1 = 路径 / URI。
///
/// Source kind: 0 = in-memory bytes, 1 = filesystem path / URI.
class SourceMsg {
  SourceMsg({
    required this.kind,
    this.bytes,
    this.path,
  });

  int kind;

  Uint8List? bytes;

  String? path;

  List<Object?> _toList() {
    return <Object?>[
      kind,
      bytes,
      path,
    ];
  }

  Object encode() {
    return _toList();  }

  static SourceMsg decode(Object result) {
    result as List<Object?>;
    return SourceMsg(
      kind: result[0]! as int,
      bytes: result[1] as Uint8List?,
      path: result[2] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! SourceMsg || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(kind, other.kind) && _deepEquals(bytes, other.bytes) && _deepEquals(path, other.path);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'SourceMsg(kind: $kind, bytes: $bytes, path: $path)';
  }
}

/// 输出位置：0 = 内存字节，1 = 文件路径。
///
/// Destination kind: 0 = in-memory bytes, 1 = filesystem path.
class DestinationMsg {
  DestinationMsg({
    required this.kind,
    this.path,
  });

  int kind;

  String? path;

  List<Object?> _toList() {
    return <Object?>[
      kind,
      path,
    ];
  }

  Object encode() {
    return _toList();  }

  static DestinationMsg decode(Object result) {
    result as List<Object?>;
    return DestinationMsg(
      kind: result[0]! as int,
      path: result[1] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! DestinationMsg || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(kind, other.kind) && _deepEquals(path, other.path);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'DestinationMsg(kind: $kind, path: $path)';
  }
}

class ImageOptionsMsg {
  ImageOptionsMsg({
    required this.format,
    required this.quality,
    this.maxDimension,
    required this.keepMetadata,
  });

  String format;

  int quality;

  int? maxDimension;

  bool keepMetadata;

  List<Object?> _toList() {
    return <Object?>[
      format,
      quality,
      maxDimension,
      keepMetadata,
    ];
  }

  Object encode() {
    return _toList();  }

  static ImageOptionsMsg decode(Object result) {
    result as List<Object?>;
    return ImageOptionsMsg(
      format: result[0]! as String,
      quality: result[1]! as int,
      maxDimension: result[2] as int?,
      keepMetadata: result[3]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ImageOptionsMsg || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(format, other.format) && _deepEquals(quality, other.quality) && _deepEquals(maxDimension, other.maxDimension) && _deepEquals(keepMetadata, other.keepMetadata);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ImageOptionsMsg(format: $format, quality: $quality, maxDimension: $maxDimension, keepMetadata: $keepMetadata)';
  }
}

class VideoOptionsMsg {
  VideoOptionsMsg({
    required this.codec,
    required this.bitrate,
    this.fps,
    this.maxDimension,
    this.keyframeInterval,
    required this.keepAudio,
  });

  String codec;

  int bitrate;

  int? fps;

  int? maxDimension;

  int? keyframeInterval;

  bool keepAudio;

  List<Object?> _toList() {
    return <Object?>[
      codec,
      bitrate,
      fps,
      maxDimension,
      keyframeInterval,
      keepAudio,
    ];
  }

  Object encode() {
    return _toList();  }

  static VideoOptionsMsg decode(Object result) {
    result as List<Object?>;
    return VideoOptionsMsg(
      codec: result[0]! as String,
      bitrate: result[1]! as int,
      fps: result[2] as int?,
      maxDimension: result[3] as int?,
      keyframeInterval: result[4] as int?,
      keepAudio: result[5]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! VideoOptionsMsg || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(codec, other.codec) && _deepEquals(bitrate, other.bitrate) && _deepEquals(fps, other.fps) && _deepEquals(maxDimension, other.maxDimension) && _deepEquals(keyframeInterval, other.keyframeInterval) && _deepEquals(keepAudio, other.keepAudio);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'VideoOptionsMsg(codec: $codec, bitrate: $bitrate, fps: $fps, maxDimension: $maxDimension, keyframeInterval: $keyframeInterval, keepAudio: $keepAudio)';
  }
}

class ImageCapabilitiesMsg {
  ImageCapabilitiesMsg({
    required this.inputFormats,
    required this.outputFormats,
  });

  List<String> inputFormats;

  List<String> outputFormats;

  List<Object?> _toList() {
    return <Object?>[
      inputFormats,
      outputFormats,
    ];
  }

  Object encode() {
    return _toList();  }

  static ImageCapabilitiesMsg decode(Object result) {
    result as List<Object?>;
    return ImageCapabilitiesMsg(
      inputFormats: (result[0]! as List<Object?>).cast<String>(),
      outputFormats: (result[1]! as List<Object?>).cast<String>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ImageCapabilitiesMsg || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(inputFormats, other.inputFormats) && _deepEquals(outputFormats, other.outputFormats);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ImageCapabilitiesMsg(inputFormats: $inputFormats, outputFormats: $outputFormats)';
  }
}

class VideoCapabilitiesMsg {
  VideoCapabilitiesMsg({
    this.encoderName,
    required this.codecs,
    required this.acceptsContentUri,
  });

  String? encoderName;

  List<String> codecs;

  bool acceptsContentUri;

  List<Object?> _toList() {
    return <Object?>[
      encoderName,
      codecs,
      acceptsContentUri,
    ];
  }

  Object encode() {
    return _toList();  }

  static VideoCapabilitiesMsg decode(Object result) {
    result as List<Object?>;
    return VideoCapabilitiesMsg(
      encoderName: result[0] as String?,
      codecs: (result[1]! as List<Object?>).cast<String>(),
      acceptsContentUri: result[2]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! VideoCapabilitiesMsg || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encoderName, other.encoderName) && _deepEquals(codecs, other.codecs) && _deepEquals(acceptsContentUri, other.acceptsContentUri);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'VideoCapabilitiesMsg(encoderName: $encoderName, codecs: $codecs, acceptsContentUri: $acceptsContentUri)';
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is SourceMsg) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    }    else if (value is DestinationMsg) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is ImageOptionsMsg) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is VideoOptionsMsg) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is ImageCapabilitiesMsg) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is VideoCapabilitiesMsg) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return SourceMsg.decode(readValue(buffer)!);
      case 130:
        return DestinationMsg.decode(readValue(buffer)!);
      case 131:
        return ImageOptionsMsg.decode(readValue(buffer)!);
      case 132:
        return VideoOptionsMsg.decode(readValue(buffer)!);
      case 133:
        return ImageCapabilitiesMsg.decode(readValue(buffer)!);
      case 134:
        return VideoCapabilitiesMsg.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class MediaCompressionHostApi {
  /// Constructor for [MediaCompressionHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  MediaCompressionHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<int> createJob() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.xue_hua_media_compression_platform_interface.MediaCompressionHostApi.createJob$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as int;
  }

  Future<ImageCapabilitiesMsg> queryImageCapabilities() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.xue_hua_media_compression_platform_interface.MediaCompressionHostApi.queryImageCapabilities$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as ImageCapabilitiesMsg;
  }

  Future<void> startImageCompress(int id, SourceMsg source, DestinationMsg destination, ImageOptionsMsg options) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.xue_hua_media_compression_platform_interface.MediaCompressionHostApi.startImageCompress$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[id, source, destination, options]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<VideoCapabilitiesMsg> queryVideoCapabilities() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.xue_hua_media_compression_platform_interface.MediaCompressionHostApi.queryVideoCapabilities$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as VideoCapabilitiesMsg;
  }

  Future<void> startVideoCompress(int id, String inputPath, String outputPath, VideoOptionsMsg options) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.xue_hua_media_compression_platform_interface.MediaCompressionHostApi.startVideoCompress$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[id, inputPath, outputPath, options]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> cancelJob(int id) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.xue_hua_media_compression_platform_interface.MediaCompressionHostApi.cancelJob$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[id]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> disposeJob(int id) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.xue_hua_media_compression_platform_interface.MediaCompressionHostApi.disposeJob$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[id]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }
}
