// Generated file. Do not edit.
// Autogenerated from Pigeon (v27.3.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum MessagesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// 输入位置：0 = 内存字节，1 = 路径 / URI。
///
/// Source kind: 0 = in-memory bytes, 1 = filesystem path / URI.
///
/// Generated class from Pigeon that represents data sent in messages.
struct SourceMsg: Hashable, CustomStringConvertible {
  var kind: Int64
  var bytes: FlutterStandardTypedData? = nil
  var path: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SourceMsg? {
    let kind = pigeonVar_list[0] as! Int64
    let bytes: FlutterStandardTypedData? = nilOrValue(pigeonVar_list[1])
    let path: String? = nilOrValue(pigeonVar_list[2])

    return SourceMsg(
      kind: kind,
      bytes: bytes,
      path: path
    )
  }
  func toList() -> [Any?] {
    return [
      kind,
      bytes,
      path,
    ]
  }
  static func == (lhs: SourceMsg, rhs: SourceMsg) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.kind, rhs.kind) && MessagesPigeonInternal.deepEquals(lhs.bytes, rhs.bytes) && MessagesPigeonInternal.deepEquals(lhs.path, rhs.path)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("SourceMsg")
    MessagesPigeonInternal.deepHash(value: kind, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: bytes, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: path, hasher: &hasher)
  }

  public var description: String {
    return "SourceMsg(kind: \(String(describing: kind)), bytes: \(String(describing: bytes)), path: \(String(describing: path)))"
  }
}

/// 输出位置：0 = 内存字节，1 = 文件路径。
///
/// Destination kind: 0 = in-memory bytes, 1 = filesystem path.
///
/// Generated class from Pigeon that represents data sent in messages.
struct DestinationMsg: Hashable, CustomStringConvertible {
  var kind: Int64
  var path: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> DestinationMsg? {
    let kind = pigeonVar_list[0] as! Int64
    let path: String? = nilOrValue(pigeonVar_list[1])

    return DestinationMsg(
      kind: kind,
      path: path
    )
  }
  func toList() -> [Any?] {
    return [
      kind,
      path,
    ]
  }
  static func == (lhs: DestinationMsg, rhs: DestinationMsg) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.kind, rhs.kind) && MessagesPigeonInternal.deepEquals(lhs.path, rhs.path)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("DestinationMsg")
    MessagesPigeonInternal.deepHash(value: kind, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: path, hasher: &hasher)
  }

  public var description: String {
    return "DestinationMsg(kind: \(String(describing: kind)), path: \(String(describing: path)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ImageOptionsMsg: Hashable, CustomStringConvertible {
  var format: String
  var quality: Int64
  var maxDimension: Int64? = nil
  var keepMetadata: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ImageOptionsMsg? {
    let format = pigeonVar_list[0] as! String
    let quality = pigeonVar_list[1] as! Int64
    let maxDimension: Int64? = nilOrValue(pigeonVar_list[2])
    let keepMetadata = pigeonVar_list[3] as! Bool

    return ImageOptionsMsg(
      format: format,
      quality: quality,
      maxDimension: maxDimension,
      keepMetadata: keepMetadata
    )
  }
  func toList() -> [Any?] {
    return [
      format,
      quality,
      maxDimension,
      keepMetadata,
    ]
  }
  static func == (lhs: ImageOptionsMsg, rhs: ImageOptionsMsg) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.format, rhs.format) && MessagesPigeonInternal.deepEquals(lhs.quality, rhs.quality) && MessagesPigeonInternal.deepEquals(lhs.maxDimension, rhs.maxDimension) && MessagesPigeonInternal.deepEquals(lhs.keepMetadata, rhs.keepMetadata)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ImageOptionsMsg")
    MessagesPigeonInternal.deepHash(value: format, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: quality, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: maxDimension, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: keepMetadata, hasher: &hasher)
  }

  public var description: String {
    return "ImageOptionsMsg(format: \(String(describing: format)), quality: \(String(describing: quality)), maxDimension: \(String(describing: maxDimension)), keepMetadata: \(String(describing: keepMetadata)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct VideoOptionsMsg: Hashable, CustomStringConvertible {
  var codec: String
  var bitrate: Int64
  var fps: Int64? = nil
  var maxDimension: Int64? = nil
  var keyframeInterval: Int64? = nil
  var keepAudio: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> VideoOptionsMsg? {
    let codec = pigeonVar_list[0] as! String
    let bitrate = pigeonVar_list[1] as! Int64
    let fps: Int64? = nilOrValue(pigeonVar_list[2])
    let maxDimension: Int64? = nilOrValue(pigeonVar_list[3])
    let keyframeInterval: Int64? = nilOrValue(pigeonVar_list[4])
    let keepAudio = pigeonVar_list[5] as! Bool

    return VideoOptionsMsg(
      codec: codec,
      bitrate: bitrate,
      fps: fps,
      maxDimension: maxDimension,
      keyframeInterval: keyframeInterval,
      keepAudio: keepAudio
    )
  }
  func toList() -> [Any?] {
    return [
      codec,
      bitrate,
      fps,
      maxDimension,
      keyframeInterval,
      keepAudio,
    ]
  }
  static func == (lhs: VideoOptionsMsg, rhs: VideoOptionsMsg) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.codec, rhs.codec) && MessagesPigeonInternal.deepEquals(lhs.bitrate, rhs.bitrate) && MessagesPigeonInternal.deepEquals(lhs.fps, rhs.fps) && MessagesPigeonInternal.deepEquals(lhs.maxDimension, rhs.maxDimension) && MessagesPigeonInternal.deepEquals(lhs.keyframeInterval, rhs.keyframeInterval) && MessagesPigeonInternal.deepEquals(lhs.keepAudio, rhs.keepAudio)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("VideoOptionsMsg")
    MessagesPigeonInternal.deepHash(value: codec, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: bitrate, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: fps, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: maxDimension, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: keyframeInterval, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: keepAudio, hasher: &hasher)
  }

  public var description: String {
    return "VideoOptionsMsg(codec: \(String(describing: codec)), bitrate: \(String(describing: bitrate)), fps: \(String(describing: fps)), maxDimension: \(String(describing: maxDimension)), keyframeInterval: \(String(describing: keyframeInterval)), keepAudio: \(String(describing: keepAudio)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ImageCapabilitiesMsg: Hashable, CustomStringConvertible {
  var inputFormats: [String]
  var outputFormats: [String]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ImageCapabilitiesMsg? {
    let inputFormats = pigeonVar_list[0] as! [String]
    let outputFormats = pigeonVar_list[1] as! [String]

    return ImageCapabilitiesMsg(
      inputFormats: inputFormats,
      outputFormats: outputFormats
    )
  }
  func toList() -> [Any?] {
    return [
      inputFormats,
      outputFormats,
    ]
  }
  static func == (lhs: ImageCapabilitiesMsg, rhs: ImageCapabilitiesMsg) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.inputFormats, rhs.inputFormats) && MessagesPigeonInternal.deepEquals(lhs.outputFormats, rhs.outputFormats)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ImageCapabilitiesMsg")
    MessagesPigeonInternal.deepHash(value: inputFormats, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: outputFormats, hasher: &hasher)
  }

  public var description: String {
    return "ImageCapabilitiesMsg(inputFormats: \(String(describing: inputFormats)), outputFormats: \(String(describing: outputFormats)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct VideoCapabilitiesMsg: Hashable, CustomStringConvertible {
  var encoderName: String? = nil
  var codecs: [String]
  var acceptsContentUri: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> VideoCapabilitiesMsg? {
    let encoderName: String? = nilOrValue(pigeonVar_list[0])
    let codecs = pigeonVar_list[1] as! [String]
    let acceptsContentUri = pigeonVar_list[2] as! Bool

    return VideoCapabilitiesMsg(
      encoderName: encoderName,
      codecs: codecs,
      acceptsContentUri: acceptsContentUri
    )
  }
  func toList() -> [Any?] {
    return [
      encoderName,
      codecs,
      acceptsContentUri,
    ]
  }
  static func == (lhs: VideoCapabilitiesMsg, rhs: VideoCapabilitiesMsg) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.encoderName, rhs.encoderName) && MessagesPigeonInternal.deepEquals(lhs.codecs, rhs.codecs) && MessagesPigeonInternal.deepEquals(lhs.acceptsContentUri, rhs.acceptsContentUri)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("VideoCapabilitiesMsg")
    MessagesPigeonInternal.deepHash(value: encoderName, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: codecs, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: acceptsContentUri, hasher: &hasher)
  }

  public var description: String {
    return "VideoCapabilitiesMsg(encoderName: \(String(describing: encoderName)), codecs: \(String(describing: codecs)), acceptsContentUri: \(String(describing: acceptsContentUri)))"
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return SourceMsg.fromList(self.readValue() as! [Any?])
    case 130:
      return DestinationMsg.fromList(self.readValue() as! [Any?])
    case 131:
      return ImageOptionsMsg.fromList(self.readValue() as! [Any?])
    case 132:
      return VideoOptionsMsg.fromList(self.readValue() as! [Any?])
    case 133:
      return ImageCapabilitiesMsg.fromList(self.readValue() as! [Any?])
    case 134:
      return VideoCapabilitiesMsg.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? SourceMsg {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? DestinationMsg {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? ImageOptionsMsg {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? VideoOptionsMsg {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? ImageCapabilitiesMsg {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? VideoCapabilitiesMsg {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol MediaCompressionHostApi {
  func createJob() throws -> Int64
  func queryImageCapabilities() throws -> ImageCapabilitiesMsg
  func startImageCompress(id: Int64, source: SourceMsg, destination: DestinationMsg, options: ImageOptionsMsg, completion: @escaping (Result<Void, Error>) -> Void)
  func queryVideoCapabilities() throws -> VideoCapabilitiesMsg
  func startVideoCompress(id: Int64, inputPath: String, outputPath: String, options: VideoOptionsMsg, completion: @escaping (Result<Void, Error>) -> Void)
  func cancelJob(id: Int64) throws
  func disposeJob(id: Int64) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class MediaCompressionHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `MediaCompressionHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: MediaCompressionHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let createJobChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.xue_hua_media_compression_platform_interface.MediaCompressionHostApi.createJob\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createJobChannel.setMessageHandler { _, reply in
        do {
          let result = try api.createJob()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      createJobChannel.setMessageHandler(nil)
    }
    let queryImageCapabilitiesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.xue_hua_media_compression_platform_interface.MediaCompressionHostApi.queryImageCapabilities\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      queryImageCapabilitiesChannel.setMessageHandler { _, reply in
        do {
          let result = try api.queryImageCapabilities()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      queryImageCapabilitiesChannel.setMessageHandler(nil)
    }
    let startImageCompressChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.xue_hua_media_compression_platform_interface.MediaCompressionHostApi.startImageCompress\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startImageCompressChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let idArg = args[0] as! Int64
        let sourceArg = args[1] as! SourceMsg
        let destinationArg = args[2] as! DestinationMsg
        let optionsArg = args[3] as! ImageOptionsMsg
        api.startImageCompress(id: idArg, source: sourceArg, destination: destinationArg, options: optionsArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startImageCompressChannel.setMessageHandler(nil)
    }
    let queryVideoCapabilitiesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.xue_hua_media_compression_platform_interface.MediaCompressionHostApi.queryVideoCapabilities\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      queryVideoCapabilitiesChannel.setMessageHandler { _, reply in
        do {
          let result = try api.queryVideoCapabilities()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      queryVideoCapabilitiesChannel.setMessageHandler(nil)
    }
    let startVideoCompressChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.xue_hua_media_compression_platform_interface.MediaCompressionHostApi.startVideoCompress\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startVideoCompressChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let idArg = args[0] as! Int64
        let inputPathArg = args[1] as! String
        let outputPathArg = args[2] as! String
        let optionsArg = args[3] as! VideoOptionsMsg
        api.startVideoCompress(id: idArg, inputPath: inputPathArg, outputPath: outputPathArg, options: optionsArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startVideoCompressChannel.setMessageHandler(nil)
    }
    let cancelJobChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.xue_hua_media_compression_platform_interface.MediaCompressionHostApi.cancelJob\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cancelJobChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let idArg = args[0] as! Int64
        do {
          try api.cancelJob(id: idArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      cancelJobChannel.setMessageHandler(nil)
    }
    let disposeJobChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.xue_hua_media_compression_platform_interface.MediaCompressionHostApi.disposeJob\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disposeJobChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let idArg = args[0] as! Int64
        do {
          try api.disposeJob(id: idArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      disposeJobChannel.setMessageHandler(nil)
    }
  }
}
