// Generated file. Do not edit.
// Autogenerated from Pigeon (v27.3.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_MESSAGES_G_H_
#define PIGEON_MESSAGES_G_H_

#include <flutter_linux/flutter_linux.h>

G_BEGIN_DECLS

/**
 * XhMcSourceMsg:
 *
 * 输入位置：0 = 内存字节，1 = 路径 / URI。
 *
 * Source kind: 0 = in-memory bytes, 1 = filesystem path / URI.
 */

G_DECLARE_FINAL_TYPE(XhMcSourceMsg, xh_mc_source_msg, XH_MC, SOURCE_MSG, GObject)

/**
 * xh_mc_source_msg_new:
 * kind: field in this object.
 * bytes: field in this object.
 * bytes_length: length of @bytes.
 * path: field in this object.
 *
 * Creates a new #SourceMsg object.
 *
 * Returns: a new #XhMcSourceMsg
 */
XhMcSourceMsg* xh_mc_source_msg_new(int64_t kind, const uint8_t* bytes, size_t bytes_length, const gchar* path);

/**
 * xh_mc_source_msg_get_kind
 * @object: a #XhMcSourceMsg.
 *
 * Gets the value of the kind field of @object.
 *
 * Returns: the field value.
 */
int64_t xh_mc_source_msg_get_kind(XhMcSourceMsg* object);

/**
 * xh_mc_source_msg_get_bytes
 * @object: a #XhMcSourceMsg.
 * @length: location to write the length of this value.
 *
 * Gets the value of the bytes field of @object.
 *
 * Returns: the field value.
 */
const uint8_t* xh_mc_source_msg_get_bytes(XhMcSourceMsg* object, size_t* length);

/**
 * xh_mc_source_msg_get_path
 * @object: a #XhMcSourceMsg.
 *
 * Gets the value of the path field of @object.
 *
 * Returns: the field value.
 */
const gchar* xh_mc_source_msg_get_path(XhMcSourceMsg* object);

/**
 * xh_mc_source_msg_equals:
 * @a: a #XhMcSourceMsg.
 * @b: another #XhMcSourceMsg.
 *
 * Checks if two #XhMcSourceMsg objects are equal.
 *
 * Returns: TRUE if @a and @b are equal.
 */
gboolean xh_mc_source_msg_equals(XhMcSourceMsg* a, XhMcSourceMsg* b);

/**
 * xh_mc_source_msg_hash:
 * @object: a #XhMcSourceMsg.
 *
 * Calculates a hash code for a #XhMcSourceMsg object.
 *
 * Returns: the hash code.
 */
guint xh_mc_source_msg_hash(XhMcSourceMsg* object);

/**
 * xh_mc_source_msg_to_string:
 * @object: a #XhMcSourceMsg.
 *
 * Returns a string representation of a #XhMcSourceMsg object.
 *
 * Returns: (transfer full): a new string, free with g_free().
 */
gchar* xh_mc_source_msg_to_string(XhMcSourceMsg* object);

/**
 * XhMcDestinationMsg:
 *
 * 输出位置：0 = 内存字节，1 = 文件路径。
 *
 * Destination kind: 0 = in-memory bytes, 1 = filesystem path.
 */

G_DECLARE_FINAL_TYPE(XhMcDestinationMsg, xh_mc_destination_msg, XH_MC, DESTINATION_MSG, GObject)

/**
 * xh_mc_destination_msg_new:
 * kind: field in this object.
 * path: field in this object.
 *
 * Creates a new #DestinationMsg object.
 *
 * Returns: a new #XhMcDestinationMsg
 */
XhMcDestinationMsg* xh_mc_destination_msg_new(int64_t kind, const gchar* path);

/**
 * xh_mc_destination_msg_get_kind
 * @object: a #XhMcDestinationMsg.
 *
 * Gets the value of the kind field of @object.
 *
 * Returns: the field value.
 */
int64_t xh_mc_destination_msg_get_kind(XhMcDestinationMsg* object);

/**
 * xh_mc_destination_msg_get_path
 * @object: a #XhMcDestinationMsg.
 *
 * Gets the value of the path field of @object.
 *
 * Returns: the field value.
 */
const gchar* xh_mc_destination_msg_get_path(XhMcDestinationMsg* object);

/**
 * xh_mc_destination_msg_equals:
 * @a: a #XhMcDestinationMsg.
 * @b: another #XhMcDestinationMsg.
 *
 * Checks if two #XhMcDestinationMsg objects are equal.
 *
 * Returns: TRUE if @a and @b are equal.
 */
gboolean xh_mc_destination_msg_equals(XhMcDestinationMsg* a, XhMcDestinationMsg* b);

/**
 * xh_mc_destination_msg_hash:
 * @object: a #XhMcDestinationMsg.
 *
 * Calculates a hash code for a #XhMcDestinationMsg object.
 *
 * Returns: the hash code.
 */
guint xh_mc_destination_msg_hash(XhMcDestinationMsg* object);

/**
 * xh_mc_destination_msg_to_string:
 * @object: a #XhMcDestinationMsg.
 *
 * Returns a string representation of a #XhMcDestinationMsg object.
 *
 * Returns: (transfer full): a new string, free with g_free().
 */
gchar* xh_mc_destination_msg_to_string(XhMcDestinationMsg* object);

/**
 * XhMcImageOptionsMsg:
 *
 */

G_DECLARE_FINAL_TYPE(XhMcImageOptionsMsg, xh_mc_image_options_msg, XH_MC, IMAGE_OPTIONS_MSG, GObject)

/**
 * xh_mc_image_options_msg_new:
 * format: field in this object.
 * quality: field in this object.
 * max_dimension: field in this object.
 *
 * Creates a new #ImageOptionsMsg object.
 *
 * Returns: a new #XhMcImageOptionsMsg
 */
XhMcImageOptionsMsg* xh_mc_image_options_msg_new(const gchar* format, int64_t quality, int64_t* max_dimension);

/**
 * xh_mc_image_options_msg_get_format
 * @object: a #XhMcImageOptionsMsg.
 *
 * Gets the value of the format field of @object.
 *
 * Returns: the field value.
 */
const gchar* xh_mc_image_options_msg_get_format(XhMcImageOptionsMsg* object);

/**
 * xh_mc_image_options_msg_get_quality
 * @object: a #XhMcImageOptionsMsg.
 *
 * Gets the value of the quality field of @object.
 *
 * Returns: the field value.
 */
int64_t xh_mc_image_options_msg_get_quality(XhMcImageOptionsMsg* object);

/**
 * xh_mc_image_options_msg_get_max_dimension
 * @object: a #XhMcImageOptionsMsg.
 *
 * Gets the value of the maxDimension field of @object.
 *
 * Returns: the field value.
 */
int64_t* xh_mc_image_options_msg_get_max_dimension(XhMcImageOptionsMsg* object);

/**
 * xh_mc_image_options_msg_equals:
 * @a: a #XhMcImageOptionsMsg.
 * @b: another #XhMcImageOptionsMsg.
 *
 * Checks if two #XhMcImageOptionsMsg objects are equal.
 *
 * Returns: TRUE if @a and @b are equal.
 */
gboolean xh_mc_image_options_msg_equals(XhMcImageOptionsMsg* a, XhMcImageOptionsMsg* b);

/**
 * xh_mc_image_options_msg_hash:
 * @object: a #XhMcImageOptionsMsg.
 *
 * Calculates a hash code for a #XhMcImageOptionsMsg object.
 *
 * Returns: the hash code.
 */
guint xh_mc_image_options_msg_hash(XhMcImageOptionsMsg* object);

/**
 * xh_mc_image_options_msg_to_string:
 * @object: a #XhMcImageOptionsMsg.
 *
 * Returns a string representation of a #XhMcImageOptionsMsg object.
 *
 * Returns: (transfer full): a new string, free with g_free().
 */
gchar* xh_mc_image_options_msg_to_string(XhMcImageOptionsMsg* object);

/**
 * XhMcVideoOptionsMsg:
 *
 */

G_DECLARE_FINAL_TYPE(XhMcVideoOptionsMsg, xh_mc_video_options_msg, XH_MC, VIDEO_OPTIONS_MSG, GObject)

/**
 * xh_mc_video_options_msg_new:
 * codec: field in this object.
 * bitrate: field in this object.
 * fps: field in this object.
 * max_dimension: field in this object.
 * keyframe_interval: field in this object.
 *
 * Creates a new #VideoOptionsMsg object.
 *
 * Returns: a new #XhMcVideoOptionsMsg
 */
XhMcVideoOptionsMsg* xh_mc_video_options_msg_new(const gchar* codec, int64_t bitrate, int64_t* fps, int64_t* max_dimension, int64_t* keyframe_interval);

/**
 * xh_mc_video_options_msg_get_codec
 * @object: a #XhMcVideoOptionsMsg.
 *
 * Gets the value of the codec field of @object.
 *
 * Returns: the field value.
 */
const gchar* xh_mc_video_options_msg_get_codec(XhMcVideoOptionsMsg* object);

/**
 * xh_mc_video_options_msg_get_bitrate
 * @object: a #XhMcVideoOptionsMsg.
 *
 * Gets the value of the bitrate field of @object.
 *
 * Returns: the field value.
 */
int64_t xh_mc_video_options_msg_get_bitrate(XhMcVideoOptionsMsg* object);

/**
 * xh_mc_video_options_msg_get_fps
 * @object: a #XhMcVideoOptionsMsg.
 *
 * Gets the value of the fps field of @object.
 *
 * Returns: the field value.
 */
int64_t* xh_mc_video_options_msg_get_fps(XhMcVideoOptionsMsg* object);

/**
 * xh_mc_video_options_msg_get_max_dimension
 * @object: a #XhMcVideoOptionsMsg.
 *
 * Gets the value of the maxDimension field of @object.
 *
 * Returns: the field value.
 */
int64_t* xh_mc_video_options_msg_get_max_dimension(XhMcVideoOptionsMsg* object);

/**
 * xh_mc_video_options_msg_get_keyframe_interval
 * @object: a #XhMcVideoOptionsMsg.
 *
 * Gets the value of the keyframeInterval field of @object.
 *
 * Returns: the field value.
 */
int64_t* xh_mc_video_options_msg_get_keyframe_interval(XhMcVideoOptionsMsg* object);

/**
 * xh_mc_video_options_msg_equals:
 * @a: a #XhMcVideoOptionsMsg.
 * @b: another #XhMcVideoOptionsMsg.
 *
 * Checks if two #XhMcVideoOptionsMsg objects are equal.
 *
 * Returns: TRUE if @a and @b are equal.
 */
gboolean xh_mc_video_options_msg_equals(XhMcVideoOptionsMsg* a, XhMcVideoOptionsMsg* b);

/**
 * xh_mc_video_options_msg_hash:
 * @object: a #XhMcVideoOptionsMsg.
 *
 * Calculates a hash code for a #XhMcVideoOptionsMsg object.
 *
 * Returns: the hash code.
 */
guint xh_mc_video_options_msg_hash(XhMcVideoOptionsMsg* object);

/**
 * xh_mc_video_options_msg_to_string:
 * @object: a #XhMcVideoOptionsMsg.
 *
 * Returns a string representation of a #XhMcVideoOptionsMsg object.
 *
 * Returns: (transfer full): a new string, free with g_free().
 */
gchar* xh_mc_video_options_msg_to_string(XhMcVideoOptionsMsg* object);

/**
 * XhMcImageCapabilitiesMsg:
 *
 */

G_DECLARE_FINAL_TYPE(XhMcImageCapabilitiesMsg, xh_mc_image_capabilities_msg, XH_MC, IMAGE_CAPABILITIES_MSG, GObject)

/**
 * xh_mc_image_capabilities_msg_new:
 * input_formats: field in this object.
 * output_formats: field in this object.
 *
 * Creates a new #ImageCapabilitiesMsg object.
 *
 * Returns: a new #XhMcImageCapabilitiesMsg
 */
XhMcImageCapabilitiesMsg* xh_mc_image_capabilities_msg_new(FlValue* input_formats, FlValue* output_formats);

/**
 * xh_mc_image_capabilities_msg_get_input_formats
 * @object: a #XhMcImageCapabilitiesMsg.
 *
 * Gets the value of the inputFormats field of @object.
 *
 * Returns: the field value.
 */
FlValue* xh_mc_image_capabilities_msg_get_input_formats(XhMcImageCapabilitiesMsg* object);

/**
 * xh_mc_image_capabilities_msg_get_output_formats
 * @object: a #XhMcImageCapabilitiesMsg.
 *
 * Gets the value of the outputFormats field of @object.
 *
 * Returns: the field value.
 */
FlValue* xh_mc_image_capabilities_msg_get_output_formats(XhMcImageCapabilitiesMsg* object);

/**
 * xh_mc_image_capabilities_msg_equals:
 * @a: a #XhMcImageCapabilitiesMsg.
 * @b: another #XhMcImageCapabilitiesMsg.
 *
 * Checks if two #XhMcImageCapabilitiesMsg objects are equal.
 *
 * Returns: TRUE if @a and @b are equal.
 */
gboolean xh_mc_image_capabilities_msg_equals(XhMcImageCapabilitiesMsg* a, XhMcImageCapabilitiesMsg* b);

/**
 * xh_mc_image_capabilities_msg_hash:
 * @object: a #XhMcImageCapabilitiesMsg.
 *
 * Calculates a hash code for a #XhMcImageCapabilitiesMsg object.
 *
 * Returns: the hash code.
 */
guint xh_mc_image_capabilities_msg_hash(XhMcImageCapabilitiesMsg* object);

/**
 * xh_mc_image_capabilities_msg_to_string:
 * @object: a #XhMcImageCapabilitiesMsg.
 *
 * Returns a string representation of a #XhMcImageCapabilitiesMsg object.
 *
 * Returns: (transfer full): a new string, free with g_free().
 */
gchar* xh_mc_image_capabilities_msg_to_string(XhMcImageCapabilitiesMsg* object);

/**
 * XhMcVideoCapabilitiesMsg:
 *
 */

G_DECLARE_FINAL_TYPE(XhMcVideoCapabilitiesMsg, xh_mc_video_capabilities_msg, XH_MC, VIDEO_CAPABILITIES_MSG, GObject)

/**
 * xh_mc_video_capabilities_msg_new:
 * encoder_name: field in this object.
 * codecs: field in this object.
 * accepts_content_uri: field in this object.
 *
 * Creates a new #VideoCapabilitiesMsg object.
 *
 * Returns: a new #XhMcVideoCapabilitiesMsg
 */
XhMcVideoCapabilitiesMsg* xh_mc_video_capabilities_msg_new(const gchar* encoder_name, FlValue* codecs, gboolean accepts_content_uri);

/**
 * xh_mc_video_capabilities_msg_get_encoder_name
 * @object: a #XhMcVideoCapabilitiesMsg.
 *
 * Gets the value of the encoderName field of @object.
 *
 * Returns: the field value.
 */
const gchar* xh_mc_video_capabilities_msg_get_encoder_name(XhMcVideoCapabilitiesMsg* object);

/**
 * xh_mc_video_capabilities_msg_get_codecs
 * @object: a #XhMcVideoCapabilitiesMsg.
 *
 * Gets the value of the codecs field of @object.
 *
 * Returns: the field value.
 */
FlValue* xh_mc_video_capabilities_msg_get_codecs(XhMcVideoCapabilitiesMsg* object);

/**
 * xh_mc_video_capabilities_msg_get_accepts_content_uri
 * @object: a #XhMcVideoCapabilitiesMsg.
 *
 * Gets the value of the acceptsContentUri field of @object.
 *
 * Returns: the field value.
 */
gboolean xh_mc_video_capabilities_msg_get_accepts_content_uri(XhMcVideoCapabilitiesMsg* object);

/**
 * xh_mc_video_capabilities_msg_equals:
 * @a: a #XhMcVideoCapabilitiesMsg.
 * @b: another #XhMcVideoCapabilitiesMsg.
 *
 * Checks if two #XhMcVideoCapabilitiesMsg objects are equal.
 *
 * Returns: TRUE if @a and @b are equal.
 */
gboolean xh_mc_video_capabilities_msg_equals(XhMcVideoCapabilitiesMsg* a, XhMcVideoCapabilitiesMsg* b);

/**
 * xh_mc_video_capabilities_msg_hash:
 * @object: a #XhMcVideoCapabilitiesMsg.
 *
 * Calculates a hash code for a #XhMcVideoCapabilitiesMsg object.
 *
 * Returns: the hash code.
 */
guint xh_mc_video_capabilities_msg_hash(XhMcVideoCapabilitiesMsg* object);

/**
 * xh_mc_video_capabilities_msg_to_string:
 * @object: a #XhMcVideoCapabilitiesMsg.
 *
 * Returns a string representation of a #XhMcVideoCapabilitiesMsg object.
 *
 * Returns: (transfer full): a new string, free with g_free().
 */
gchar* xh_mc_video_capabilities_msg_to_string(XhMcVideoCapabilitiesMsg* object);

G_DECLARE_FINAL_TYPE(XhMcMessageCodec, xh_mc_message_codec, XH_MC, MESSAGE_CODEC, FlStandardMessageCodec)

/**
 * Custom type ID constants:
 *
 * Constants used to identify custom types in the codec.
 * They are used in the codec to encode and decode custom types.
 * They may be used in custom object creation functions to identify the type.
 */
extern const int xh_mc_source_msg_type_id;
extern const int xh_mc_destination_msg_type_id;
extern const int xh_mc_image_options_msg_type_id;
extern const int xh_mc_video_options_msg_type_id;
extern const int xh_mc_image_capabilities_msg_type_id;
extern const int xh_mc_video_capabilities_msg_type_id;

G_DECLARE_FINAL_TYPE(XhMcMediaCompressionHostApi, xh_mc_media_compression_host_api, XH_MC, MEDIA_COMPRESSION_HOST_API, GObject)

G_DECLARE_FINAL_TYPE(XhMcMediaCompressionHostApiResponseHandle, xh_mc_media_compression_host_api_response_handle, XH_MC, MEDIA_COMPRESSION_HOST_API_RESPONSE_HANDLE, GObject)

G_DECLARE_FINAL_TYPE(XhMcMediaCompressionHostApiCreateJobResponse, xh_mc_media_compression_host_api_create_job_response, XH_MC, MEDIA_COMPRESSION_HOST_API_CREATE_JOB_RESPONSE, GObject)

/**
 * xh_mc_media_compression_host_api_create_job_response_new:
 *
 * Creates a new response to MediaCompressionHostApi.createJob.
 *
 * Returns: a new #XhMcMediaCompressionHostApiCreateJobResponse
 */
XhMcMediaCompressionHostApiCreateJobResponse* xh_mc_media_compression_host_api_create_job_response_new(int64_t return_value);

/**
 * xh_mc_media_compression_host_api_create_job_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to MediaCompressionHostApi.createJob.
 *
 * Returns: a new #XhMcMediaCompressionHostApiCreateJobResponse
 */
XhMcMediaCompressionHostApiCreateJobResponse* xh_mc_media_compression_host_api_create_job_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(XhMcMediaCompressionHostApiQueryImageCapabilitiesResponse, xh_mc_media_compression_host_api_query_image_capabilities_response, XH_MC, MEDIA_COMPRESSION_HOST_API_QUERY_IMAGE_CAPABILITIES_RESPONSE, GObject)

/**
 * xh_mc_media_compression_host_api_query_image_capabilities_response_new:
 *
 * Creates a new response to MediaCompressionHostApi.queryImageCapabilities.
 *
 * Returns: a new #XhMcMediaCompressionHostApiQueryImageCapabilitiesResponse
 */
XhMcMediaCompressionHostApiQueryImageCapabilitiesResponse* xh_mc_media_compression_host_api_query_image_capabilities_response_new(XhMcImageCapabilitiesMsg* return_value);

/**
 * xh_mc_media_compression_host_api_query_image_capabilities_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to MediaCompressionHostApi.queryImageCapabilities.
 *
 * Returns: a new #XhMcMediaCompressionHostApiQueryImageCapabilitiesResponse
 */
XhMcMediaCompressionHostApiQueryImageCapabilitiesResponse* xh_mc_media_compression_host_api_query_image_capabilities_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(XhMcMediaCompressionHostApiQueryVideoCapabilitiesResponse, xh_mc_media_compression_host_api_query_video_capabilities_response, XH_MC, MEDIA_COMPRESSION_HOST_API_QUERY_VIDEO_CAPABILITIES_RESPONSE, GObject)

/**
 * xh_mc_media_compression_host_api_query_video_capabilities_response_new:
 *
 * Creates a new response to MediaCompressionHostApi.queryVideoCapabilities.
 *
 * Returns: a new #XhMcMediaCompressionHostApiQueryVideoCapabilitiesResponse
 */
XhMcMediaCompressionHostApiQueryVideoCapabilitiesResponse* xh_mc_media_compression_host_api_query_video_capabilities_response_new(XhMcVideoCapabilitiesMsg* return_value);

/**
 * xh_mc_media_compression_host_api_query_video_capabilities_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to MediaCompressionHostApi.queryVideoCapabilities.
 *
 * Returns: a new #XhMcMediaCompressionHostApiQueryVideoCapabilitiesResponse
 */
XhMcMediaCompressionHostApiQueryVideoCapabilitiesResponse* xh_mc_media_compression_host_api_query_video_capabilities_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(XhMcMediaCompressionHostApiCancelJobResponse, xh_mc_media_compression_host_api_cancel_job_response, XH_MC, MEDIA_COMPRESSION_HOST_API_CANCEL_JOB_RESPONSE, GObject)

/**
 * xh_mc_media_compression_host_api_cancel_job_response_new:
 *
 * Creates a new response to MediaCompressionHostApi.cancelJob.
 *
 * Returns: a new #XhMcMediaCompressionHostApiCancelJobResponse
 */
XhMcMediaCompressionHostApiCancelJobResponse* xh_mc_media_compression_host_api_cancel_job_response_new();

/**
 * xh_mc_media_compression_host_api_cancel_job_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to MediaCompressionHostApi.cancelJob.
 *
 * Returns: a new #XhMcMediaCompressionHostApiCancelJobResponse
 */
XhMcMediaCompressionHostApiCancelJobResponse* xh_mc_media_compression_host_api_cancel_job_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(XhMcMediaCompressionHostApiDisposeJobResponse, xh_mc_media_compression_host_api_dispose_job_response, XH_MC, MEDIA_COMPRESSION_HOST_API_DISPOSE_JOB_RESPONSE, GObject)

/**
 * xh_mc_media_compression_host_api_dispose_job_response_new:
 *
 * Creates a new response to MediaCompressionHostApi.disposeJob.
 *
 * Returns: a new #XhMcMediaCompressionHostApiDisposeJobResponse
 */
XhMcMediaCompressionHostApiDisposeJobResponse* xh_mc_media_compression_host_api_dispose_job_response_new();

/**
 * xh_mc_media_compression_host_api_dispose_job_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to MediaCompressionHostApi.disposeJob.
 *
 * Returns: a new #XhMcMediaCompressionHostApiDisposeJobResponse
 */
XhMcMediaCompressionHostApiDisposeJobResponse* xh_mc_media_compression_host_api_dispose_job_response_new_error(const gchar* code, const gchar* message, FlValue* details);

/**
 * XhMcMediaCompressionHostApiVTable:
 *
 * Table of functions exposed by MediaCompressionHostApi to be implemented by the API provider.
 */
typedef struct {
  XhMcMediaCompressionHostApiCreateJobResponse* (*create_job)(gpointer user_data);
  XhMcMediaCompressionHostApiQueryImageCapabilitiesResponse* (*query_image_capabilities)(gpointer user_data);
  void (*start_image_compress)(int64_t id, XhMcSourceMsg* source, XhMcDestinationMsg* destination, XhMcImageOptionsMsg* options, XhMcMediaCompressionHostApiResponseHandle* response_handle, gpointer user_data);
  XhMcMediaCompressionHostApiQueryVideoCapabilitiesResponse* (*query_video_capabilities)(gpointer user_data);
  void (*start_video_compress)(int64_t id, const gchar* input_path, const gchar* output_path, XhMcVideoOptionsMsg* options, XhMcMediaCompressionHostApiResponseHandle* response_handle, gpointer user_data);
  XhMcMediaCompressionHostApiCancelJobResponse* (*cancel_job)(int64_t id, gpointer user_data);
  XhMcMediaCompressionHostApiDisposeJobResponse* (*dispose_job)(int64_t id, gpointer user_data);
} XhMcMediaCompressionHostApiVTable;

/**
 * xh_mc_media_compression_host_api_set_method_handlers:
 *
 * @messenger: an #FlBinaryMessenger.
 * @suffix: (allow-none): a suffix to add to the API or %NULL for none.
 * @vtable: implementations of the methods in this API.
 * @user_data: (closure): user data to pass to the functions in @vtable.
 * @user_data_free_func: (allow-none): a function which gets called to free @user_data, or %NULL.
 *
 * Connects the method handlers in the MediaCompressionHostApi API.
 */
void xh_mc_media_compression_host_api_set_method_handlers(FlBinaryMessenger* messenger, const gchar* suffix, const XhMcMediaCompressionHostApiVTable* vtable, gpointer user_data, GDestroyNotify user_data_free_func);

/**
 * xh_mc_media_compression_host_api_clear_method_handlers:
 *
 * @messenger: an #FlBinaryMessenger.
 * @suffix: (allow-none): a suffix to add to the API or %NULL for none.
 *
 * Clears the method handlers in the MediaCompressionHostApi API.
 */
void xh_mc_media_compression_host_api_clear_method_handlers(FlBinaryMessenger* messenger, const gchar* suffix);

/**
 * xh_mc_media_compression_host_api_respond_start_image_compress:
 * @response_handle: a #XhMcMediaCompressionHostApiResponseHandle.
 *
 * Responds to MediaCompressionHostApi.startImageCompress. 
 */
void xh_mc_media_compression_host_api_respond_start_image_compress(XhMcMediaCompressionHostApiResponseHandle* response_handle);

/**
 * xh_mc_media_compression_host_api_respond_error_start_image_compress:
 * @response_handle: a #XhMcMediaCompressionHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to MediaCompressionHostApi.startImageCompress. 
 */
void xh_mc_media_compression_host_api_respond_error_start_image_compress(XhMcMediaCompressionHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * xh_mc_media_compression_host_api_respond_start_video_compress:
 * @response_handle: a #XhMcMediaCompressionHostApiResponseHandle.
 *
 * Responds to MediaCompressionHostApi.startVideoCompress. 
 */
void xh_mc_media_compression_host_api_respond_start_video_compress(XhMcMediaCompressionHostApiResponseHandle* response_handle);

/**
 * xh_mc_media_compression_host_api_respond_error_start_video_compress:
 * @response_handle: a #XhMcMediaCompressionHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to MediaCompressionHostApi.startVideoCompress. 
 */
void xh_mc_media_compression_host_api_respond_error_start_video_compress(XhMcMediaCompressionHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

G_END_DECLS

#endif  // PIGEON_MESSAGES_G_H_
