// Generated file. Do not edit.
// Autogenerated from Pigeon (v27.3.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#include <cmath>

#include <string.h>
#include "messages.g.h"
static guint G_GNUC_UNUSED flpigeon_hash_double(double v) {
  if (std::isnan(v)) {
    return static_cast<guint>(0x7FF80000);
  }
  if (v == 0.0) {
    v = 0.0;
  }
  union { double d; uint64_t u; } u;
  u.d = v;
  return static_cast<guint>(u.u ^ (u.u >> 32));
}
static gboolean G_GNUC_UNUSED flpigeon_equals_double(double a, double b) {
  return (a == b) || (std::isnan(a) && std::isnan(b));
}
static gboolean G_GNUC_UNUSED flpigeon_deep_equals(FlValue* a, FlValue* b) {
  if (a == b) {
    return TRUE;
  }
  if (a == nullptr || b == nullptr) {
    return FALSE;
  }
  if (fl_value_get_type(a) != fl_value_get_type(b)) {
    return FALSE;
  }
  switch (fl_value_get_type(a)) {
    case FL_VALUE_TYPE_NULL:
      return TRUE;
    case FL_VALUE_TYPE_BOOL:
      return fl_value_get_bool(a) == fl_value_get_bool(b);
    case FL_VALUE_TYPE_INT:
      return fl_value_get_int(a) == fl_value_get_int(b);
    case FL_VALUE_TYPE_FLOAT: {
      return flpigeon_equals_double(fl_value_get_float(a), fl_value_get_float(b));
    }
    case FL_VALUE_TYPE_STRING:
      return g_strcmp0(fl_value_get_string(a), fl_value_get_string(b)) == 0;
    case FL_VALUE_TYPE_UINT8_LIST:
      return fl_value_get_length(a) == fl_value_get_length(b) &&
             memcmp(fl_value_get_uint8_list(a), fl_value_get_uint8_list(b), fl_value_get_length(a)) == 0;
    case FL_VALUE_TYPE_INT32_LIST:
      return fl_value_get_length(a) == fl_value_get_length(b) &&
             memcmp(fl_value_get_int32_list(a), fl_value_get_int32_list(b), fl_value_get_length(a) * sizeof(int32_t)) == 0;
    case FL_VALUE_TYPE_INT64_LIST:
      return fl_value_get_length(a) == fl_value_get_length(b) &&
             memcmp(fl_value_get_int64_list(a), fl_value_get_int64_list(b), fl_value_get_length(a) * sizeof(int64_t)) == 0;
    case FL_VALUE_TYPE_FLOAT_LIST: {
      size_t len = fl_value_get_length(a);
      if (len != fl_value_get_length(b)) {
        return FALSE;
      }
      const double* a_data = fl_value_get_float_list(a);
      const double* b_data = fl_value_get_float_list(b);
      for (size_t i = 0; i < len; i++) {
      if (!flpigeon_equals_double(a_data[i], b_data[i])) {
        return FALSE;
      }
    }
      return TRUE;
    }
    case FL_VALUE_TYPE_LIST: {
      size_t len = fl_value_get_length(a);
      if (len != fl_value_get_length(b)) {
        return FALSE;
      }
      for (size_t i = 0; i < len; i++) {
      if (!flpigeon_deep_equals(fl_value_get_list_value(a, i), fl_value_get_list_value(b, i))) {
        return FALSE;
      }
    }
      return TRUE;
    }
    case FL_VALUE_TYPE_MAP: {
      size_t len = fl_value_get_length(a);
      if (len != fl_value_get_length(b)) {
        return FALSE;
      }
      for (size_t i = 0; i < len; i++) {
      FlValue* key = fl_value_get_map_key(a, i);
      FlValue* val = fl_value_get_map_value(a, i);
      gboolean found = FALSE;
      for (size_t j = 0; j < len; j++) {
        FlValue* b_key = fl_value_get_map_key(b, j);
        if (flpigeon_deep_equals(key, b_key)) {
          FlValue* b_val = fl_value_get_map_value(b, j);
          if (flpigeon_deep_equals(val, b_val)) {
            found = TRUE;
            break;
          } else {
            return FALSE;
          }
        }
      }
      if (!found) {
        return FALSE;
      }
    }
      return TRUE;
    }
    default:
      return FALSE;
  }
  return FALSE;
}
static guint G_GNUC_UNUSED flpigeon_deep_hash(FlValue* value) {
  if (value == nullptr) {
    return 0;
  }
  switch (fl_value_get_type(value)) {
    case FL_VALUE_TYPE_NULL:
      return 0;
    case FL_VALUE_TYPE_BOOL:
      return fl_value_get_bool(value) ? 1231 : 1237;
    case FL_VALUE_TYPE_INT: {
      int64_t v = fl_value_get_int(value);
      return static_cast<guint>(v ^ (v >> 32));
    }
    case FL_VALUE_TYPE_FLOAT:
      return flpigeon_hash_double(fl_value_get_float(value));
    case FL_VALUE_TYPE_STRING:
      return g_str_hash(fl_value_get_string(value));
    case FL_VALUE_TYPE_UINT8_LIST: {
      guint result = 1;
      size_t len = fl_value_get_length(value);
      const uint8_t* data = fl_value_get_uint8_list(value);
      for (size_t i = 0; i < len; i++) {
        result = result * 31 + data[i];
      }
      return result;
    }
    case FL_VALUE_TYPE_INT32_LIST: {
      guint result = 1;
      size_t len = fl_value_get_length(value);
      const int32_t* data = fl_value_get_int32_list(value);
      for (size_t i = 0; i < len; i++) {
        result = result * 31 + static_cast<guint>(data[i]);
      }
      return result;
    }
    case FL_VALUE_TYPE_INT64_LIST: {
      guint result = 1;
      size_t len = fl_value_get_length(value);
      const int64_t* data = fl_value_get_int64_list(value);
      for (size_t i = 0; i < len; i++) {
        result = result * 31 + static_cast<guint>(data[i] ^ (data[i] >> 32));
      }
      return result;
    }
    case FL_VALUE_TYPE_FLOAT_LIST: {
      guint result = 1;
      size_t len = fl_value_get_length(value);
      const double* data = fl_value_get_float_list(value);
      for (size_t i = 0; i < len; i++) {
      result = result * 31 + flpigeon_hash_double(data[i]);
    }
      return result;
    }
    case FL_VALUE_TYPE_LIST: {
      guint result = 1;
      size_t len = fl_value_get_length(value);
      for (size_t i = 0; i < len; i++) {
      result = result * 31 + flpigeon_deep_hash(fl_value_get_list_value(value, i));
    }
      return result;
    }
    case FL_VALUE_TYPE_MAP: {
      guint result = 0;
      size_t len = fl_value_get_length(value);
      for (size_t i = 0; i < len; i++) {
      result += ((flpigeon_deep_hash(fl_value_get_map_key(value, i)) * 31) ^ flpigeon_deep_hash(fl_value_get_map_value(value, i)));
    }
      return result;
    }
    default:
      return static_cast<guint>(fl_value_get_type(value));
  }
  return 0;
}
static gchar* G_GNUC_UNUSED flpigeon_to_string(FlValue* value) {
  if (value == nullptr) {
    return g_strdup("null");
  }
  switch (fl_value_get_type(value)) {
    case FL_VALUE_TYPE_NULL:
      return g_strdup("null");
    case FL_VALUE_TYPE_BOOL:
      return g_strdup(fl_value_get_bool(value) ? "true" : "false");
    case FL_VALUE_TYPE_INT:
      return g_strdup_printf("%" G_GINT64_FORMAT, fl_value_get_int(value));
    case FL_VALUE_TYPE_FLOAT:
      return g_strdup_printf("%g", fl_value_get_float(value));
    case FL_VALUE_TYPE_STRING:
      return g_strdup_printf("\"%s\"", fl_value_get_string(value));
    case FL_VALUE_TYPE_UINT8_LIST: {
      GString* str = g_string_new("[");
      size_t len = fl_value_get_length(value);
      const uint8_t* data = fl_value_get_uint8_list(value);
      for (size_t i = 0; i < len; i++) {
        if (i > 0) {
          g_string_append(str, ", ");
        }
        g_string_append_printf(str, "%d", data[i]);
      }
      g_string_append(str, "]");
      return g_string_free(str, FALSE);
    }
    case FL_VALUE_TYPE_INT32_LIST: {
      GString* str = g_string_new("[");
      size_t len = fl_value_get_length(value);
      const int32_t* data = fl_value_get_int32_list(value);
      for (size_t i = 0; i < len; i++) {
        if (i > 0) {
          g_string_append(str, ", ");
        }
        g_string_append_printf(str, "%d", data[i]);
      }
      g_string_append(str, "]");
      return g_string_free(str, FALSE);
    }
    case FL_VALUE_TYPE_INT64_LIST: {
      GString* str = g_string_new("[");
      size_t len = fl_value_get_length(value);
      const int64_t* data = fl_value_get_int64_list(value);
      for (size_t i = 0; i < len; i++) {
        if (i > 0) {
          g_string_append(str, ", ");
        }
        g_string_append_printf(str, "%" G_GINT64_FORMAT, data[i]);
      }
      g_string_append(str, "]");
      return g_string_free(str, FALSE);
    }
    case FL_VALUE_TYPE_FLOAT_LIST: {
      GString* str = g_string_new("[");
      size_t len = fl_value_get_length(value);
      const double* data = fl_value_get_float_list(value);
      for (size_t i = 0; i < len; i++) {
        if (i > 0) {
          g_string_append(str, ", ");
        }
        g_string_append_printf(str, "%g", data[i]);
      }
      g_string_append(str, "]");
      return g_string_free(str, FALSE);
    }
    case FL_VALUE_TYPE_LIST: {
      GString* str = g_string_new("[");
      size_t len = fl_value_get_length(value);
      for (size_t i = 0; i < len; i++) {
        if (i > 0) {
          g_string_append(str, ", ");
        }
        gchar* item_str = flpigeon_to_string(fl_value_get_list_value(value, i));
        g_string_append(str, item_str);
        g_free(item_str);
      }
      g_string_append(str, "]");
      return g_string_free(str, FALSE);
    }
    case FL_VALUE_TYPE_MAP: {
      GString* str = g_string_new("{");
      size_t len = fl_value_get_length(value);
      for (size_t i = 0; i < len; i++) {
        if (i > 0) {
          g_string_append(str, ", ");
        }
        gchar* key_str = flpigeon_to_string(fl_value_get_map_key(value, i));
        gchar* val_str = flpigeon_to_string(fl_value_get_map_value(value, i));
        g_string_append_printf(str, "%s: %s", key_str, val_str);
        g_free(key_str);
        g_free(val_str);
      }
      g_string_append(str, "}");
      return g_string_free(str, FALSE);
    }
    default:
      return g_strdup("[custom]");
  }
  return g_strdup("null");
}


struct _XhMcSourceMsg {
  GObject parent_instance;

  int64_t kind;
  uint8_t* bytes;
  size_t bytes_length;
  gchar* path;
};

G_DEFINE_TYPE(XhMcSourceMsg, xh_mc_source_msg, G_TYPE_OBJECT)

static void xh_mc_source_msg_dispose(GObject* object) {
  XhMcSourceMsg* self = XH_MC_SOURCE_MSG(object);
  g_clear_pointer(&self->path, g_free);
  G_OBJECT_CLASS(xh_mc_source_msg_parent_class)->dispose(object);
}

static void xh_mc_source_msg_init(XhMcSourceMsg* self) {
}

static void xh_mc_source_msg_class_init(XhMcSourceMsgClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = xh_mc_source_msg_dispose;
}

XhMcSourceMsg* xh_mc_source_msg_new(int64_t kind, const uint8_t* bytes, size_t bytes_length, const gchar* path) {
  XhMcSourceMsg* self = XH_MC_SOURCE_MSG(g_object_new(xh_mc_source_msg_get_type(), nullptr));
  self->kind = kind;
  if (bytes != nullptr) {
    self->bytes = static_cast<uint8_t*>(memcpy(malloc(bytes_length), bytes, bytes_length));
    self->bytes_length = bytes_length;
  }
  else {
    self->bytes = nullptr;
    self->bytes_length = 0;
  }
  if (path != nullptr) {
    self->path = g_strdup(path);
  }
  else {
    self->path = nullptr;
  }
  return self;
}

int64_t xh_mc_source_msg_get_kind(XhMcSourceMsg* self) {
  g_return_val_if_fail(XH_MC_IS_SOURCE_MSG(self), 0);
  return self->kind;
}

const uint8_t* xh_mc_source_msg_get_bytes(XhMcSourceMsg* self, size_t* length) {
  g_return_val_if_fail(XH_MC_IS_SOURCE_MSG(self), nullptr);
  *length = self->bytes_length;
  return self->bytes;
}

const gchar* xh_mc_source_msg_get_path(XhMcSourceMsg* self) {
  g_return_val_if_fail(XH_MC_IS_SOURCE_MSG(self), nullptr);
  return self->path;
}

static FlValue* xh_mc_source_msg_to_list(XhMcSourceMsg* self) {
  FlValue* values = fl_value_new_list();
  fl_value_append_take(values, fl_value_new_int(self->kind));
  fl_value_append_take(values, self->bytes != nullptr ? fl_value_new_uint8_list(self->bytes, self->bytes_length) : fl_value_new_null());
  fl_value_append_take(values, self->path != nullptr ? fl_value_new_string(self->path) : fl_value_new_null());
  return values;
}

static XhMcSourceMsg* xh_mc_source_msg_new_from_list(FlValue* values) {
  FlValue* value0 = fl_value_get_list_value(values, 0);
  int64_t kind = fl_value_get_int(value0);
  FlValue* value1 = fl_value_get_list_value(values, 1);
  const uint8_t* bytes = nullptr;
  size_t bytes_length = 0;
  if (fl_value_get_type(value1) != FL_VALUE_TYPE_NULL) {
    bytes = fl_value_get_uint8_list(value1);
    bytes_length = fl_value_get_length(value1);
  }
  FlValue* value2 = fl_value_get_list_value(values, 2);
  const gchar* path = nullptr;
  if (fl_value_get_type(value2) != FL_VALUE_TYPE_NULL) {
    path = fl_value_get_string(value2);
  }
  return xh_mc_source_msg_new(kind, bytes, bytes_length, path);
}

gboolean xh_mc_source_msg_equals(XhMcSourceMsg* a, XhMcSourceMsg* b) {
  if (a == b) {
    return TRUE;
  }
  if (a == nullptr || b == nullptr) {
    return FALSE;
  }
  if (a->kind != b->kind) {
    return FALSE;
  }
  if (a->bytes != b->bytes) {
    if (a->bytes == nullptr || b->bytes == nullptr) {
      return FALSE;
    }
    if (a->bytes_length != b->bytes_length) {
      return FALSE;
    }
    if (memcmp(a->bytes, b->bytes, a->bytes_length * sizeof(uint8_t)) != 0) {
      return FALSE;
    }
  }
  if (g_strcmp0(a->path, b->path) != 0) {
    return FALSE;
  }
  return TRUE;
}

guint xh_mc_source_msg_hash(XhMcSourceMsg* self) {
  g_return_val_if_fail(XH_MC_IS_SOURCE_MSG(self), 0);
  guint result = 0;
  result = result * 31 + static_cast<guint>(self->kind);
  {
    size_t len = self->bytes_length;
    const uint8_t* data = self->bytes;
    if (data != nullptr) {
      for (size_t i = 0; i < len; i++) {
        result = result * 31 + static_cast<guint>(data[i]);
      }
    }
  }
  result = result * 31 + (self->path != nullptr ? g_str_hash(self->path) : 0);
  return result;
}

gchar* xh_mc_source_msg_to_string(XhMcSourceMsg* self) {
  g_return_val_if_fail(XH_MC_IS_SOURCE_MSG(self), NULL);
  GString* str = g_string_new("SourceMsg(");
  g_string_append(str, "kind: ");
  g_string_append_printf(str, "%" G_GINT64_FORMAT, self->kind);
  g_string_append(str, ", bytes: ");
  if (self->bytes != nullptr) {
    g_string_append(str, "[");
    size_t len = self->bytes_length;
    const uint8_t* data = self->bytes;
    for (size_t i = 0; i < len; i++) {
      if (i > 0) {
        g_string_append(str, ", ");
      }
      g_string_append_printf(str, "%d", static_cast<int>(data[i]));
    }
    g_string_append(str, "]");
  }
  else {
    g_string_append(str, "null");
  }
  g_string_append(str, ", path: ");
  if (self->path != nullptr) {
    g_string_append_printf(str, "\"%s\"", self->path);
  }
  else {
    g_string_append(str, "null");
  }
  g_string_append(str, ")");
  return g_string_free(str, FALSE);
}

struct _XhMcDestinationMsg {
  GObject parent_instance;

  int64_t kind;
  gchar* path;
};

G_DEFINE_TYPE(XhMcDestinationMsg, xh_mc_destination_msg, G_TYPE_OBJECT)

static void xh_mc_destination_msg_dispose(GObject* object) {
  XhMcDestinationMsg* self = XH_MC_DESTINATION_MSG(object);
  g_clear_pointer(&self->path, g_free);
  G_OBJECT_CLASS(xh_mc_destination_msg_parent_class)->dispose(object);
}

static void xh_mc_destination_msg_init(XhMcDestinationMsg* self) {
}

static void xh_mc_destination_msg_class_init(XhMcDestinationMsgClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = xh_mc_destination_msg_dispose;
}

XhMcDestinationMsg* xh_mc_destination_msg_new(int64_t kind, const gchar* path) {
  XhMcDestinationMsg* self = XH_MC_DESTINATION_MSG(g_object_new(xh_mc_destination_msg_get_type(), nullptr));
  self->kind = kind;
  if (path != nullptr) {
    self->path = g_strdup(path);
  }
  else {
    self->path = nullptr;
  }
  return self;
}

int64_t xh_mc_destination_msg_get_kind(XhMcDestinationMsg* self) {
  g_return_val_if_fail(XH_MC_IS_DESTINATION_MSG(self), 0);
  return self->kind;
}

const gchar* xh_mc_destination_msg_get_path(XhMcDestinationMsg* self) {
  g_return_val_if_fail(XH_MC_IS_DESTINATION_MSG(self), nullptr);
  return self->path;
}

static FlValue* xh_mc_destination_msg_to_list(XhMcDestinationMsg* self) {
  FlValue* values = fl_value_new_list();
  fl_value_append_take(values, fl_value_new_int(self->kind));
  fl_value_append_take(values, self->path != nullptr ? fl_value_new_string(self->path) : fl_value_new_null());
  return values;
}

static XhMcDestinationMsg* xh_mc_destination_msg_new_from_list(FlValue* values) {
  FlValue* value0 = fl_value_get_list_value(values, 0);
  int64_t kind = fl_value_get_int(value0);
  FlValue* value1 = fl_value_get_list_value(values, 1);
  const gchar* path = nullptr;
  if (fl_value_get_type(value1) != FL_VALUE_TYPE_NULL) {
    path = fl_value_get_string(value1);
  }
  return xh_mc_destination_msg_new(kind, path);
}

gboolean xh_mc_destination_msg_equals(XhMcDestinationMsg* a, XhMcDestinationMsg* b) {
  if (a == b) {
    return TRUE;
  }
  if (a == nullptr || b == nullptr) {
    return FALSE;
  }
  if (a->kind != b->kind) {
    return FALSE;
  }
  if (g_strcmp0(a->path, b->path) != 0) {
    return FALSE;
  }
  return TRUE;
}

guint xh_mc_destination_msg_hash(XhMcDestinationMsg* self) {
  g_return_val_if_fail(XH_MC_IS_DESTINATION_MSG(self), 0);
  guint result = 0;
  result = result * 31 + static_cast<guint>(self->kind);
  result = result * 31 + (self->path != nullptr ? g_str_hash(self->path) : 0);
  return result;
}

gchar* xh_mc_destination_msg_to_string(XhMcDestinationMsg* self) {
  g_return_val_if_fail(XH_MC_IS_DESTINATION_MSG(self), NULL);
  GString* str = g_string_new("DestinationMsg(");
  g_string_append(str, "kind: ");
  g_string_append_printf(str, "%" G_GINT64_FORMAT, self->kind);
  g_string_append(str, ", path: ");
  if (self->path != nullptr) {
    g_string_append_printf(str, "\"%s\"", self->path);
  }
  else {
    g_string_append(str, "null");
  }
  g_string_append(str, ")");
  return g_string_free(str, FALSE);
}

struct _XhMcImageOptionsMsg {
  GObject parent_instance;

  gchar* format;
  int64_t quality;
  int64_t* max_dimension;
  gboolean keep_metadata;
};

G_DEFINE_TYPE(XhMcImageOptionsMsg, xh_mc_image_options_msg, G_TYPE_OBJECT)

static void xh_mc_image_options_msg_dispose(GObject* object) {
  XhMcImageOptionsMsg* self = XH_MC_IMAGE_OPTIONS_MSG(object);
  g_clear_pointer(&self->format, g_free);
  g_clear_pointer(&self->max_dimension, g_free);
  G_OBJECT_CLASS(xh_mc_image_options_msg_parent_class)->dispose(object);
}

static void xh_mc_image_options_msg_init(XhMcImageOptionsMsg* self) {
}

static void xh_mc_image_options_msg_class_init(XhMcImageOptionsMsgClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = xh_mc_image_options_msg_dispose;
}

XhMcImageOptionsMsg* xh_mc_image_options_msg_new(const gchar* format, int64_t quality, int64_t* max_dimension, gboolean keep_metadata) {
  XhMcImageOptionsMsg* self = XH_MC_IMAGE_OPTIONS_MSG(g_object_new(xh_mc_image_options_msg_get_type(), nullptr));
  self->format = g_strdup(format);
  self->quality = quality;
  if (max_dimension != nullptr) {
    self->max_dimension = static_cast<int64_t*>(malloc(sizeof(int64_t)));
    *self->max_dimension = *max_dimension;
  }
  else {
    self->max_dimension = nullptr;
  }
  self->keep_metadata = keep_metadata;
  return self;
}

const gchar* xh_mc_image_options_msg_get_format(XhMcImageOptionsMsg* self) {
  g_return_val_if_fail(XH_MC_IS_IMAGE_OPTIONS_MSG(self), nullptr);
  return self->format;
}

int64_t xh_mc_image_options_msg_get_quality(XhMcImageOptionsMsg* self) {
  g_return_val_if_fail(XH_MC_IS_IMAGE_OPTIONS_MSG(self), 0);
  return self->quality;
}

int64_t* xh_mc_image_options_msg_get_max_dimension(XhMcImageOptionsMsg* self) {
  g_return_val_if_fail(XH_MC_IS_IMAGE_OPTIONS_MSG(self), nullptr);
  return self->max_dimension;
}

gboolean xh_mc_image_options_msg_get_keep_metadata(XhMcImageOptionsMsg* self) {
  g_return_val_if_fail(XH_MC_IS_IMAGE_OPTIONS_MSG(self), FALSE);
  return self->keep_metadata;
}

static FlValue* xh_mc_image_options_msg_to_list(XhMcImageOptionsMsg* self) {
  FlValue* values = fl_value_new_list();
  fl_value_append_take(values, fl_value_new_string(self->format));
  fl_value_append_take(values, fl_value_new_int(self->quality));
  fl_value_append_take(values, self->max_dimension != nullptr ? fl_value_new_int(*self->max_dimension) : fl_value_new_null());
  fl_value_append_take(values, fl_value_new_bool(self->keep_metadata));
  return values;
}

static XhMcImageOptionsMsg* xh_mc_image_options_msg_new_from_list(FlValue* values) {
  FlValue* value0 = fl_value_get_list_value(values, 0);
  const gchar* format = fl_value_get_string(value0);
  FlValue* value1 = fl_value_get_list_value(values, 1);
  int64_t quality = fl_value_get_int(value1);
  FlValue* value2 = fl_value_get_list_value(values, 2);
  int64_t* max_dimension = nullptr;
  int64_t max_dimension_value;
  if (fl_value_get_type(value2) != FL_VALUE_TYPE_NULL) {
    max_dimension_value = fl_value_get_int(value2);
    max_dimension = &max_dimension_value;
  }
  FlValue* value3 = fl_value_get_list_value(values, 3);
  gboolean keep_metadata = fl_value_get_bool(value3);
  return xh_mc_image_options_msg_new(format, quality, max_dimension, keep_metadata);
}

gboolean xh_mc_image_options_msg_equals(XhMcImageOptionsMsg* a, XhMcImageOptionsMsg* b) {
  if (a == b) {
    return TRUE;
  }
  if (a == nullptr || b == nullptr) {
    return FALSE;
  }
  if (g_strcmp0(a->format, b->format) != 0) {
    return FALSE;
  }
  if (a->quality != b->quality) {
    return FALSE;
  }
  if ((a->max_dimension == nullptr) != (b->max_dimension == nullptr)) {
    return FALSE;
  }
  if (a->max_dimension != nullptr && *a->max_dimension != *b->max_dimension) {
    return FALSE;
  }
  if (a->keep_metadata != b->keep_metadata) {
    return FALSE;
  }
  return TRUE;
}

guint xh_mc_image_options_msg_hash(XhMcImageOptionsMsg* self) {
  g_return_val_if_fail(XH_MC_IS_IMAGE_OPTIONS_MSG(self), 0);
  guint result = 0;
  result = result * 31 + (self->format != nullptr ? g_str_hash(self->format) : 0);
  result = result * 31 + static_cast<guint>(self->quality);
  result = result * 31 + (self->max_dimension != nullptr ? static_cast<guint>(*self->max_dimension) : 0);
  result = result * 31 + static_cast<guint>(self->keep_metadata);
  return result;
}

gchar* xh_mc_image_options_msg_to_string(XhMcImageOptionsMsg* self) {
  g_return_val_if_fail(XH_MC_IS_IMAGE_OPTIONS_MSG(self), NULL);
  GString* str = g_string_new("ImageOptionsMsg(");
  g_string_append(str, "format: ");
  if (self->format != nullptr) {
    g_string_append_printf(str, "\"%s\"", self->format);
  }
  else {
    g_string_append(str, "null");
  }
  g_string_append(str, ", quality: ");
  g_string_append_printf(str, "%" G_GINT64_FORMAT, self->quality);
  g_string_append(str, ", max_dimension: ");
  if (self->max_dimension != nullptr) {
    g_string_append_printf(str, "%" G_GINT64_FORMAT, *self->max_dimension);
  }
  else {
    g_string_append(str, "null");
  }
  g_string_append(str, ", keep_metadata: ");
  g_string_append(str, self->keep_metadata ? "true" : "false");
  g_string_append(str, ")");
  return g_string_free(str, FALSE);
}

struct _XhMcVideoOptionsMsg {
  GObject parent_instance;

  gchar* codec;
  int64_t bitrate;
  int64_t* fps;
  int64_t* max_dimension;
  int64_t* keyframe_interval;
  gboolean keep_audio;
};

G_DEFINE_TYPE(XhMcVideoOptionsMsg, xh_mc_video_options_msg, G_TYPE_OBJECT)

static void xh_mc_video_options_msg_dispose(GObject* object) {
  XhMcVideoOptionsMsg* self = XH_MC_VIDEO_OPTIONS_MSG(object);
  g_clear_pointer(&self->codec, g_free);
  g_clear_pointer(&self->fps, g_free);
  g_clear_pointer(&self->max_dimension, g_free);
  g_clear_pointer(&self->keyframe_interval, g_free);
  G_OBJECT_CLASS(xh_mc_video_options_msg_parent_class)->dispose(object);
}

static void xh_mc_video_options_msg_init(XhMcVideoOptionsMsg* self) {
}

static void xh_mc_video_options_msg_class_init(XhMcVideoOptionsMsgClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = xh_mc_video_options_msg_dispose;
}

XhMcVideoOptionsMsg* xh_mc_video_options_msg_new(const gchar* codec, int64_t bitrate, int64_t* fps, int64_t* max_dimension, int64_t* keyframe_interval, gboolean keep_audio) {
  XhMcVideoOptionsMsg* self = XH_MC_VIDEO_OPTIONS_MSG(g_object_new(xh_mc_video_options_msg_get_type(), nullptr));
  self->codec = g_strdup(codec);
  self->bitrate = bitrate;
  if (fps != nullptr) {
    self->fps = static_cast<int64_t*>(malloc(sizeof(int64_t)));
    *self->fps = *fps;
  }
  else {
    self->fps = nullptr;
  }
  if (max_dimension != nullptr) {
    self->max_dimension = static_cast<int64_t*>(malloc(sizeof(int64_t)));
    *self->max_dimension = *max_dimension;
  }
  else {
    self->max_dimension = nullptr;
  }
  if (keyframe_interval != nullptr) {
    self->keyframe_interval = static_cast<int64_t*>(malloc(sizeof(int64_t)));
    *self->keyframe_interval = *keyframe_interval;
  }
  else {
    self->keyframe_interval = nullptr;
  }
  self->keep_audio = keep_audio;
  return self;
}

const gchar* xh_mc_video_options_msg_get_codec(XhMcVideoOptionsMsg* self) {
  g_return_val_if_fail(XH_MC_IS_VIDEO_OPTIONS_MSG(self), nullptr);
  return self->codec;
}

int64_t xh_mc_video_options_msg_get_bitrate(XhMcVideoOptionsMsg* self) {
  g_return_val_if_fail(XH_MC_IS_VIDEO_OPTIONS_MSG(self), 0);
  return self->bitrate;
}

int64_t* xh_mc_video_options_msg_get_fps(XhMcVideoOptionsMsg* self) {
  g_return_val_if_fail(XH_MC_IS_VIDEO_OPTIONS_MSG(self), nullptr);
  return self->fps;
}

int64_t* xh_mc_video_options_msg_get_max_dimension(XhMcVideoOptionsMsg* self) {
  g_return_val_if_fail(XH_MC_IS_VIDEO_OPTIONS_MSG(self), nullptr);
  return self->max_dimension;
}

int64_t* xh_mc_video_options_msg_get_keyframe_interval(XhMcVideoOptionsMsg* self) {
  g_return_val_if_fail(XH_MC_IS_VIDEO_OPTIONS_MSG(self), nullptr);
  return self->keyframe_interval;
}

gboolean xh_mc_video_options_msg_get_keep_audio(XhMcVideoOptionsMsg* self) {
  g_return_val_if_fail(XH_MC_IS_VIDEO_OPTIONS_MSG(self), FALSE);
  return self->keep_audio;
}

static FlValue* xh_mc_video_options_msg_to_list(XhMcVideoOptionsMsg* self) {
  FlValue* values = fl_value_new_list();
  fl_value_append_take(values, fl_value_new_string(self->codec));
  fl_value_append_take(values, fl_value_new_int(self->bitrate));
  fl_value_append_take(values, self->fps != nullptr ? fl_value_new_int(*self->fps) : fl_value_new_null());
  fl_value_append_take(values, self->max_dimension != nullptr ? fl_value_new_int(*self->max_dimension) : fl_value_new_null());
  fl_value_append_take(values, self->keyframe_interval != nullptr ? fl_value_new_int(*self->keyframe_interval) : fl_value_new_null());
  fl_value_append_take(values, fl_value_new_bool(self->keep_audio));
  return values;
}

static XhMcVideoOptionsMsg* xh_mc_video_options_msg_new_from_list(FlValue* values) {
  FlValue* value0 = fl_value_get_list_value(values, 0);
  const gchar* codec = fl_value_get_string(value0);
  FlValue* value1 = fl_value_get_list_value(values, 1);
  int64_t bitrate = fl_value_get_int(value1);
  FlValue* value2 = fl_value_get_list_value(values, 2);
  int64_t* fps = nullptr;
  int64_t fps_value;
  if (fl_value_get_type(value2) != FL_VALUE_TYPE_NULL) {
    fps_value = fl_value_get_int(value2);
    fps = &fps_value;
  }
  FlValue* value3 = fl_value_get_list_value(values, 3);
  int64_t* max_dimension = nullptr;
  int64_t max_dimension_value;
  if (fl_value_get_type(value3) != FL_VALUE_TYPE_NULL) {
    max_dimension_value = fl_value_get_int(value3);
    max_dimension = &max_dimension_value;
  }
  FlValue* value4 = fl_value_get_list_value(values, 4);
  int64_t* keyframe_interval = nullptr;
  int64_t keyframe_interval_value;
  if (fl_value_get_type(value4) != FL_VALUE_TYPE_NULL) {
    keyframe_interval_value = fl_value_get_int(value4);
    keyframe_interval = &keyframe_interval_value;
  }
  FlValue* value5 = fl_value_get_list_value(values, 5);
  gboolean keep_audio = fl_value_get_bool(value5);
  return xh_mc_video_options_msg_new(codec, bitrate, fps, max_dimension, keyframe_interval, keep_audio);
}

gboolean xh_mc_video_options_msg_equals(XhMcVideoOptionsMsg* a, XhMcVideoOptionsMsg* b) {
  if (a == b) {
    return TRUE;
  }
  if (a == nullptr || b == nullptr) {
    return FALSE;
  }
  if (g_strcmp0(a->codec, b->codec) != 0) {
    return FALSE;
  }
  if (a->bitrate != b->bitrate) {
    return FALSE;
  }
  if ((a->fps == nullptr) != (b->fps == nullptr)) {
    return FALSE;
  }
  if (a->fps != nullptr && *a->fps != *b->fps) {
    return FALSE;
  }
  if ((a->max_dimension == nullptr) != (b->max_dimension == nullptr)) {
    return FALSE;
  }
  if (a->max_dimension != nullptr && *a->max_dimension != *b->max_dimension) {
    return FALSE;
  }
  if ((a->keyframe_interval == nullptr) != (b->keyframe_interval == nullptr)) {
    return FALSE;
  }
  if (a->keyframe_interval != nullptr && *a->keyframe_interval != *b->keyframe_interval) {
    return FALSE;
  }
  if (a->keep_audio != b->keep_audio) {
    return FALSE;
  }
  return TRUE;
}

guint xh_mc_video_options_msg_hash(XhMcVideoOptionsMsg* self) {
  g_return_val_if_fail(XH_MC_IS_VIDEO_OPTIONS_MSG(self), 0);
  guint result = 0;
  result = result * 31 + (self->codec != nullptr ? g_str_hash(self->codec) : 0);
  result = result * 31 + static_cast<guint>(self->bitrate);
  result = result * 31 + (self->fps != nullptr ? static_cast<guint>(*self->fps) : 0);
  result = result * 31 + (self->max_dimension != nullptr ? static_cast<guint>(*self->max_dimension) : 0);
  result = result * 31 + (self->keyframe_interval != nullptr ? static_cast<guint>(*self->keyframe_interval) : 0);
  result = result * 31 + static_cast<guint>(self->keep_audio);
  return result;
}

gchar* xh_mc_video_options_msg_to_string(XhMcVideoOptionsMsg* self) {
  g_return_val_if_fail(XH_MC_IS_VIDEO_OPTIONS_MSG(self), NULL);
  GString* str = g_string_new("VideoOptionsMsg(");
  g_string_append(str, "codec: ");
  if (self->codec != nullptr) {
    g_string_append_printf(str, "\"%s\"", self->codec);
  }
  else {
    g_string_append(str, "null");
  }
  g_string_append(str, ", bitrate: ");
  g_string_append_printf(str, "%" G_GINT64_FORMAT, self->bitrate);
  g_string_append(str, ", fps: ");
  if (self->fps != nullptr) {
    g_string_append_printf(str, "%" G_GINT64_FORMAT, *self->fps);
  }
  else {
    g_string_append(str, "null");
  }
  g_string_append(str, ", max_dimension: ");
  if (self->max_dimension != nullptr) {
    g_string_append_printf(str, "%" G_GINT64_FORMAT, *self->max_dimension);
  }
  else {
    g_string_append(str, "null");
  }
  g_string_append(str, ", keyframe_interval: ");
  if (self->keyframe_interval != nullptr) {
    g_string_append_printf(str, "%" G_GINT64_FORMAT, *self->keyframe_interval);
  }
  else {
    g_string_append(str, "null");
  }
  g_string_append(str, ", keep_audio: ");
  g_string_append(str, self->keep_audio ? "true" : "false");
  g_string_append(str, ")");
  return g_string_free(str, FALSE);
}

struct _XhMcImageCapabilitiesMsg {
  GObject parent_instance;

  FlValue* input_formats;
  FlValue* output_formats;
};

G_DEFINE_TYPE(XhMcImageCapabilitiesMsg, xh_mc_image_capabilities_msg, G_TYPE_OBJECT)

static void xh_mc_image_capabilities_msg_dispose(GObject* object) {
  XhMcImageCapabilitiesMsg* self = XH_MC_IMAGE_CAPABILITIES_MSG(object);
  g_clear_pointer(&self->input_formats, fl_value_unref);
  g_clear_pointer(&self->output_formats, fl_value_unref);
  G_OBJECT_CLASS(xh_mc_image_capabilities_msg_parent_class)->dispose(object);
}

static void xh_mc_image_capabilities_msg_init(XhMcImageCapabilitiesMsg* self) {
}

static void xh_mc_image_capabilities_msg_class_init(XhMcImageCapabilitiesMsgClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = xh_mc_image_capabilities_msg_dispose;
}

XhMcImageCapabilitiesMsg* xh_mc_image_capabilities_msg_new(FlValue* input_formats, FlValue* output_formats) {
  XhMcImageCapabilitiesMsg* self = XH_MC_IMAGE_CAPABILITIES_MSG(g_object_new(xh_mc_image_capabilities_msg_get_type(), nullptr));
  self->input_formats = fl_value_ref(input_formats);
  self->output_formats = fl_value_ref(output_formats);
  return self;
}

FlValue* xh_mc_image_capabilities_msg_get_input_formats(XhMcImageCapabilitiesMsg* self) {
  g_return_val_if_fail(XH_MC_IS_IMAGE_CAPABILITIES_MSG(self), nullptr);
  return self->input_formats;
}

FlValue* xh_mc_image_capabilities_msg_get_output_formats(XhMcImageCapabilitiesMsg* self) {
  g_return_val_if_fail(XH_MC_IS_IMAGE_CAPABILITIES_MSG(self), nullptr);
  return self->output_formats;
}

static FlValue* xh_mc_image_capabilities_msg_to_list(XhMcImageCapabilitiesMsg* self) {
  FlValue* values = fl_value_new_list();
  fl_value_append_take(values, fl_value_ref(self->input_formats));
  fl_value_append_take(values, fl_value_ref(self->output_formats));
  return values;
}

static XhMcImageCapabilitiesMsg* xh_mc_image_capabilities_msg_new_from_list(FlValue* values) {
  FlValue* value0 = fl_value_get_list_value(values, 0);
  FlValue* input_formats = value0;
  FlValue* value1 = fl_value_get_list_value(values, 1);
  FlValue* output_formats = value1;
  return xh_mc_image_capabilities_msg_new(input_formats, output_formats);
}

gboolean xh_mc_image_capabilities_msg_equals(XhMcImageCapabilitiesMsg* a, XhMcImageCapabilitiesMsg* b) {
  if (a == b) {
    return TRUE;
  }
  if (a == nullptr || b == nullptr) {
    return FALSE;
  }
  if (!flpigeon_deep_equals(a->input_formats, b->input_formats)) {
    return FALSE;
  }
  if (!flpigeon_deep_equals(a->output_formats, b->output_formats)) {
    return FALSE;
  }
  return TRUE;
}

guint xh_mc_image_capabilities_msg_hash(XhMcImageCapabilitiesMsg* self) {
  g_return_val_if_fail(XH_MC_IS_IMAGE_CAPABILITIES_MSG(self), 0);
  guint result = 0;
  result = result * 31 + flpigeon_deep_hash(self->input_formats);
  result = result * 31 + flpigeon_deep_hash(self->output_formats);
  return result;
}

gchar* xh_mc_image_capabilities_msg_to_string(XhMcImageCapabilitiesMsg* self) {
  g_return_val_if_fail(XH_MC_IS_IMAGE_CAPABILITIES_MSG(self), NULL);
  GString* str = g_string_new("ImageCapabilitiesMsg(");
  g_string_append(str, "input_formats: ");
  if (self->input_formats != nullptr) {
    gchar* val_str = flpigeon_to_string(self->input_formats);
    g_string_append(str, val_str);
    g_free(val_str);
  }
  else {
    g_string_append(str, "null");
  }
  g_string_append(str, ", output_formats: ");
  if (self->output_formats != nullptr) {
    gchar* val_str = flpigeon_to_string(self->output_formats);
    g_string_append(str, val_str);
    g_free(val_str);
  }
  else {
    g_string_append(str, "null");
  }
  g_string_append(str, ")");
  return g_string_free(str, FALSE);
}

struct _XhMcVideoCapabilitiesMsg {
  GObject parent_instance;

  gchar* encoder_name;
  FlValue* codecs;
  gboolean accepts_content_uri;
};

G_DEFINE_TYPE(XhMcVideoCapabilitiesMsg, xh_mc_video_capabilities_msg, G_TYPE_OBJECT)

static void xh_mc_video_capabilities_msg_dispose(GObject* object) {
  XhMcVideoCapabilitiesMsg* self = XH_MC_VIDEO_CAPABILITIES_MSG(object);
  g_clear_pointer(&self->encoder_name, g_free);
  g_clear_pointer(&self->codecs, fl_value_unref);
  G_OBJECT_CLASS(xh_mc_video_capabilities_msg_parent_class)->dispose(object);
}

static void xh_mc_video_capabilities_msg_init(XhMcVideoCapabilitiesMsg* self) {
}

static void xh_mc_video_capabilities_msg_class_init(XhMcVideoCapabilitiesMsgClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = xh_mc_video_capabilities_msg_dispose;
}

XhMcVideoCapabilitiesMsg* xh_mc_video_capabilities_msg_new(const gchar* encoder_name, FlValue* codecs, gboolean accepts_content_uri) {
  XhMcVideoCapabilitiesMsg* self = XH_MC_VIDEO_CAPABILITIES_MSG(g_object_new(xh_mc_video_capabilities_msg_get_type(), nullptr));
  if (encoder_name != nullptr) {
    self->encoder_name = g_strdup(encoder_name);
  }
  else {
    self->encoder_name = nullptr;
  }
  self->codecs = fl_value_ref(codecs);
  self->accepts_content_uri = accepts_content_uri;
  return self;
}

const gchar* xh_mc_video_capabilities_msg_get_encoder_name(XhMcVideoCapabilitiesMsg* self) {
  g_return_val_if_fail(XH_MC_IS_VIDEO_CAPABILITIES_MSG(self), nullptr);
  return self->encoder_name;
}

FlValue* xh_mc_video_capabilities_msg_get_codecs(XhMcVideoCapabilitiesMsg* self) {
  g_return_val_if_fail(XH_MC_IS_VIDEO_CAPABILITIES_MSG(self), nullptr);
  return self->codecs;
}

gboolean xh_mc_video_capabilities_msg_get_accepts_content_uri(XhMcVideoCapabilitiesMsg* self) {
  g_return_val_if_fail(XH_MC_IS_VIDEO_CAPABILITIES_MSG(self), FALSE);
  return self->accepts_content_uri;
}

static FlValue* xh_mc_video_capabilities_msg_to_list(XhMcVideoCapabilitiesMsg* self) {
  FlValue* values = fl_value_new_list();
  fl_value_append_take(values, self->encoder_name != nullptr ? fl_value_new_string(self->encoder_name) : fl_value_new_null());
  fl_value_append_take(values, fl_value_ref(self->codecs));
  fl_value_append_take(values, fl_value_new_bool(self->accepts_content_uri));
  return values;
}

static XhMcVideoCapabilitiesMsg* xh_mc_video_capabilities_msg_new_from_list(FlValue* values) {
  FlValue* value0 = fl_value_get_list_value(values, 0);
  const gchar* encoder_name = nullptr;
  if (fl_value_get_type(value0) != FL_VALUE_TYPE_NULL) {
    encoder_name = fl_value_get_string(value0);
  }
  FlValue* value1 = fl_value_get_list_value(values, 1);
  FlValue* codecs = value1;
  FlValue* value2 = fl_value_get_list_value(values, 2);
  gboolean accepts_content_uri = fl_value_get_bool(value2);
  return xh_mc_video_capabilities_msg_new(encoder_name, codecs, accepts_content_uri);
}

gboolean xh_mc_video_capabilities_msg_equals(XhMcVideoCapabilitiesMsg* a, XhMcVideoCapabilitiesMsg* b) {
  if (a == b) {
    return TRUE;
  }
  if (a == nullptr || b == nullptr) {
    return FALSE;
  }
  if (g_strcmp0(a->encoder_name, b->encoder_name) != 0) {
    return FALSE;
  }
  if (!flpigeon_deep_equals(a->codecs, b->codecs)) {
    return FALSE;
  }
  if (a->accepts_content_uri != b->accepts_content_uri) {
    return FALSE;
  }
  return TRUE;
}

guint xh_mc_video_capabilities_msg_hash(XhMcVideoCapabilitiesMsg* self) {
  g_return_val_if_fail(XH_MC_IS_VIDEO_CAPABILITIES_MSG(self), 0);
  guint result = 0;
  result = result * 31 + (self->encoder_name != nullptr ? g_str_hash(self->encoder_name) : 0);
  result = result * 31 + flpigeon_deep_hash(self->codecs);
  result = result * 31 + static_cast<guint>(self->accepts_content_uri);
  return result;
}

gchar* xh_mc_video_capabilities_msg_to_string(XhMcVideoCapabilitiesMsg* self) {
  g_return_val_if_fail(XH_MC_IS_VIDEO_CAPABILITIES_MSG(self), NULL);
  GString* str = g_string_new("VideoCapabilitiesMsg(");
  g_string_append(str, "encoder_name: ");
  if (self->encoder_name != nullptr) {
    g_string_append_printf(str, "\"%s\"", self->encoder_name);
  }
  else {
    g_string_append(str, "null");
  }
  g_string_append(str, ", codecs: ");
  if (self->codecs != nullptr) {
    gchar* val_str = flpigeon_to_string(self->codecs);
    g_string_append(str, val_str);
    g_free(val_str);
  }
  else {
    g_string_append(str, "null");
  }
  g_string_append(str, ", accepts_content_uri: ");
  g_string_append(str, self->accepts_content_uri ? "true" : "false");
  g_string_append(str, ")");
  return g_string_free(str, FALSE);
}

struct _XhMcMessageCodec {
  FlStandardMessageCodec parent_instance;

};

G_DEFINE_TYPE(XhMcMessageCodec, xh_mc_message_codec, fl_standard_message_codec_get_type())

const int xh_mc_source_msg_type_id = 129;
const int xh_mc_destination_msg_type_id = 130;
const int xh_mc_image_options_msg_type_id = 131;
const int xh_mc_video_options_msg_type_id = 132;
const int xh_mc_image_capabilities_msg_type_id = 133;
const int xh_mc_video_capabilities_msg_type_id = 134;

static gboolean xh_mc_message_codec_write_xh_mc_source_msg(FlStandardMessageCodec* codec, GByteArray* buffer, XhMcSourceMsg* value, GError** error) {
  uint8_t type = xh_mc_source_msg_type_id;
  g_byte_array_append(buffer, &type, sizeof(uint8_t));
  g_autoptr(FlValue) values = xh_mc_source_msg_to_list(value);
  return fl_standard_message_codec_write_value(codec, buffer, values, error);
}

static gboolean xh_mc_message_codec_write_xh_mc_destination_msg(FlStandardMessageCodec* codec, GByteArray* buffer, XhMcDestinationMsg* value, GError** error) {
  uint8_t type = xh_mc_destination_msg_type_id;
  g_byte_array_append(buffer, &type, sizeof(uint8_t));
  g_autoptr(FlValue) values = xh_mc_destination_msg_to_list(value);
  return fl_standard_message_codec_write_value(codec, buffer, values, error);
}

static gboolean xh_mc_message_codec_write_xh_mc_image_options_msg(FlStandardMessageCodec* codec, GByteArray* buffer, XhMcImageOptionsMsg* value, GError** error) {
  uint8_t type = xh_mc_image_options_msg_type_id;
  g_byte_array_append(buffer, &type, sizeof(uint8_t));
  g_autoptr(FlValue) values = xh_mc_image_options_msg_to_list(value);
  return fl_standard_message_codec_write_value(codec, buffer, values, error);
}

static gboolean xh_mc_message_codec_write_xh_mc_video_options_msg(FlStandardMessageCodec* codec, GByteArray* buffer, XhMcVideoOptionsMsg* value, GError** error) {
  uint8_t type = xh_mc_video_options_msg_type_id;
  g_byte_array_append(buffer, &type, sizeof(uint8_t));
  g_autoptr(FlValue) values = xh_mc_video_options_msg_to_list(value);
  return fl_standard_message_codec_write_value(codec, buffer, values, error);
}

static gboolean xh_mc_message_codec_write_xh_mc_image_capabilities_msg(FlStandardMessageCodec* codec, GByteArray* buffer, XhMcImageCapabilitiesMsg* value, GError** error) {
  uint8_t type = xh_mc_image_capabilities_msg_type_id;
  g_byte_array_append(buffer, &type, sizeof(uint8_t));
  g_autoptr(FlValue) values = xh_mc_image_capabilities_msg_to_list(value);
  return fl_standard_message_codec_write_value(codec, buffer, values, error);
}

static gboolean xh_mc_message_codec_write_xh_mc_video_capabilities_msg(FlStandardMessageCodec* codec, GByteArray* buffer, XhMcVideoCapabilitiesMsg* value, GError** error) {
  uint8_t type = xh_mc_video_capabilities_msg_type_id;
  g_byte_array_append(buffer, &type, sizeof(uint8_t));
  g_autoptr(FlValue) values = xh_mc_video_capabilities_msg_to_list(value);
  return fl_standard_message_codec_write_value(codec, buffer, values, error);
}

static gboolean xh_mc_message_codec_write_value(FlStandardMessageCodec* codec, GByteArray* buffer, FlValue* value, GError** error) {
  if (fl_value_get_type(value) == FL_VALUE_TYPE_CUSTOM) {
    switch (fl_value_get_custom_type(value)) {
      case xh_mc_source_msg_type_id:
        return xh_mc_message_codec_write_xh_mc_source_msg(codec, buffer, XH_MC_SOURCE_MSG(fl_value_get_custom_value_object(value)), error);
      case xh_mc_destination_msg_type_id:
        return xh_mc_message_codec_write_xh_mc_destination_msg(codec, buffer, XH_MC_DESTINATION_MSG(fl_value_get_custom_value_object(value)), error);
      case xh_mc_image_options_msg_type_id:
        return xh_mc_message_codec_write_xh_mc_image_options_msg(codec, buffer, XH_MC_IMAGE_OPTIONS_MSG(fl_value_get_custom_value_object(value)), error);
      case xh_mc_video_options_msg_type_id:
        return xh_mc_message_codec_write_xh_mc_video_options_msg(codec, buffer, XH_MC_VIDEO_OPTIONS_MSG(fl_value_get_custom_value_object(value)), error);
      case xh_mc_image_capabilities_msg_type_id:
        return xh_mc_message_codec_write_xh_mc_image_capabilities_msg(codec, buffer, XH_MC_IMAGE_CAPABILITIES_MSG(fl_value_get_custom_value_object(value)), error);
      case xh_mc_video_capabilities_msg_type_id:
        return xh_mc_message_codec_write_xh_mc_video_capabilities_msg(codec, buffer, XH_MC_VIDEO_CAPABILITIES_MSG(fl_value_get_custom_value_object(value)), error);
    }
  }

  return FL_STANDARD_MESSAGE_CODEC_CLASS(xh_mc_message_codec_parent_class)->write_value(codec, buffer, value, error);
}

static FlValue* xh_mc_message_codec_read_xh_mc_source_msg(FlStandardMessageCodec* codec, GBytes* buffer, size_t* offset, GError** error) {
  g_autoptr(FlValue) values = fl_standard_message_codec_read_value(codec, buffer, offset, error);
  if (values == nullptr) {
    return nullptr;
  }

  g_autoptr(XhMcSourceMsg) value = xh_mc_source_msg_new_from_list(values);
  if (value == nullptr) {
    g_set_error(error, FL_MESSAGE_CODEC_ERROR, FL_MESSAGE_CODEC_ERROR_FAILED, "Invalid data received for MessageData");
    return nullptr;
  }

  return fl_value_new_custom_object(xh_mc_source_msg_type_id, G_OBJECT(value));
}

static FlValue* xh_mc_message_codec_read_xh_mc_destination_msg(FlStandardMessageCodec* codec, GBytes* buffer, size_t* offset, GError** error) {
  g_autoptr(FlValue) values = fl_standard_message_codec_read_value(codec, buffer, offset, error);
  if (values == nullptr) {
    return nullptr;
  }

  g_autoptr(XhMcDestinationMsg) value = xh_mc_destination_msg_new_from_list(values);
  if (value == nullptr) {
    g_set_error(error, FL_MESSAGE_CODEC_ERROR, FL_MESSAGE_CODEC_ERROR_FAILED, "Invalid data received for MessageData");
    return nullptr;
  }

  return fl_value_new_custom_object(xh_mc_destination_msg_type_id, G_OBJECT(value));
}

static FlValue* xh_mc_message_codec_read_xh_mc_image_options_msg(FlStandardMessageCodec* codec, GBytes* buffer, size_t* offset, GError** error) {
  g_autoptr(FlValue) values = fl_standard_message_codec_read_value(codec, buffer, offset, error);
  if (values == nullptr) {
    return nullptr;
  }

  g_autoptr(XhMcImageOptionsMsg) value = xh_mc_image_options_msg_new_from_list(values);
  if (value == nullptr) {
    g_set_error(error, FL_MESSAGE_CODEC_ERROR, FL_MESSAGE_CODEC_ERROR_FAILED, "Invalid data received for MessageData");
    return nullptr;
  }

  return fl_value_new_custom_object(xh_mc_image_options_msg_type_id, G_OBJECT(value));
}

static FlValue* xh_mc_message_codec_read_xh_mc_video_options_msg(FlStandardMessageCodec* codec, GBytes* buffer, size_t* offset, GError** error) {
  g_autoptr(FlValue) values = fl_standard_message_codec_read_value(codec, buffer, offset, error);
  if (values == nullptr) {
    return nullptr;
  }

  g_autoptr(XhMcVideoOptionsMsg) value = xh_mc_video_options_msg_new_from_list(values);
  if (value == nullptr) {
    g_set_error(error, FL_MESSAGE_CODEC_ERROR, FL_MESSAGE_CODEC_ERROR_FAILED, "Invalid data received for MessageData");
    return nullptr;
  }

  return fl_value_new_custom_object(xh_mc_video_options_msg_type_id, G_OBJECT(value));
}

static FlValue* xh_mc_message_codec_read_xh_mc_image_capabilities_msg(FlStandardMessageCodec* codec, GBytes* buffer, size_t* offset, GError** error) {
  g_autoptr(FlValue) values = fl_standard_message_codec_read_value(codec, buffer, offset, error);
  if (values == nullptr) {
    return nullptr;
  }

  g_autoptr(XhMcImageCapabilitiesMsg) value = xh_mc_image_capabilities_msg_new_from_list(values);
  if (value == nullptr) {
    g_set_error(error, FL_MESSAGE_CODEC_ERROR, FL_MESSAGE_CODEC_ERROR_FAILED, "Invalid data received for MessageData");
    return nullptr;
  }

  return fl_value_new_custom_object(xh_mc_image_capabilities_msg_type_id, G_OBJECT(value));
}

static FlValue* xh_mc_message_codec_read_xh_mc_video_capabilities_msg(FlStandardMessageCodec* codec, GBytes* buffer, size_t* offset, GError** error) {
  g_autoptr(FlValue) values = fl_standard_message_codec_read_value(codec, buffer, offset, error);
  if (values == nullptr) {
    return nullptr;
  }

  g_autoptr(XhMcVideoCapabilitiesMsg) value = xh_mc_video_capabilities_msg_new_from_list(values);
  if (value == nullptr) {
    g_set_error(error, FL_MESSAGE_CODEC_ERROR, FL_MESSAGE_CODEC_ERROR_FAILED, "Invalid data received for MessageData");
    return nullptr;
  }

  return fl_value_new_custom_object(xh_mc_video_capabilities_msg_type_id, G_OBJECT(value));
}

static FlValue* xh_mc_message_codec_read_value_of_type(FlStandardMessageCodec* codec, GBytes* buffer, size_t* offset, int type, GError** error) {
  switch (type) {
    case xh_mc_source_msg_type_id:
      return xh_mc_message_codec_read_xh_mc_source_msg(codec, buffer, offset, error);
    case xh_mc_destination_msg_type_id:
      return xh_mc_message_codec_read_xh_mc_destination_msg(codec, buffer, offset, error);
    case xh_mc_image_options_msg_type_id:
      return xh_mc_message_codec_read_xh_mc_image_options_msg(codec, buffer, offset, error);
    case xh_mc_video_options_msg_type_id:
      return xh_mc_message_codec_read_xh_mc_video_options_msg(codec, buffer, offset, error);
    case xh_mc_image_capabilities_msg_type_id:
      return xh_mc_message_codec_read_xh_mc_image_capabilities_msg(codec, buffer, offset, error);
    case xh_mc_video_capabilities_msg_type_id:
      return xh_mc_message_codec_read_xh_mc_video_capabilities_msg(codec, buffer, offset, error);
    default:
      return FL_STANDARD_MESSAGE_CODEC_CLASS(xh_mc_message_codec_parent_class)->read_value_of_type(codec, buffer, offset, type, error);
  }
}

static void xh_mc_message_codec_init(XhMcMessageCodec* self) {
}

static void xh_mc_message_codec_class_init(XhMcMessageCodecClass* klass) {
  FL_STANDARD_MESSAGE_CODEC_CLASS(klass)->write_value = xh_mc_message_codec_write_value;
  FL_STANDARD_MESSAGE_CODEC_CLASS(klass)->read_value_of_type = xh_mc_message_codec_read_value_of_type;
}

static XhMcMessageCodec* xh_mc_message_codec_new() {
  XhMcMessageCodec* self = XH_MC_MESSAGE_CODEC(g_object_new(xh_mc_message_codec_get_type(), nullptr));
  return self;
}

struct _XhMcMediaCompressionHostApiResponseHandle {
  GObject parent_instance;

  FlBasicMessageChannel* channel;
  FlBasicMessageChannelResponseHandle* response_handle;
};

G_DEFINE_TYPE(XhMcMediaCompressionHostApiResponseHandle, xh_mc_media_compression_host_api_response_handle, G_TYPE_OBJECT)

static void xh_mc_media_compression_host_api_response_handle_dispose(GObject* object) {
  XhMcMediaCompressionHostApiResponseHandle* self = XH_MC_MEDIA_COMPRESSION_HOST_API_RESPONSE_HANDLE(object);
  g_clear_object(&self->channel);
  g_clear_object(&self->response_handle);
  G_OBJECT_CLASS(xh_mc_media_compression_host_api_response_handle_parent_class)->dispose(object);
}

static void xh_mc_media_compression_host_api_response_handle_init(XhMcMediaCompressionHostApiResponseHandle* self) {
}

static void xh_mc_media_compression_host_api_response_handle_class_init(XhMcMediaCompressionHostApiResponseHandleClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = xh_mc_media_compression_host_api_response_handle_dispose;
}

static XhMcMediaCompressionHostApiResponseHandle* xh_mc_media_compression_host_api_response_handle_new(FlBasicMessageChannel* channel, FlBasicMessageChannelResponseHandle* response_handle) {
  XhMcMediaCompressionHostApiResponseHandle* self = XH_MC_MEDIA_COMPRESSION_HOST_API_RESPONSE_HANDLE(g_object_new(xh_mc_media_compression_host_api_response_handle_get_type(), nullptr));
  self->channel = FL_BASIC_MESSAGE_CHANNEL(g_object_ref(channel));
  self->response_handle = FL_BASIC_MESSAGE_CHANNEL_RESPONSE_HANDLE(g_object_ref(response_handle));
  return self;
}

struct _XhMcMediaCompressionHostApiCreateJobResponse {
  GObject parent_instance;

  FlValue* value;
};

G_DEFINE_TYPE(XhMcMediaCompressionHostApiCreateJobResponse, xh_mc_media_compression_host_api_create_job_response, G_TYPE_OBJECT)

static void xh_mc_media_compression_host_api_create_job_response_dispose(GObject* object) {
  XhMcMediaCompressionHostApiCreateJobResponse* self = XH_MC_MEDIA_COMPRESSION_HOST_API_CREATE_JOB_RESPONSE(object);
  g_clear_pointer(&self->value, fl_value_unref);
  G_OBJECT_CLASS(xh_mc_media_compression_host_api_create_job_response_parent_class)->dispose(object);
}

static void xh_mc_media_compression_host_api_create_job_response_init(XhMcMediaCompressionHostApiCreateJobResponse* self) {
}

static void xh_mc_media_compression_host_api_create_job_response_class_init(XhMcMediaCompressionHostApiCreateJobResponseClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = xh_mc_media_compression_host_api_create_job_response_dispose;
}

XhMcMediaCompressionHostApiCreateJobResponse* xh_mc_media_compression_host_api_create_job_response_new(int64_t return_value) {
  XhMcMediaCompressionHostApiCreateJobResponse* self = XH_MC_MEDIA_COMPRESSION_HOST_API_CREATE_JOB_RESPONSE(g_object_new(xh_mc_media_compression_host_api_create_job_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_int(return_value));
  return self;
}

XhMcMediaCompressionHostApiCreateJobResponse* xh_mc_media_compression_host_api_create_job_response_new_error(const gchar* code, const gchar* message, FlValue* details) {
  XhMcMediaCompressionHostApiCreateJobResponse* self = XH_MC_MEDIA_COMPRESSION_HOST_API_CREATE_JOB_RESPONSE(g_object_new(xh_mc_media_compression_host_api_create_job_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_string(code));
  fl_value_append_take(self->value, fl_value_new_string(message != nullptr ? message : ""));
  fl_value_append_take(self->value, details != nullptr ? fl_value_ref(details) : fl_value_new_null());
  return self;
}

struct _XhMcMediaCompressionHostApiQueryImageCapabilitiesResponse {
  GObject parent_instance;

  FlValue* value;
};

G_DEFINE_TYPE(XhMcMediaCompressionHostApiQueryImageCapabilitiesResponse, xh_mc_media_compression_host_api_query_image_capabilities_response, G_TYPE_OBJECT)

static void xh_mc_media_compression_host_api_query_image_capabilities_response_dispose(GObject* object) {
  XhMcMediaCompressionHostApiQueryImageCapabilitiesResponse* self = XH_MC_MEDIA_COMPRESSION_HOST_API_QUERY_IMAGE_CAPABILITIES_RESPONSE(object);
  g_clear_pointer(&self->value, fl_value_unref);
  G_OBJECT_CLASS(xh_mc_media_compression_host_api_query_image_capabilities_response_parent_class)->dispose(object);
}

static void xh_mc_media_compression_host_api_query_image_capabilities_response_init(XhMcMediaCompressionHostApiQueryImageCapabilitiesResponse* self) {
}

static void xh_mc_media_compression_host_api_query_image_capabilities_response_class_init(XhMcMediaCompressionHostApiQueryImageCapabilitiesResponseClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = xh_mc_media_compression_host_api_query_image_capabilities_response_dispose;
}

XhMcMediaCompressionHostApiQueryImageCapabilitiesResponse* xh_mc_media_compression_host_api_query_image_capabilities_response_new(XhMcImageCapabilitiesMsg* return_value) {
  XhMcMediaCompressionHostApiQueryImageCapabilitiesResponse* self = XH_MC_MEDIA_COMPRESSION_HOST_API_QUERY_IMAGE_CAPABILITIES_RESPONSE(g_object_new(xh_mc_media_compression_host_api_query_image_capabilities_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_custom_object(xh_mc_image_capabilities_msg_type_id, G_OBJECT(return_value)));
  return self;
}

XhMcMediaCompressionHostApiQueryImageCapabilitiesResponse* xh_mc_media_compression_host_api_query_image_capabilities_response_new_error(const gchar* code, const gchar* message, FlValue* details) {
  XhMcMediaCompressionHostApiQueryImageCapabilitiesResponse* self = XH_MC_MEDIA_COMPRESSION_HOST_API_QUERY_IMAGE_CAPABILITIES_RESPONSE(g_object_new(xh_mc_media_compression_host_api_query_image_capabilities_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_string(code));
  fl_value_append_take(self->value, fl_value_new_string(message != nullptr ? message : ""));
  fl_value_append_take(self->value, details != nullptr ? fl_value_ref(details) : fl_value_new_null());
  return self;
}

G_DECLARE_FINAL_TYPE(XhMcMediaCompressionHostApiStartImageCompressResponse, xh_mc_media_compression_host_api_start_image_compress_response, XH_MC, MEDIA_COMPRESSION_HOST_API_START_IMAGE_COMPRESS_RESPONSE, GObject)

struct _XhMcMediaCompressionHostApiStartImageCompressResponse {
  GObject parent_instance;

  FlValue* value;
};

G_DEFINE_TYPE(XhMcMediaCompressionHostApiStartImageCompressResponse, xh_mc_media_compression_host_api_start_image_compress_response, G_TYPE_OBJECT)

static void xh_mc_media_compression_host_api_start_image_compress_response_dispose(GObject* object) {
  XhMcMediaCompressionHostApiStartImageCompressResponse* self = XH_MC_MEDIA_COMPRESSION_HOST_API_START_IMAGE_COMPRESS_RESPONSE(object);
  g_clear_pointer(&self->value, fl_value_unref);
  G_OBJECT_CLASS(xh_mc_media_compression_host_api_start_image_compress_response_parent_class)->dispose(object);
}

static void xh_mc_media_compression_host_api_start_image_compress_response_init(XhMcMediaCompressionHostApiStartImageCompressResponse* self) {
}

static void xh_mc_media_compression_host_api_start_image_compress_response_class_init(XhMcMediaCompressionHostApiStartImageCompressResponseClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = xh_mc_media_compression_host_api_start_image_compress_response_dispose;
}

static XhMcMediaCompressionHostApiStartImageCompressResponse* xh_mc_media_compression_host_api_start_image_compress_response_new() {
  XhMcMediaCompressionHostApiStartImageCompressResponse* self = XH_MC_MEDIA_COMPRESSION_HOST_API_START_IMAGE_COMPRESS_RESPONSE(g_object_new(xh_mc_media_compression_host_api_start_image_compress_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_null());
  return self;
}

static XhMcMediaCompressionHostApiStartImageCompressResponse* xh_mc_media_compression_host_api_start_image_compress_response_new_error(const gchar* code, const gchar* message, FlValue* details) {
  XhMcMediaCompressionHostApiStartImageCompressResponse* self = XH_MC_MEDIA_COMPRESSION_HOST_API_START_IMAGE_COMPRESS_RESPONSE(g_object_new(xh_mc_media_compression_host_api_start_image_compress_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_string(code));
  fl_value_append_take(self->value, fl_value_new_string(message != nullptr ? message : ""));
  fl_value_append_take(self->value, details != nullptr ? fl_value_ref(details) : fl_value_new_null());
  return self;
}

struct _XhMcMediaCompressionHostApiQueryVideoCapabilitiesResponse {
  GObject parent_instance;

  FlValue* value;
};

G_DEFINE_TYPE(XhMcMediaCompressionHostApiQueryVideoCapabilitiesResponse, xh_mc_media_compression_host_api_query_video_capabilities_response, G_TYPE_OBJECT)

static void xh_mc_media_compression_host_api_query_video_capabilities_response_dispose(GObject* object) {
  XhMcMediaCompressionHostApiQueryVideoCapabilitiesResponse* self = XH_MC_MEDIA_COMPRESSION_HOST_API_QUERY_VIDEO_CAPABILITIES_RESPONSE(object);
  g_clear_pointer(&self->value, fl_value_unref);
  G_OBJECT_CLASS(xh_mc_media_compression_host_api_query_video_capabilities_response_parent_class)->dispose(object);
}

static void xh_mc_media_compression_host_api_query_video_capabilities_response_init(XhMcMediaCompressionHostApiQueryVideoCapabilitiesResponse* self) {
}

static void xh_mc_media_compression_host_api_query_video_capabilities_response_class_init(XhMcMediaCompressionHostApiQueryVideoCapabilitiesResponseClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = xh_mc_media_compression_host_api_query_video_capabilities_response_dispose;
}

XhMcMediaCompressionHostApiQueryVideoCapabilitiesResponse* xh_mc_media_compression_host_api_query_video_capabilities_response_new(XhMcVideoCapabilitiesMsg* return_value) {
  XhMcMediaCompressionHostApiQueryVideoCapabilitiesResponse* self = XH_MC_MEDIA_COMPRESSION_HOST_API_QUERY_VIDEO_CAPABILITIES_RESPONSE(g_object_new(xh_mc_media_compression_host_api_query_video_capabilities_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_custom_object(xh_mc_video_capabilities_msg_type_id, G_OBJECT(return_value)));
  return self;
}

XhMcMediaCompressionHostApiQueryVideoCapabilitiesResponse* xh_mc_media_compression_host_api_query_video_capabilities_response_new_error(const gchar* code, const gchar* message, FlValue* details) {
  XhMcMediaCompressionHostApiQueryVideoCapabilitiesResponse* self = XH_MC_MEDIA_COMPRESSION_HOST_API_QUERY_VIDEO_CAPABILITIES_RESPONSE(g_object_new(xh_mc_media_compression_host_api_query_video_capabilities_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_string(code));
  fl_value_append_take(self->value, fl_value_new_string(message != nullptr ? message : ""));
  fl_value_append_take(self->value, details != nullptr ? fl_value_ref(details) : fl_value_new_null());
  return self;
}

G_DECLARE_FINAL_TYPE(XhMcMediaCompressionHostApiStartVideoCompressResponse, xh_mc_media_compression_host_api_start_video_compress_response, XH_MC, MEDIA_COMPRESSION_HOST_API_START_VIDEO_COMPRESS_RESPONSE, GObject)

struct _XhMcMediaCompressionHostApiStartVideoCompressResponse {
  GObject parent_instance;

  FlValue* value;
};

G_DEFINE_TYPE(XhMcMediaCompressionHostApiStartVideoCompressResponse, xh_mc_media_compression_host_api_start_video_compress_response, G_TYPE_OBJECT)

static void xh_mc_media_compression_host_api_start_video_compress_response_dispose(GObject* object) {
  XhMcMediaCompressionHostApiStartVideoCompressResponse* self = XH_MC_MEDIA_COMPRESSION_HOST_API_START_VIDEO_COMPRESS_RESPONSE(object);
  g_clear_pointer(&self->value, fl_value_unref);
  G_OBJECT_CLASS(xh_mc_media_compression_host_api_start_video_compress_response_parent_class)->dispose(object);
}

static void xh_mc_media_compression_host_api_start_video_compress_response_init(XhMcMediaCompressionHostApiStartVideoCompressResponse* self) {
}

static void xh_mc_media_compression_host_api_start_video_compress_response_class_init(XhMcMediaCompressionHostApiStartVideoCompressResponseClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = xh_mc_media_compression_host_api_start_video_compress_response_dispose;
}

static XhMcMediaCompressionHostApiStartVideoCompressResponse* xh_mc_media_compression_host_api_start_video_compress_response_new() {
  XhMcMediaCompressionHostApiStartVideoCompressResponse* self = XH_MC_MEDIA_COMPRESSION_HOST_API_START_VIDEO_COMPRESS_RESPONSE(g_object_new(xh_mc_media_compression_host_api_start_video_compress_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_null());
  return self;
}

static XhMcMediaCompressionHostApiStartVideoCompressResponse* xh_mc_media_compression_host_api_start_video_compress_response_new_error(const gchar* code, const gchar* message, FlValue* details) {
  XhMcMediaCompressionHostApiStartVideoCompressResponse* self = XH_MC_MEDIA_COMPRESSION_HOST_API_START_VIDEO_COMPRESS_RESPONSE(g_object_new(xh_mc_media_compression_host_api_start_video_compress_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_string(code));
  fl_value_append_take(self->value, fl_value_new_string(message != nullptr ? message : ""));
  fl_value_append_take(self->value, details != nullptr ? fl_value_ref(details) : fl_value_new_null());
  return self;
}

struct _XhMcMediaCompressionHostApiCancelJobResponse {
  GObject parent_instance;

  FlValue* value;
};

G_DEFINE_TYPE(XhMcMediaCompressionHostApiCancelJobResponse, xh_mc_media_compression_host_api_cancel_job_response, G_TYPE_OBJECT)

static void xh_mc_media_compression_host_api_cancel_job_response_dispose(GObject* object) {
  XhMcMediaCompressionHostApiCancelJobResponse* self = XH_MC_MEDIA_COMPRESSION_HOST_API_CANCEL_JOB_RESPONSE(object);
  g_clear_pointer(&self->value, fl_value_unref);
  G_OBJECT_CLASS(xh_mc_media_compression_host_api_cancel_job_response_parent_class)->dispose(object);
}

static void xh_mc_media_compression_host_api_cancel_job_response_init(XhMcMediaCompressionHostApiCancelJobResponse* self) {
}

static void xh_mc_media_compression_host_api_cancel_job_response_class_init(XhMcMediaCompressionHostApiCancelJobResponseClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = xh_mc_media_compression_host_api_cancel_job_response_dispose;
}

XhMcMediaCompressionHostApiCancelJobResponse* xh_mc_media_compression_host_api_cancel_job_response_new() {
  XhMcMediaCompressionHostApiCancelJobResponse* self = XH_MC_MEDIA_COMPRESSION_HOST_API_CANCEL_JOB_RESPONSE(g_object_new(xh_mc_media_compression_host_api_cancel_job_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_null());
  return self;
}

XhMcMediaCompressionHostApiCancelJobResponse* xh_mc_media_compression_host_api_cancel_job_response_new_error(const gchar* code, const gchar* message, FlValue* details) {
  XhMcMediaCompressionHostApiCancelJobResponse* self = XH_MC_MEDIA_COMPRESSION_HOST_API_CANCEL_JOB_RESPONSE(g_object_new(xh_mc_media_compression_host_api_cancel_job_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_string(code));
  fl_value_append_take(self->value, fl_value_new_string(message != nullptr ? message : ""));
  fl_value_append_take(self->value, details != nullptr ? fl_value_ref(details) : fl_value_new_null());
  return self;
}

struct _XhMcMediaCompressionHostApiDisposeJobResponse {
  GObject parent_instance;

  FlValue* value;
};

G_DEFINE_TYPE(XhMcMediaCompressionHostApiDisposeJobResponse, xh_mc_media_compression_host_api_dispose_job_response, G_TYPE_OBJECT)

static void xh_mc_media_compression_host_api_dispose_job_response_dispose(GObject* object) {
  XhMcMediaCompressionHostApiDisposeJobResponse* self = XH_MC_MEDIA_COMPRESSION_HOST_API_DISPOSE_JOB_RESPONSE(object);
  g_clear_pointer(&self->value, fl_value_unref);
  G_OBJECT_CLASS(xh_mc_media_compression_host_api_dispose_job_response_parent_class)->dispose(object);
}

static void xh_mc_media_compression_host_api_dispose_job_response_init(XhMcMediaCompressionHostApiDisposeJobResponse* self) {
}

static void xh_mc_media_compression_host_api_dispose_job_response_class_init(XhMcMediaCompressionHostApiDisposeJobResponseClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = xh_mc_media_compression_host_api_dispose_job_response_dispose;
}

XhMcMediaCompressionHostApiDisposeJobResponse* xh_mc_media_compression_host_api_dispose_job_response_new() {
  XhMcMediaCompressionHostApiDisposeJobResponse* self = XH_MC_MEDIA_COMPRESSION_HOST_API_DISPOSE_JOB_RESPONSE(g_object_new(xh_mc_media_compression_host_api_dispose_job_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_null());
  return self;
}

XhMcMediaCompressionHostApiDisposeJobResponse* xh_mc_media_compression_host_api_dispose_job_response_new_error(const gchar* code, const gchar* message, FlValue* details) {
  XhMcMediaCompressionHostApiDisposeJobResponse* self = XH_MC_MEDIA_COMPRESSION_HOST_API_DISPOSE_JOB_RESPONSE(g_object_new(xh_mc_media_compression_host_api_dispose_job_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_string(code));
  fl_value_append_take(self->value, fl_value_new_string(message != nullptr ? message : ""));
  fl_value_append_take(self->value, details != nullptr ? fl_value_ref(details) : fl_value_new_null());
  return self;
}

struct _XhMcMediaCompressionHostApi {
  GObject parent_instance;

  const XhMcMediaCompressionHostApiVTable* vtable;
  gpointer user_data;
  GDestroyNotify user_data_free_func;
};

G_DEFINE_TYPE(XhMcMediaCompressionHostApi, xh_mc_media_compression_host_api, G_TYPE_OBJECT)

static void xh_mc_media_compression_host_api_dispose(GObject* object) {
  XhMcMediaCompressionHostApi* self = XH_MC_MEDIA_COMPRESSION_HOST_API(object);
  if (self->user_data != nullptr) {
    self->user_data_free_func(self->user_data);
  }
  self->user_data = nullptr;
  G_OBJECT_CLASS(xh_mc_media_compression_host_api_parent_class)->dispose(object);
}

static void xh_mc_media_compression_host_api_init(XhMcMediaCompressionHostApi* self) {
}

static void xh_mc_media_compression_host_api_class_init(XhMcMediaCompressionHostApiClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = xh_mc_media_compression_host_api_dispose;
}

static XhMcMediaCompressionHostApi* xh_mc_media_compression_host_api_new(const XhMcMediaCompressionHostApiVTable* vtable, gpointer user_data, GDestroyNotify user_data_free_func) {
  XhMcMediaCompressionHostApi* self = XH_MC_MEDIA_COMPRESSION_HOST_API(g_object_new(xh_mc_media_compression_host_api_get_type(), nullptr));
  self->vtable = vtable;
  self->user_data = user_data;
  self->user_data_free_func = user_data_free_func;
  return self;
}

static void xh_mc_media_compression_host_api_create_job_cb(FlBasicMessageChannel* channel, FlValue* message_, FlBasicMessageChannelResponseHandle* response_handle, gpointer user_data) {
  XhMcMediaCompressionHostApi* self = XH_MC_MEDIA_COMPRESSION_HOST_API(user_data);

  if (self->vtable == nullptr || self->vtable->create_job == nullptr) {
    return;
  }

  g_autoptr(XhMcMediaCompressionHostApiCreateJobResponse) response = self->vtable->create_job(self->user_data);
  if (response == nullptr) {
    g_warning("No response returned to %s.%s", "MediaCompressionHostApi", "createJob");
    return;
  }

  g_autoptr(GError) error = NULL;
  if (!fl_basic_message_channel_respond(channel, response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "MediaCompressionHostApi", "createJob", error->message);
  }
}

static void xh_mc_media_compression_host_api_query_image_capabilities_cb(FlBasicMessageChannel* channel, FlValue* message_, FlBasicMessageChannelResponseHandle* response_handle, gpointer user_data) {
  XhMcMediaCompressionHostApi* self = XH_MC_MEDIA_COMPRESSION_HOST_API(user_data);

  if (self->vtable == nullptr || self->vtable->query_image_capabilities == nullptr) {
    return;
  }

  g_autoptr(XhMcMediaCompressionHostApiQueryImageCapabilitiesResponse) response = self->vtable->query_image_capabilities(self->user_data);
  if (response == nullptr) {
    g_warning("No response returned to %s.%s", "MediaCompressionHostApi", "queryImageCapabilities");
    return;
  }

  g_autoptr(GError) error = NULL;
  if (!fl_basic_message_channel_respond(channel, response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "MediaCompressionHostApi", "queryImageCapabilities", error->message);
  }
}

static void xh_mc_media_compression_host_api_start_image_compress_cb(FlBasicMessageChannel* channel, FlValue* message_, FlBasicMessageChannelResponseHandle* response_handle, gpointer user_data) {
  XhMcMediaCompressionHostApi* self = XH_MC_MEDIA_COMPRESSION_HOST_API(user_data);

  if (self->vtable == nullptr || self->vtable->start_image_compress == nullptr) {
    return;
  }

  FlValue* value0 = fl_value_get_list_value(message_, 0);
  int64_t id = fl_value_get_int(value0);
  FlValue* value1 = fl_value_get_list_value(message_, 1);
  XhMcSourceMsg* source = XH_MC_SOURCE_MSG(fl_value_get_custom_value_object(value1));
  FlValue* value2 = fl_value_get_list_value(message_, 2);
  XhMcDestinationMsg* destination = XH_MC_DESTINATION_MSG(fl_value_get_custom_value_object(value2));
  FlValue* value3 = fl_value_get_list_value(message_, 3);
  XhMcImageOptionsMsg* options = XH_MC_IMAGE_OPTIONS_MSG(fl_value_get_custom_value_object(value3));
  g_autoptr(XhMcMediaCompressionHostApiResponseHandle) handle = xh_mc_media_compression_host_api_response_handle_new(channel, response_handle);
  self->vtable->start_image_compress(id, source, destination, options, handle, self->user_data);
}

static void xh_mc_media_compression_host_api_query_video_capabilities_cb(FlBasicMessageChannel* channel, FlValue* message_, FlBasicMessageChannelResponseHandle* response_handle, gpointer user_data) {
  XhMcMediaCompressionHostApi* self = XH_MC_MEDIA_COMPRESSION_HOST_API(user_data);

  if (self->vtable == nullptr || self->vtable->query_video_capabilities == nullptr) {
    return;
  }

  g_autoptr(XhMcMediaCompressionHostApiQueryVideoCapabilitiesResponse) response = self->vtable->query_video_capabilities(self->user_data);
  if (response == nullptr) {
    g_warning("No response returned to %s.%s", "MediaCompressionHostApi", "queryVideoCapabilities");
    return;
  }

  g_autoptr(GError) error = NULL;
  if (!fl_basic_message_channel_respond(channel, response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "MediaCompressionHostApi", "queryVideoCapabilities", error->message);
  }
}

static void xh_mc_media_compression_host_api_start_video_compress_cb(FlBasicMessageChannel* channel, FlValue* message_, FlBasicMessageChannelResponseHandle* response_handle, gpointer user_data) {
  XhMcMediaCompressionHostApi* self = XH_MC_MEDIA_COMPRESSION_HOST_API(user_data);

  if (self->vtable == nullptr || self->vtable->start_video_compress == nullptr) {
    return;
  }

  FlValue* value0 = fl_value_get_list_value(message_, 0);
  int64_t id = fl_value_get_int(value0);
  FlValue* value1 = fl_value_get_list_value(message_, 1);
  const gchar* input_path = fl_value_get_string(value1);
  FlValue* value2 = fl_value_get_list_value(message_, 2);
  const gchar* output_path = fl_value_get_string(value2);
  FlValue* value3 = fl_value_get_list_value(message_, 3);
  XhMcVideoOptionsMsg* options = XH_MC_VIDEO_OPTIONS_MSG(fl_value_get_custom_value_object(value3));
  g_autoptr(XhMcMediaCompressionHostApiResponseHandle) handle = xh_mc_media_compression_host_api_response_handle_new(channel, response_handle);
  self->vtable->start_video_compress(id, input_path, output_path, options, handle, self->user_data);
}

static void xh_mc_media_compression_host_api_cancel_job_cb(FlBasicMessageChannel* channel, FlValue* message_, FlBasicMessageChannelResponseHandle* response_handle, gpointer user_data) {
  XhMcMediaCompressionHostApi* self = XH_MC_MEDIA_COMPRESSION_HOST_API(user_data);

  if (self->vtable == nullptr || self->vtable->cancel_job == nullptr) {
    return;
  }

  FlValue* value0 = fl_value_get_list_value(message_, 0);
  int64_t id = fl_value_get_int(value0);
  g_autoptr(XhMcMediaCompressionHostApiCancelJobResponse) response = self->vtable->cancel_job(id, self->user_data);
  if (response == nullptr) {
    g_warning("No response returned to %s.%s", "MediaCompressionHostApi", "cancelJob");
    return;
  }

  g_autoptr(GError) error = NULL;
  if (!fl_basic_message_channel_respond(channel, response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "MediaCompressionHostApi", "cancelJob", error->message);
  }
}

static void xh_mc_media_compression_host_api_dispose_job_cb(FlBasicMessageChannel* channel, FlValue* message_, FlBasicMessageChannelResponseHandle* response_handle, gpointer user_data) {
  XhMcMediaCompressionHostApi* self = XH_MC_MEDIA_COMPRESSION_HOST_API(user_data);

  if (self->vtable == nullptr || self->vtable->dispose_job == nullptr) {
    return;
  }

  FlValue* value0 = fl_value_get_list_value(message_, 0);
  int64_t id = fl_value_get_int(value0);
  g_autoptr(XhMcMediaCompressionHostApiDisposeJobResponse) response = self->vtable->dispose_job(id, self->user_data);
  if (response == nullptr) {
    g_warning("No response returned to %s.%s", "MediaCompressionHostApi", "disposeJob");
    return;
  }

  g_autoptr(GError) error = NULL;
  if (!fl_basic_message_channel_respond(channel, response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "MediaCompressionHostApi", "disposeJob", error->message);
  }
}

void xh_mc_media_compression_host_api_set_method_handlers(FlBinaryMessenger* messenger, const gchar* suffix, const XhMcMediaCompressionHostApiVTable* vtable, gpointer user_data, GDestroyNotify user_data_free_func) {
  g_autofree gchar* dot_suffix = suffix != nullptr ? g_strdup_printf(".%s", suffix) : g_strdup("");
  g_autoptr(XhMcMediaCompressionHostApi) api_data = xh_mc_media_compression_host_api_new(vtable, user_data, user_data_free_func);

  g_autoptr(XhMcMessageCodec) codec = xh_mc_message_codec_new();
  g_autofree gchar* create_job_channel_name = g_strdup_printf("dev.flutter.pigeon.xue_hua_media_compression_platform_interface.MediaCompressionHostApi.createJob%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) create_job_channel = fl_basic_message_channel_new(messenger, create_job_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(create_job_channel, xh_mc_media_compression_host_api_create_job_cb, g_object_ref(api_data), g_object_unref);
  g_autofree gchar* query_image_capabilities_channel_name = g_strdup_printf("dev.flutter.pigeon.xue_hua_media_compression_platform_interface.MediaCompressionHostApi.queryImageCapabilities%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) query_image_capabilities_channel = fl_basic_message_channel_new(messenger, query_image_capabilities_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(query_image_capabilities_channel, xh_mc_media_compression_host_api_query_image_capabilities_cb, g_object_ref(api_data), g_object_unref);
  g_autofree gchar* start_image_compress_channel_name = g_strdup_printf("dev.flutter.pigeon.xue_hua_media_compression_platform_interface.MediaCompressionHostApi.startImageCompress%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) start_image_compress_channel = fl_basic_message_channel_new(messenger, start_image_compress_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(start_image_compress_channel, xh_mc_media_compression_host_api_start_image_compress_cb, g_object_ref(api_data), g_object_unref);
  g_autofree gchar* query_video_capabilities_channel_name = g_strdup_printf("dev.flutter.pigeon.xue_hua_media_compression_platform_interface.MediaCompressionHostApi.queryVideoCapabilities%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) query_video_capabilities_channel = fl_basic_message_channel_new(messenger, query_video_capabilities_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(query_video_capabilities_channel, xh_mc_media_compression_host_api_query_video_capabilities_cb, g_object_ref(api_data), g_object_unref);
  g_autofree gchar* start_video_compress_channel_name = g_strdup_printf("dev.flutter.pigeon.xue_hua_media_compression_platform_interface.MediaCompressionHostApi.startVideoCompress%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) start_video_compress_channel = fl_basic_message_channel_new(messenger, start_video_compress_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(start_video_compress_channel, xh_mc_media_compression_host_api_start_video_compress_cb, g_object_ref(api_data), g_object_unref);
  g_autofree gchar* cancel_job_channel_name = g_strdup_printf("dev.flutter.pigeon.xue_hua_media_compression_platform_interface.MediaCompressionHostApi.cancelJob%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) cancel_job_channel = fl_basic_message_channel_new(messenger, cancel_job_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(cancel_job_channel, xh_mc_media_compression_host_api_cancel_job_cb, g_object_ref(api_data), g_object_unref);
  g_autofree gchar* dispose_job_channel_name = g_strdup_printf("dev.flutter.pigeon.xue_hua_media_compression_platform_interface.MediaCompressionHostApi.disposeJob%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) dispose_job_channel = fl_basic_message_channel_new(messenger, dispose_job_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(dispose_job_channel, xh_mc_media_compression_host_api_dispose_job_cb, g_object_ref(api_data), g_object_unref);
}

void xh_mc_media_compression_host_api_clear_method_handlers(FlBinaryMessenger* messenger, const gchar* suffix) {
  g_autofree gchar* dot_suffix = suffix != nullptr ? g_strdup_printf(".%s", suffix) : g_strdup("");

  g_autoptr(XhMcMessageCodec) codec = xh_mc_message_codec_new();
  g_autofree gchar* create_job_channel_name = g_strdup_printf("dev.flutter.pigeon.xue_hua_media_compression_platform_interface.MediaCompressionHostApi.createJob%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) create_job_channel = fl_basic_message_channel_new(messenger, create_job_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(create_job_channel, nullptr, nullptr, nullptr);
  g_autofree gchar* query_image_capabilities_channel_name = g_strdup_printf("dev.flutter.pigeon.xue_hua_media_compression_platform_interface.MediaCompressionHostApi.queryImageCapabilities%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) query_image_capabilities_channel = fl_basic_message_channel_new(messenger, query_image_capabilities_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(query_image_capabilities_channel, nullptr, nullptr, nullptr);
  g_autofree gchar* start_image_compress_channel_name = g_strdup_printf("dev.flutter.pigeon.xue_hua_media_compression_platform_interface.MediaCompressionHostApi.startImageCompress%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) start_image_compress_channel = fl_basic_message_channel_new(messenger, start_image_compress_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(start_image_compress_channel, nullptr, nullptr, nullptr);
  g_autofree gchar* query_video_capabilities_channel_name = g_strdup_printf("dev.flutter.pigeon.xue_hua_media_compression_platform_interface.MediaCompressionHostApi.queryVideoCapabilities%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) query_video_capabilities_channel = fl_basic_message_channel_new(messenger, query_video_capabilities_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(query_video_capabilities_channel, nullptr, nullptr, nullptr);
  g_autofree gchar* start_video_compress_channel_name = g_strdup_printf("dev.flutter.pigeon.xue_hua_media_compression_platform_interface.MediaCompressionHostApi.startVideoCompress%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) start_video_compress_channel = fl_basic_message_channel_new(messenger, start_video_compress_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(start_video_compress_channel, nullptr, nullptr, nullptr);
  g_autofree gchar* cancel_job_channel_name = g_strdup_printf("dev.flutter.pigeon.xue_hua_media_compression_platform_interface.MediaCompressionHostApi.cancelJob%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) cancel_job_channel = fl_basic_message_channel_new(messenger, cancel_job_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(cancel_job_channel, nullptr, nullptr, nullptr);
  g_autofree gchar* dispose_job_channel_name = g_strdup_printf("dev.flutter.pigeon.xue_hua_media_compression_platform_interface.MediaCompressionHostApi.disposeJob%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) dispose_job_channel = fl_basic_message_channel_new(messenger, dispose_job_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(dispose_job_channel, nullptr, nullptr, nullptr);
}

void xh_mc_media_compression_host_api_respond_start_image_compress(XhMcMediaCompressionHostApiResponseHandle* response_handle) {
  g_autoptr(XhMcMediaCompressionHostApiStartImageCompressResponse) response = xh_mc_media_compression_host_api_start_image_compress_response_new();
  g_autoptr(GError) error = nullptr;
  if (!fl_basic_message_channel_respond(response_handle->channel, response_handle->response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "MediaCompressionHostApi", "startImageCompress", error->message);
  }
}

void xh_mc_media_compression_host_api_respond_error_start_image_compress(XhMcMediaCompressionHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details) {
  g_autoptr(XhMcMediaCompressionHostApiStartImageCompressResponse) response = xh_mc_media_compression_host_api_start_image_compress_response_new_error(code, message, details);
  g_autoptr(GError) error = nullptr;
  if (!fl_basic_message_channel_respond(response_handle->channel, response_handle->response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "MediaCompressionHostApi", "startImageCompress", error->message);
  }
}

void xh_mc_media_compression_host_api_respond_start_video_compress(XhMcMediaCompressionHostApiResponseHandle* response_handle) {
  g_autoptr(XhMcMediaCompressionHostApiStartVideoCompressResponse) response = xh_mc_media_compression_host_api_start_video_compress_response_new();
  g_autoptr(GError) error = nullptr;
  if (!fl_basic_message_channel_respond(response_handle->channel, response_handle->response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "MediaCompressionHostApi", "startVideoCompress", error->message);
  }
}

void xh_mc_media_compression_host_api_respond_error_start_video_compress(XhMcMediaCompressionHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details) {
  g_autoptr(XhMcMediaCompressionHostApiStartVideoCompressResponse) response = xh_mc_media_compression_host_api_start_video_compress_response_new_error(code, message, details);
  g_autoptr(GError) error = nullptr;
  if (!fl_basic_message_channel_respond(response_handle->channel, response_handle->response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "MediaCompressionHostApi", "startVideoCompress", error->message);
  }
}
