// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'traits.dart';

// These functions are ignored because they are not marked as `pub`: `decode_any`, `decode_heic`, `downscale_to_max`, `encode_avif`, `encode_gif`, `encode_heic`, `encode_jpeg`, `encode_png`, `encode_webp`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<GenericImageCompressor>>
abstract class GenericImageCompressor
    implements RustOpaqueInterface, ImageCompressor {
  static Future<Uint8List> compress({
    required List<int> input,
    required ImageOptions opts,
  }) => RustLib.instance.api.crateApiImageGenericImageCompressorCompress(
    input: input,
    opts: opts,
  );
}
