// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'traits.dart';

/// 返回当前平台所用的视频硬编后端名称，便于 Dart 侧诊断与展示。
Future<String> rustVideoBackendName() =>
    RustLib.instance.api.crateApiMediaRustVideoBackendName();

/// 压缩图片。输入/输出均为内存字节。
///
/// - `input`: 原始图片字节（任意受支持的输入格式）。
/// - `opts` : 目标格式与质量等参数。
Future<Uint8List> rustCompressImage({
  required List<int> input,
  required ImageOptions opts,
}) => RustLib.instance.api.crateApiMediaRustCompressImage(
  input: input,
  opts: opts,
);

/// 便捷封装：直接读文件 -> 压缩 -> 写文件，返回输出文件字节数。
Future<BigInt> rustCompressImageFile({
  required String inputPath,
  required String outputPath,
  required ImageOptions opts,
}) => RustLib.instance.api.crateApiMediaRustCompressImageFile(
  inputPath: inputPath,
  outputPath: outputPath,
  opts: opts,
);

/// 压缩视频：读取 `input_path`，用平台硬件编码器编码并封装为 MP4 写到 `output_path`。
Future<VideoResult> rustCompressVideo({
  required String inputPath,
  required String outputPath,
  required VideoOptions opts,
}) => RustLib.instance.api.crateApiMediaRustCompressVideo(
  inputPath: inputPath,
  outputPath: outputPath,
  opts: opts,
);

/// 构造默认图片选项（Dart 侧可直接拿到带默认值的结构体）。
Future<ImageOptions> rustDefaultImageOptions() =>
    RustLib.instance.api.crateApiMediaRustDefaultImageOptions();

/// 构造默认视频选项。
Future<VideoOptions> rustDefaultVideoOptions() =>
    RustLib.instance.api.crateApiMediaRustDefaultVideoOptions();
