// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'traits.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`

abstract class ImageCompressor {}

abstract class VideoCompressor {}

/// 目标图片格式。
enum ImageFormat { jpeg, png, webP, gif, heic, avif }

/// 图片压缩参数。
class ImageOptions {
  /// 目标输出格式。
  final ImageFormat format;

  /// 质量 0-100（对有损格式 JPEG/WebP/AVIF/HEIC 有效）。
  final int quality;

  /// 可选：等比缩放到的最大边长（像素）。`None` 表示不缩放。
  final int? maxDimension;

  /// 编码速度档位 0-10（对 AVIF/HEIC 有效，越大越快质量略降）。
  final int? speed;

  const ImageOptions({
    required this.format,
    required this.quality,
    this.maxDimension,
    this.speed,
  });

  static Future<ImageOptions> default_() =>
      RustLib.instance.api.crateApiTraitsImageOptionsDefault();

  @override
  int get hashCode =>
      format.hashCode ^
      quality.hashCode ^
      maxDimension.hashCode ^
      speed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImageOptions &&
          runtimeType == other.runtimeType &&
          format == other.format &&
          quality == other.quality &&
          maxDimension == other.maxDimension &&
          speed == other.speed;
}

@freezed
sealed class MediaError with _$MediaError implements FrbException {
  const MediaError._();

  const factory MediaError.unsupportedFormat(String field0) =
      MediaError_UnsupportedFormat;
  const factory MediaError.decode(String field0) = MediaError_Decode;
  const factory MediaError.encode(String field0) = MediaError_Encode;
  const factory MediaError.hardwareUnavailable(String field0) =
      MediaError_HardwareUnavailable;
  const factory MediaError.mux(String field0) = MediaError_Mux;
  const factory MediaError.io(String field0) = MediaError_Io;
  const factory MediaError.native({
    required PlatformInt64 code,
    required String msg,
  }) = MediaError_Native;
}

/// 目标视频编码。
enum VideoCodec { h264, h265 }

/// 视频压缩参数。
class VideoOptions {
  /// 目标编码（H.264 / H.265）。
  final VideoCodec codec;

  /// 目标平均码率（bps）。
  final int bitrate;

  /// 目标帧率。`None` 表示沿用源帧率。
  final int? fps;

  /// 可选：等比缩放到的最大边长（像素）。
  final int? maxDimension;

  /// 关键帧间隔（GOP，单位为帧）。
  final int? keyframeInterval;

  const VideoOptions({
    required this.codec,
    required this.bitrate,
    this.fps,
    this.maxDimension,
    this.keyframeInterval,
  });

  static Future<VideoOptions> default_() =>
      RustLib.instance.api.crateApiTraitsVideoOptionsDefault();

  @override
  int get hashCode =>
      codec.hashCode ^
      bitrate.hashCode ^
      fps.hashCode ^
      maxDimension.hashCode ^
      keyframeInterval.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VideoOptions &&
          runtimeType == other.runtimeType &&
          codec == other.codec &&
          bitrate == other.bitrate &&
          fps == other.fps &&
          maxDimension == other.maxDimension &&
          keyframeInterval == other.keyframeInterval;
}

/// 视频压缩结果。
class VideoResult {
  /// 输出文件路径。
  final String outputPath;

  /// 输出文件大小（字节）。
  final BigInt sizeBytes;

  /// 实际使用的编码后端（如 "MediaFoundation" / "VideoToolbox"）。
  final String backend;

  /// 输出视频宽高。
  final int width;
  final int height;

  const VideoResult({
    required this.outputPath,
    required this.sizeBytes,
    required this.backend,
    required this.width,
    required this.height,
  });

  @override
  int get hashCode =>
      outputPath.hashCode ^
      sizeBytes.hashCode ^
      backend.hashCode ^
      width.hashCode ^
      height.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VideoResult &&
          runtimeType == other.runtimeType &&
          outputPath == other.outputPath &&
          sizeBytes == other.sizeBytes &&
          backend == other.backend &&
          width == other.width &&
          height == other.height;
}
