// Generated file. Do not edit.
// Autogenerated from Pigeon (v27.3.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#undef _HAS_EXCEPTIONS

#include "messages.g.h"

#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <cmath>
#include <limits>
#include <map>
#include <optional>
#include <sstream>
#include <string>

namespace xue_hua_media_compression {
using ::flutter::BasicMessageChannel;
using ::flutter::CustomEncodableValue;
using ::flutter::EncodableList;
using ::flutter::EncodableMap;
using ::flutter::EncodableValue;

FlutterError CreateConnectionError(const std::string channel_name) {
  return FlutterError(
      "channel-error",
      "Unable to establish connection on channel: '" + channel_name + "'.",
      EncodableValue(""));
}

namespace {
template<typename T>
bool PigeonInternalDeepEquals(const T& a, const T& b);

bool PigeonInternalDeepEquals(const double& a, const double& b);

template<typename T>
bool PigeonInternalDeepEquals(const std::vector<T>& a, const std::vector<T>& b);

template<typename K, typename V>
bool PigeonInternalDeepEquals(const std::map<K, V>& a, const std::map<K, V>& b);

template<typename T>
bool PigeonInternalDeepEquals(const std::optional<T>& a, const std::optional<T>& b);

template<typename T>
bool PigeonInternalDeepEquals(const std::unique_ptr<T>& a, const std::unique_ptr<T>& b);

bool PigeonInternalDeepEquals(const ::flutter::EncodableValue& a, const ::flutter::EncodableValue& b);

template<typename T>
bool PigeonInternalDeepEquals(const T& a, const T& b) {
  return a == b;
}

template<typename T>
bool PigeonInternalDeepEquals(const std::vector<T>& a, const std::vector<T>& b) {
  if (a.size() != b.size()) {
    return false;
  }
  for (size_t i = 0; i < a.size(); ++i) {
    if (!PigeonInternalDeepEquals(a[i], b[i])) {
      return false;
    }
  }
  return true;
}

template <typename K, typename V>
bool PigeonInternalDeepEquals(const std::map<K, V>& a, const std::map<K, V>& b) {
  if (a.size() != b.size()) {
    return false;
  }
  for (const auto& kv : a) {
    bool found = false;
    for (const auto& b_kv : b) {
      if (PigeonInternalDeepEquals(kv.first, b_kv.first)) {
        if (PigeonInternalDeepEquals(kv.second, b_kv.second)) {
          found = true;
          break;
        } else {
          return false;
        }
      }
    }
    if (!found) {
      return false;
    }
  }
  return true;
}

bool PigeonInternalDeepEquals(const double& a, const double& b) {
  // Normalize -0.0 to 0.0 and handle NaN equality.
  return (a == b) || (std::isnan(a) && std::isnan(b));
}

template<typename T>
bool PigeonInternalDeepEquals(const std::optional<T>& a, const std::optional<T>& b) {
  if (!a && !b) {
    return true;
  }
  if (!a || !b) {
    return false;
  }
  return PigeonInternalDeepEquals(*a, *b);
}

template<typename T>
bool PigeonInternalDeepEquals(const std::unique_ptr<T>& a, const std::unique_ptr<T>& b) {
  if (a.get() == b.get()) {
    return true;
  }
  if (!a || !b) {
    return false;
  }
  return PigeonInternalDeepEquals(*a, *b);
}

bool PigeonInternalDeepEquals(const ::flutter::EncodableValue& a, const ::flutter::EncodableValue& b) {
  if (a.index() != b.index()) {
    return false;
  }
  if (const double* da = std::get_if<double>(&a)) {
    return PigeonInternalDeepEquals(*da, std::get<double>(b));
  } else if (const ::flutter::EncodableList* la = std::get_if<::flutter::EncodableList>(&a)) {
    return PigeonInternalDeepEquals(*la, std::get<::flutter::EncodableList>(b));
  } else if (const ::flutter::EncodableMap* ma = std::get_if<::flutter::EncodableMap>(&a)) {
    return PigeonInternalDeepEquals(*ma, std::get<::flutter::EncodableMap>(b));
  }
  return a == b;
}

template <typename T>
size_t PigeonInternalDeepHash(const T& v);

size_t PigeonInternalDeepHash(const double& v);

template <typename T>
size_t PigeonInternalDeepHash(const std::vector<T>& v);

template <typename K, typename V>
size_t PigeonInternalDeepHash(const std::map<K, V>& v);

template <typename T>
size_t PigeonInternalDeepHash(const std::optional<T>& v);

template <typename T>
size_t PigeonInternalDeepHash(const std::unique_ptr<T>& v);

size_t PigeonInternalDeepHash(const ::flutter::EncodableValue& v);

template <typename T>
size_t PigeonInternalDeepHash(const T& v) {
  return std::hash<T>()(v);
}

template <typename T>
size_t PigeonInternalDeepHash(const std::vector<T>& v) {
  size_t result = 1;
  for (const auto& item : v) {
    result = result * 31 + PigeonInternalDeepHash(item);
  }
  return result;
}

template <typename K, typename V>
size_t PigeonInternalDeepHash(const std::map<K, V>& v) {
  size_t result = 0;
  for (const auto& kv : v) {
    result += ((PigeonInternalDeepHash(kv.first) * 31) ^ PigeonInternalDeepHash(kv.second));
  }
  return result;
}

size_t PigeonInternalDeepHash(const double& v) {
  if (std::isnan(v)) {
    // Normalize NaN to a consistent hash.
    return std::hash<double>()(std::numeric_limits<double>::quiet_NaN());
  }
  if (v == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return std::hash<double>()(0.0);
  }
  return std::hash<double>()(v);
}

template <typename T>
size_t PigeonInternalDeepHash(const std::optional<T>& v) {
  return v ? PigeonInternalDeepHash(*v) : 0;
}

template <typename T>
size_t PigeonInternalDeepHash(const std::unique_ptr<T>& v) {
  return v ? PigeonInternalDeepHash(*v) : 0;
}

size_t PigeonInternalDeepHash(const ::flutter::EncodableValue& v) {
  size_t result = v.index();
  if (const double* dv = std::get_if<double>(&v)) {
    result = result * 31 + PigeonInternalDeepHash(*dv);
  } else if (const ::flutter::EncodableList* lv =
                 std::get_if<::flutter::EncodableList>(&v)) {
    result = result * 31 + PigeonInternalDeepHash(*lv);
  } else if (const ::flutter::EncodableMap* mv =
                 std::get_if<::flutter::EncodableMap>(&v)) {
    result = result * 31 + PigeonInternalDeepHash(*mv);
  } else {
    std::visit(
        [&result](const auto& val) {
          using T = std::decay_t<decltype(val)>;
          if constexpr (!std::is_same_v<T, double> &&
                        !std::is_same_v<T, ::flutter::EncodableList> &&
                        !std::is_same_v<T, ::flutter::EncodableMap> &&
                        !std::is_same_v<T, std::monostate> &&
                        !std::is_same_v<T, ::flutter::CustomEncodableValue>) {
            result = result * 31 + PigeonInternalDeepHash(val);
          }
        },
        v);
  }
  return result;
}

template <typename T>
std::string PigeonInternalToString(const T& v);

std::string PigeonInternalToString(const bool& v);

template <typename T>
std::string PigeonInternalToString(const std::vector<T>& v);

template <typename K, typename V>
std::string PigeonInternalToString(const std::map<K, V>& v);

template <typename T>
std::string PigeonInternalToString(const std::optional<T>& v);

template <typename T>
std::string PigeonInternalToString(const std::unique_ptr<T>& v);

std::string PigeonInternalToString(const ::flutter::EncodableValue& v);

template <typename T>
std::string PigeonInternalToString(const T& v) {
  std::stringstream ss;
  if constexpr (std::is_enum_v<T>) {
    ss << static_cast<int>(v);
  } else {
    ss << v;
  }
  return ss.str();
}

std::string PigeonInternalToString(const bool& v) {
  return v ? "true" : "false";
}

template <typename T>
std::string PigeonInternalToString(const std::vector<T>& v) {
  std::stringstream ss;
  ss << "[";
  for (size_t i = 0; i < v.size(); ++i) {
    if (i > 0) {
      ss << ", ";
    }
    ss << PigeonInternalToString(v[i]);
  }
  ss << "]";
  return ss.str();
}

template <typename K, typename V>
std::string PigeonInternalToString(const std::map<K, V>& v) {
  std::stringstream ss;
  ss << "{";
  bool first = true;
  for (const auto& kv : v) {
    if (!first) {
      ss << ", ";
    }
    first = false;
    ss << PigeonInternalToString(kv.first) << ": " << PigeonInternalToString(kv.second);
  }
  ss << "}";
  return ss.str();
}

template <typename T>
std::string PigeonInternalToString(const std::optional<T>& v) {
  return v ? PigeonInternalToString(*v) : "null";
}

template <typename T>
std::string PigeonInternalToString(const std::unique_ptr<T>& v) {
  return v ? PigeonInternalToString(*v) : "null";
}

std::string PigeonInternalToString(const ::flutter::EncodableValue& v) {
  return std::visit(
      [](const auto& val) {
        using T = std::decay_t<decltype(val)>;
        if constexpr (std::is_same_v<T, std::monostate>) {
          return std::string("null");
        } else if constexpr (std::is_same_v<T, bool>) {
          return val ? std::string("true") : std::string("false");
        } else if constexpr (std::is_same_v<T, std::string>) {
          return "\"" + val + "\"";
        } else if constexpr (std::is_same_v<T, ::flutter::CustomEncodableValue>) {
          return std::string("[custom]");
        } else {
          return PigeonInternalToString(val);
        }
      },
      v);
}

}  // namespace
// SourceMsg

SourceMsg::SourceMsg(int64_t kind)
 : kind_(kind) {}

SourceMsg::SourceMsg(
  int64_t kind,
  const std::vector<uint8_t>* bytes,
  const std::string* path)
 : kind_(kind),
    bytes_(bytes ? std::optional<std::vector<uint8_t>>(*bytes) : std::nullopt),
    path_(path ? std::optional<std::string>(*path) : std::nullopt) {}

int64_t SourceMsg::kind() const {
  return kind_;
}

void SourceMsg::set_kind(int64_t value_arg) {
  kind_ = value_arg;
}


const std::vector<uint8_t>* SourceMsg::bytes() const {
  return bytes_ ? &(*bytes_) : nullptr;
}

void SourceMsg::set_bytes(const std::vector<uint8_t>* value_arg) {
  bytes_ = value_arg ? std::optional<std::vector<uint8_t>>(*value_arg) : std::nullopt;
}

void SourceMsg::set_bytes(const std::vector<uint8_t>& value_arg) {
  bytes_ = value_arg;
}


const std::string* SourceMsg::path() const {
  return path_ ? &(*path_) : nullptr;
}

void SourceMsg::set_path(const std::string_view* value_arg) {
  path_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void SourceMsg::set_path(std::string_view value_arg) {
  path_ = value_arg;
}


EncodableList SourceMsg::ToEncodableList() const {
  EncodableList list;
  list.reserve(3);
  list.push_back(EncodableValue(kind_));
  list.push_back(bytes_ ? EncodableValue(*bytes_) : EncodableValue());
  list.push_back(path_ ? EncodableValue(*path_) : EncodableValue());
  return list;
}

SourceMsg SourceMsg::FromEncodableList(const EncodableList& list) {
  SourceMsg decoded(
    std::get<int64_t>(list[0]));
  auto& encodable_bytes = list[1];
  if (!encodable_bytes.IsNull()) {
    decoded.set_bytes(std::get<std::vector<uint8_t>>(encodable_bytes));
  }
  auto& encodable_path = list[2];
  if (!encodable_path.IsNull()) {
    decoded.set_path(std::get<std::string>(encodable_path));
  }
  return decoded;
}

bool SourceMsg::operator==(const SourceMsg& other) const {
  return PigeonInternalDeepEquals(kind_, other.kind_) && PigeonInternalDeepEquals(bytes_, other.bytes_) && PigeonInternalDeepEquals(path_, other.path_);
}

bool SourceMsg::operator!=(const SourceMsg& other) const {
  return !(*this == other);
}

size_t SourceMsg::Hash() const {
  size_t result = 1;
  result = result * 31 + PigeonInternalDeepHash(kind_);
  result = result * 31 + PigeonInternalDeepHash(bytes_);
  result = result * 31 + PigeonInternalDeepHash(path_);
  return result;
}

std::ostream& operator<<(
  std::ostream& os,
  const SourceMsg& obj) {
  os << "SourceMsg(";
  os << "kind: ";
  os << PigeonInternalToString(obj.kind_);
  os << ", bytes: ";
  if (obj.bytes_) {
    os << PigeonInternalToString(*obj.bytes_);
  }
  else {
    os << "null";
  }
  os << ", path: ";
  if (obj.path_) {
    os << PigeonInternalToString(*obj.path_);
  }
  else {
    os << "null";
  }
  os << ")";
  return os;
}

size_t PigeonInternalDeepHash(const SourceMsg& v) {
  return v.Hash();
}

// DestinationMsg

DestinationMsg::DestinationMsg(int64_t kind)
 : kind_(kind) {}

DestinationMsg::DestinationMsg(
  int64_t kind,
  const std::string* path)
 : kind_(kind),
    path_(path ? std::optional<std::string>(*path) : std::nullopt) {}

int64_t DestinationMsg::kind() const {
  return kind_;
}

void DestinationMsg::set_kind(int64_t value_arg) {
  kind_ = value_arg;
}


const std::string* DestinationMsg::path() const {
  return path_ ? &(*path_) : nullptr;
}

void DestinationMsg::set_path(const std::string_view* value_arg) {
  path_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void DestinationMsg::set_path(std::string_view value_arg) {
  path_ = value_arg;
}


EncodableList DestinationMsg::ToEncodableList() const {
  EncodableList list;
  list.reserve(2);
  list.push_back(EncodableValue(kind_));
  list.push_back(path_ ? EncodableValue(*path_) : EncodableValue());
  return list;
}

DestinationMsg DestinationMsg::FromEncodableList(const EncodableList& list) {
  DestinationMsg decoded(
    std::get<int64_t>(list[0]));
  auto& encodable_path = list[1];
  if (!encodable_path.IsNull()) {
    decoded.set_path(std::get<std::string>(encodable_path));
  }
  return decoded;
}

bool DestinationMsg::operator==(const DestinationMsg& other) const {
  return PigeonInternalDeepEquals(kind_, other.kind_) && PigeonInternalDeepEquals(path_, other.path_);
}

bool DestinationMsg::operator!=(const DestinationMsg& other) const {
  return !(*this == other);
}

size_t DestinationMsg::Hash() const {
  size_t result = 1;
  result = result * 31 + PigeonInternalDeepHash(kind_);
  result = result * 31 + PigeonInternalDeepHash(path_);
  return result;
}

std::ostream& operator<<(
  std::ostream& os,
  const DestinationMsg& obj) {
  os << "DestinationMsg(";
  os << "kind: ";
  os << PigeonInternalToString(obj.kind_);
  os << ", path: ";
  if (obj.path_) {
    os << PigeonInternalToString(*obj.path_);
  }
  else {
    os << "null";
  }
  os << ")";
  return os;
}

size_t PigeonInternalDeepHash(const DestinationMsg& v) {
  return v.Hash();
}

// ImageOptionsMsg

ImageOptionsMsg::ImageOptionsMsg(
  const std::string& format,
  int64_t quality)
 : format_(format),
    quality_(quality) {}

ImageOptionsMsg::ImageOptionsMsg(
  const std::string& format,
  int64_t quality,
  const int64_t* max_dimension)
 : format_(format),
    quality_(quality),
    max_dimension_(max_dimension ? std::optional<int64_t>(*max_dimension) : std::nullopt) {}

const std::string& ImageOptionsMsg::format() const {
  return format_;
}

void ImageOptionsMsg::set_format(std::string_view value_arg) {
  format_ = value_arg;
}


int64_t ImageOptionsMsg::quality() const {
  return quality_;
}

void ImageOptionsMsg::set_quality(int64_t value_arg) {
  quality_ = value_arg;
}


const int64_t* ImageOptionsMsg::max_dimension() const {
  return max_dimension_ ? &(*max_dimension_) : nullptr;
}

void ImageOptionsMsg::set_max_dimension(const int64_t* value_arg) {
  max_dimension_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void ImageOptionsMsg::set_max_dimension(int64_t value_arg) {
  max_dimension_ = value_arg;
}


EncodableList ImageOptionsMsg::ToEncodableList() const {
  EncodableList list;
  list.reserve(3);
  list.push_back(EncodableValue(format_));
  list.push_back(EncodableValue(quality_));
  list.push_back(max_dimension_ ? EncodableValue(*max_dimension_) : EncodableValue());
  return list;
}

ImageOptionsMsg ImageOptionsMsg::FromEncodableList(const EncodableList& list) {
  ImageOptionsMsg decoded(
    std::get<std::string>(list[0]),
    std::get<int64_t>(list[1]));
  auto& encodable_max_dimension = list[2];
  if (!encodable_max_dimension.IsNull()) {
    decoded.set_max_dimension(std::get<int64_t>(encodable_max_dimension));
  }
  return decoded;
}

bool ImageOptionsMsg::operator==(const ImageOptionsMsg& other) const {
  return PigeonInternalDeepEquals(format_, other.format_) && PigeonInternalDeepEquals(quality_, other.quality_) && PigeonInternalDeepEquals(max_dimension_, other.max_dimension_);
}

bool ImageOptionsMsg::operator!=(const ImageOptionsMsg& other) const {
  return !(*this == other);
}

size_t ImageOptionsMsg::Hash() const {
  size_t result = 1;
  result = result * 31 + PigeonInternalDeepHash(format_);
  result = result * 31 + PigeonInternalDeepHash(quality_);
  result = result * 31 + PigeonInternalDeepHash(max_dimension_);
  return result;
}

std::ostream& operator<<(
  std::ostream& os,
  const ImageOptionsMsg& obj) {
  os << "ImageOptionsMsg(";
  os << "format: ";
  os << PigeonInternalToString(obj.format_);
  os << ", quality: ";
  os << PigeonInternalToString(obj.quality_);
  os << ", max_dimension: ";
  if (obj.max_dimension_) {
    os << PigeonInternalToString(*obj.max_dimension_);
  }
  else {
    os << "null";
  }
  os << ")";
  return os;
}

size_t PigeonInternalDeepHash(const ImageOptionsMsg& v) {
  return v.Hash();
}

// VideoOptionsMsg

VideoOptionsMsg::VideoOptionsMsg(
  const std::string& codec,
  int64_t bitrate)
 : codec_(codec),
    bitrate_(bitrate) {}

VideoOptionsMsg::VideoOptionsMsg(
  const std::string& codec,
  int64_t bitrate,
  const int64_t* fps,
  const int64_t* max_dimension,
  const int64_t* keyframe_interval)
 : codec_(codec),
    bitrate_(bitrate),
    fps_(fps ? std::optional<int64_t>(*fps) : std::nullopt),
    max_dimension_(max_dimension ? std::optional<int64_t>(*max_dimension) : std::nullopt),
    keyframe_interval_(keyframe_interval ? std::optional<int64_t>(*keyframe_interval) : std::nullopt) {}

const std::string& VideoOptionsMsg::codec() const {
  return codec_;
}

void VideoOptionsMsg::set_codec(std::string_view value_arg) {
  codec_ = value_arg;
}


int64_t VideoOptionsMsg::bitrate() const {
  return bitrate_;
}

void VideoOptionsMsg::set_bitrate(int64_t value_arg) {
  bitrate_ = value_arg;
}


const int64_t* VideoOptionsMsg::fps() const {
  return fps_ ? &(*fps_) : nullptr;
}

void VideoOptionsMsg::set_fps(const int64_t* value_arg) {
  fps_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void VideoOptionsMsg::set_fps(int64_t value_arg) {
  fps_ = value_arg;
}


const int64_t* VideoOptionsMsg::max_dimension() const {
  return max_dimension_ ? &(*max_dimension_) : nullptr;
}

void VideoOptionsMsg::set_max_dimension(const int64_t* value_arg) {
  max_dimension_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void VideoOptionsMsg::set_max_dimension(int64_t value_arg) {
  max_dimension_ = value_arg;
}


const int64_t* VideoOptionsMsg::keyframe_interval() const {
  return keyframe_interval_ ? &(*keyframe_interval_) : nullptr;
}

void VideoOptionsMsg::set_keyframe_interval(const int64_t* value_arg) {
  keyframe_interval_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void VideoOptionsMsg::set_keyframe_interval(int64_t value_arg) {
  keyframe_interval_ = value_arg;
}


EncodableList VideoOptionsMsg::ToEncodableList() const {
  EncodableList list;
  list.reserve(5);
  list.push_back(EncodableValue(codec_));
  list.push_back(EncodableValue(bitrate_));
  list.push_back(fps_ ? EncodableValue(*fps_) : EncodableValue());
  list.push_back(max_dimension_ ? EncodableValue(*max_dimension_) : EncodableValue());
  list.push_back(keyframe_interval_ ? EncodableValue(*keyframe_interval_) : EncodableValue());
  return list;
}

VideoOptionsMsg VideoOptionsMsg::FromEncodableList(const EncodableList& list) {
  VideoOptionsMsg decoded(
    std::get<std::string>(list[0]),
    std::get<int64_t>(list[1]));
  auto& encodable_fps = list[2];
  if (!encodable_fps.IsNull()) {
    decoded.set_fps(std::get<int64_t>(encodable_fps));
  }
  auto& encodable_max_dimension = list[3];
  if (!encodable_max_dimension.IsNull()) {
    decoded.set_max_dimension(std::get<int64_t>(encodable_max_dimension));
  }
  auto& encodable_keyframe_interval = list[4];
  if (!encodable_keyframe_interval.IsNull()) {
    decoded.set_keyframe_interval(std::get<int64_t>(encodable_keyframe_interval));
  }
  return decoded;
}

bool VideoOptionsMsg::operator==(const VideoOptionsMsg& other) const {
  return PigeonInternalDeepEquals(codec_, other.codec_) && PigeonInternalDeepEquals(bitrate_, other.bitrate_) && PigeonInternalDeepEquals(fps_, other.fps_) && PigeonInternalDeepEquals(max_dimension_, other.max_dimension_) && PigeonInternalDeepEquals(keyframe_interval_, other.keyframe_interval_);
}

bool VideoOptionsMsg::operator!=(const VideoOptionsMsg& other) const {
  return !(*this == other);
}

size_t VideoOptionsMsg::Hash() const {
  size_t result = 1;
  result = result * 31 + PigeonInternalDeepHash(codec_);
  result = result * 31 + PigeonInternalDeepHash(bitrate_);
  result = result * 31 + PigeonInternalDeepHash(fps_);
  result = result * 31 + PigeonInternalDeepHash(max_dimension_);
  result = result * 31 + PigeonInternalDeepHash(keyframe_interval_);
  return result;
}

std::ostream& operator<<(
  std::ostream& os,
  const VideoOptionsMsg& obj) {
  os << "VideoOptionsMsg(";
  os << "codec: ";
  os << PigeonInternalToString(obj.codec_);
  os << ", bitrate: ";
  os << PigeonInternalToString(obj.bitrate_);
  os << ", fps: ";
  if (obj.fps_) {
    os << PigeonInternalToString(*obj.fps_);
  }
  else {
    os << "null";
  }
  os << ", max_dimension: ";
  if (obj.max_dimension_) {
    os << PigeonInternalToString(*obj.max_dimension_);
  }
  else {
    os << "null";
  }
  os << ", keyframe_interval: ";
  if (obj.keyframe_interval_) {
    os << PigeonInternalToString(*obj.keyframe_interval_);
  }
  else {
    os << "null";
  }
  os << ")";
  return os;
}

size_t PigeonInternalDeepHash(const VideoOptionsMsg& v) {
  return v.Hash();
}

// ImageCapabilitiesMsg

ImageCapabilitiesMsg::ImageCapabilitiesMsg(
  const EncodableList& input_formats,
  const EncodableList& output_formats)
 : input_formats_(input_formats),
    output_formats_(output_formats) {}

const EncodableList& ImageCapabilitiesMsg::input_formats() const {
  return input_formats_;
}

void ImageCapabilitiesMsg::set_input_formats(const EncodableList& value_arg) {
  input_formats_ = value_arg;
}


const EncodableList& ImageCapabilitiesMsg::output_formats() const {
  return output_formats_;
}

void ImageCapabilitiesMsg::set_output_formats(const EncodableList& value_arg) {
  output_formats_ = value_arg;
}


EncodableList ImageCapabilitiesMsg::ToEncodableList() const {
  EncodableList list;
  list.reserve(2);
  list.push_back(EncodableValue(input_formats_));
  list.push_back(EncodableValue(output_formats_));
  return list;
}

ImageCapabilitiesMsg ImageCapabilitiesMsg::FromEncodableList(const EncodableList& list) {
  ImageCapabilitiesMsg decoded(
    std::get<EncodableList>(list[0]),
    std::get<EncodableList>(list[1]));
  return decoded;
}

bool ImageCapabilitiesMsg::operator==(const ImageCapabilitiesMsg& other) const {
  return PigeonInternalDeepEquals(input_formats_, other.input_formats_) && PigeonInternalDeepEquals(output_formats_, other.output_formats_);
}

bool ImageCapabilitiesMsg::operator!=(const ImageCapabilitiesMsg& other) const {
  return !(*this == other);
}

size_t ImageCapabilitiesMsg::Hash() const {
  size_t result = 1;
  result = result * 31 + PigeonInternalDeepHash(input_formats_);
  result = result * 31 + PigeonInternalDeepHash(output_formats_);
  return result;
}

std::ostream& operator<<(
  std::ostream& os,
  const ImageCapabilitiesMsg& obj) {
  os << "ImageCapabilitiesMsg(";
  os << "input_formats: ";
  os << PigeonInternalToString(obj.input_formats_);
  os << ", output_formats: ";
  os << PigeonInternalToString(obj.output_formats_);
  os << ")";
  return os;
}

size_t PigeonInternalDeepHash(const ImageCapabilitiesMsg& v) {
  return v.Hash();
}

// VideoCapabilitiesMsg

VideoCapabilitiesMsg::VideoCapabilitiesMsg(
  const EncodableList& codecs,
  bool accepts_content_uri)
 : codecs_(codecs),
    accepts_content_uri_(accepts_content_uri) {}

VideoCapabilitiesMsg::VideoCapabilitiesMsg(
  const std::string* encoder_name,
  const EncodableList& codecs,
  bool accepts_content_uri)
 : encoder_name_(encoder_name ? std::optional<std::string>(*encoder_name) : std::nullopt),
    codecs_(codecs),
    accepts_content_uri_(accepts_content_uri) {}

const std::string* VideoCapabilitiesMsg::encoder_name() const {
  return encoder_name_ ? &(*encoder_name_) : nullptr;
}

void VideoCapabilitiesMsg::set_encoder_name(const std::string_view* value_arg) {
  encoder_name_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void VideoCapabilitiesMsg::set_encoder_name(std::string_view value_arg) {
  encoder_name_ = value_arg;
}


const EncodableList& VideoCapabilitiesMsg::codecs() const {
  return codecs_;
}

void VideoCapabilitiesMsg::set_codecs(const EncodableList& value_arg) {
  codecs_ = value_arg;
}


bool VideoCapabilitiesMsg::accepts_content_uri() const {
  return accepts_content_uri_;
}

void VideoCapabilitiesMsg::set_accepts_content_uri(bool value_arg) {
  accepts_content_uri_ = value_arg;
}


EncodableList VideoCapabilitiesMsg::ToEncodableList() const {
  EncodableList list;
  list.reserve(3);
  list.push_back(encoder_name_ ? EncodableValue(*encoder_name_) : EncodableValue());
  list.push_back(EncodableValue(codecs_));
  list.push_back(EncodableValue(accepts_content_uri_));
  return list;
}

VideoCapabilitiesMsg VideoCapabilitiesMsg::FromEncodableList(const EncodableList& list) {
  VideoCapabilitiesMsg decoded(
    std::get<EncodableList>(list[1]),
    std::get<bool>(list[2]));
  auto& encodable_encoder_name = list[0];
  if (!encodable_encoder_name.IsNull()) {
    decoded.set_encoder_name(std::get<std::string>(encodable_encoder_name));
  }
  return decoded;
}

bool VideoCapabilitiesMsg::operator==(const VideoCapabilitiesMsg& other) const {
  return PigeonInternalDeepEquals(encoder_name_, other.encoder_name_) && PigeonInternalDeepEquals(codecs_, other.codecs_) && PigeonInternalDeepEquals(accepts_content_uri_, other.accepts_content_uri_);
}

bool VideoCapabilitiesMsg::operator!=(const VideoCapabilitiesMsg& other) const {
  return !(*this == other);
}

size_t VideoCapabilitiesMsg::Hash() const {
  size_t result = 1;
  result = result * 31 + PigeonInternalDeepHash(encoder_name_);
  result = result * 31 + PigeonInternalDeepHash(codecs_);
  result = result * 31 + PigeonInternalDeepHash(accepts_content_uri_);
  return result;
}

std::ostream& operator<<(
  std::ostream& os,
  const VideoCapabilitiesMsg& obj) {
  os << "VideoCapabilitiesMsg(";
  os << "encoder_name: ";
  if (obj.encoder_name_) {
    os << PigeonInternalToString(*obj.encoder_name_);
  }
  else {
    os << "null";
  }
  os << ", codecs: ";
  os << PigeonInternalToString(obj.codecs_);
  os << ", accepts_content_uri: ";
  os << PigeonInternalToString(obj.accepts_content_uri_);
  os << ")";
  return os;
}

size_t PigeonInternalDeepHash(const VideoCapabilitiesMsg& v) {
  return v.Hash();
}


PigeonInternalCodecSerializer::PigeonInternalCodecSerializer() {}

EncodableValue PigeonInternalCodecSerializer::ReadValueOfType(
  uint8_t type,
  ::flutter::ByteStreamReader* stream) const {
  switch (type) {
    case 129: {
        return CustomEncodableValue(SourceMsg::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 130: {
        return CustomEncodableValue(DestinationMsg::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 131: {
        return CustomEncodableValue(ImageOptionsMsg::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 132: {
        return CustomEncodableValue(VideoOptionsMsg::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 133: {
        return CustomEncodableValue(ImageCapabilitiesMsg::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 134: {
        return CustomEncodableValue(VideoCapabilitiesMsg::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    default:
      return ::flutter::StandardCodecSerializer::ReadValueOfType(type, stream);
    }
}

void PigeonInternalCodecSerializer::WriteValue(
  const EncodableValue& value,
  ::flutter::ByteStreamWriter* stream) const {
  if (const CustomEncodableValue* custom_value = std::get_if<CustomEncodableValue>(&value)) {
    if (custom_value->type() == typeid(SourceMsg)) {
      stream->WriteByte(129);
      WriteValue(EncodableValue(std::any_cast<SourceMsg>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(DestinationMsg)) {
      stream->WriteByte(130);
      WriteValue(EncodableValue(std::any_cast<DestinationMsg>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(ImageOptionsMsg)) {
      stream->WriteByte(131);
      WriteValue(EncodableValue(std::any_cast<ImageOptionsMsg>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(VideoOptionsMsg)) {
      stream->WriteByte(132);
      WriteValue(EncodableValue(std::any_cast<VideoOptionsMsg>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(ImageCapabilitiesMsg)) {
      stream->WriteByte(133);
      WriteValue(EncodableValue(std::any_cast<ImageCapabilitiesMsg>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(VideoCapabilitiesMsg)) {
      stream->WriteByte(134);
      WriteValue(EncodableValue(std::any_cast<VideoCapabilitiesMsg>(*custom_value).ToEncodableList()), stream);
      return;
    }
  }
  ::flutter::StandardCodecSerializer::WriteValue(value, stream);
}

/// The codec used by MediaCompressionHostApi.
const ::flutter::StandardMessageCodec& MediaCompressionHostApi::GetCodec() {
  return ::flutter::StandardMessageCodec::GetInstance(&PigeonInternalCodecSerializer::GetInstance());
}

// Sets up an instance of `MediaCompressionHostApi` to handle messages through the `binary_messenger`.
void MediaCompressionHostApi::SetUp(
  ::flutter::BinaryMessenger* binary_messenger,
  MediaCompressionHostApi* api) {
  MediaCompressionHostApi::SetUp(binary_messenger, api, "");
}

void MediaCompressionHostApi::SetUp(
  ::flutter::BinaryMessenger* binary_messenger,
  MediaCompressionHostApi* api,
  const std::string& message_channel_suffix) {
  const std::string prepended_suffix = message_channel_suffix.length() > 0 ? std::string(".") + message_channel_suffix : "";
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.xue_hua_media_compression_platform_interface.MediaCompressionHostApi.createJob" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          ErrorOr<int64_t> output = api->CreateJob();
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.xue_hua_media_compression_platform_interface.MediaCompressionHostApi.queryImageCapabilities" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          ErrorOr<ImageCapabilitiesMsg> output = api->QueryImageCapabilities();
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.xue_hua_media_compression_platform_interface.MediaCompressionHostApi.startImageCompress" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_id_arg = args.at(0);
          if (encodable_id_arg.IsNull()) {
            reply(WrapError("id_arg unexpectedly null."));
            return;
          }
          const int64_t id_arg = encodable_id_arg.LongValue();
          const auto& encodable_source_arg = args.at(1);
          if (encodable_source_arg.IsNull()) {
            reply(WrapError("source_arg unexpectedly null."));
            return;
          }
          const auto& source_arg = std::any_cast<const SourceMsg&>(std::get<CustomEncodableValue>(encodable_source_arg));
          const auto& encodable_destination_arg = args.at(2);
          if (encodable_destination_arg.IsNull()) {
            reply(WrapError("destination_arg unexpectedly null."));
            return;
          }
          const auto& destination_arg = std::any_cast<const DestinationMsg&>(std::get<CustomEncodableValue>(encodable_destination_arg));
          const auto& encodable_options_arg = args.at(3);
          if (encodable_options_arg.IsNull()) {
            reply(WrapError("options_arg unexpectedly null."));
            return;
          }
          const auto& options_arg = std::any_cast<const ImageOptionsMsg&>(std::get<CustomEncodableValue>(encodable_options_arg));
          api->StartImageCompress(id_arg, source_arg, destination_arg, options_arg, [reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.xue_hua_media_compression_platform_interface.MediaCompressionHostApi.queryVideoCapabilities" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          ErrorOr<VideoCapabilitiesMsg> output = api->QueryVideoCapabilities();
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.xue_hua_media_compression_platform_interface.MediaCompressionHostApi.startVideoCompress" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_id_arg = args.at(0);
          if (encodable_id_arg.IsNull()) {
            reply(WrapError("id_arg unexpectedly null."));
            return;
          }
          const int64_t id_arg = encodable_id_arg.LongValue();
          const auto& encodable_input_path_arg = args.at(1);
          if (encodable_input_path_arg.IsNull()) {
            reply(WrapError("input_path_arg unexpectedly null."));
            return;
          }
          const auto& input_path_arg = std::get<std::string>(encodable_input_path_arg);
          const auto& encodable_output_path_arg = args.at(2);
          if (encodable_output_path_arg.IsNull()) {
            reply(WrapError("output_path_arg unexpectedly null."));
            return;
          }
          const auto& output_path_arg = std::get<std::string>(encodable_output_path_arg);
          const auto& encodable_options_arg = args.at(3);
          if (encodable_options_arg.IsNull()) {
            reply(WrapError("options_arg unexpectedly null."));
            return;
          }
          const auto& options_arg = std::any_cast<const VideoOptionsMsg&>(std::get<CustomEncodableValue>(encodable_options_arg));
          api->StartVideoCompress(id_arg, input_path_arg, output_path_arg, options_arg, [reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.xue_hua_media_compression_platform_interface.MediaCompressionHostApi.cancelJob" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_id_arg = args.at(0);
          if (encodable_id_arg.IsNull()) {
            reply(WrapError("id_arg unexpectedly null."));
            return;
          }
          const int64_t id_arg = encodable_id_arg.LongValue();
          std::optional<FlutterError> output = api->CancelJob(id_arg);
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.xue_hua_media_compression_platform_interface.MediaCompressionHostApi.disposeJob" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_id_arg = args.at(0);
          if (encodable_id_arg.IsNull()) {
            reply(WrapError("id_arg unexpectedly null."));
            return;
          }
          const int64_t id_arg = encodable_id_arg.LongValue();
          std::optional<FlutterError> output = api->DisposeJob(id_arg);
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
}

EncodableValue MediaCompressionHostApi::WrapError(std::string_view error_message) {
  return EncodableValue(EncodableList{
    EncodableValue(std::string(error_message)),
    EncodableValue("Error"),
    EncodableValue()
  });
}

EncodableValue MediaCompressionHostApi::WrapError(const FlutterError& error) {
  return EncodableValue(EncodableList{
    EncodableValue(error.code()),
    EncodableValue(error.message()),
    error.details()
  });
}

}  // namespace xue_hua_media_compression
