name: xue_hua_media_compression_android
description: Android implementation of xue_hua_media_compression.
version: 2.0.0
homepage: https://github.com/Matkurban/xue_hua_media_compression
repository: https://github.com/Matkurban/xue_hua_media_compression
issue_tracker: https://github.com/Matkurban/xue_hua_media_compression/issues
resolution: workspace

environment:
  sdk: ^3.12.0
  flutter: '>=3.44.0'

dependencies:
  flutter:
    sdk: flutter
  xue_hua_media_compression_platform_interface: ^2.0.0

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  plugin:
    implements: xue_hua_media_compression
    platforms:
      android:
        package: com.xuehua.xue_hua_media_compression
        pluginClass: XueHuaMediaCompressionPlugin
